### ISSUE TITLE
console.log("...") output should be shown in the traces section

### ISSUE THREAD

**Issue by 0xalfalfa** [foundry-rs/foundry#1024]
### Component

Forge

### Describe the feature you would like

Currently console.log("...") output is shown in "Logs:" output section. 

It would be really helpful to see the output at the correct location in the "Traces:" section of the output.

**Comment by onbjerg** [comment]
This is not present in the REVM port either because 1) it clutters the traces and 2) `console.log` has borked function signatures that we need to patch. If we want to include it in the traces we need to patch function selectors every time there is a call to the `console.log` address which may degrade performance.

I'm curious why you think it would be useful to have it in traces - can you elaborate a bit on your use case?

**Comment by 0xalfalfa** [comment]
My use case is that I follow the trace from top to bottom to locate a problem. Then, I add a console.log in my code to output further debugging information that I need to pinpoint the problem and run the test again.
At that point, I find myself scrolling between the traces and Logs section and try to map when which log output happened in the chronological order of the trace output. 
It just would be handy and easier to read to have the output inline in the trace section. Right now, it's actually more readable to emit my own events with debug information instead of using console.log.

**Comment by onbjerg** [comment]
Solved in https://github.com/foundry-rs/foundry/pull/1367 (thanks @mds1!), but it requries that you use a patched version of `console.sol` from here: https://github.com/foundry-rs/forge-std/blob/master/src/console2.sol
