### ISSUE TITLE
tx.gasprice always set to 0

### ISSUE THREAD

**Issue by benesjan** [foundry-rs/foundry#1143]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5916d38 2022-03-30T16:31:01.267891+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

tx.gasprice is always set to 0. This is the case even when gas_price parameter in foundry.toml is set to non-zero value.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/13470840/160888967-8a4c90fe-7679-41d5-a7e4-c00075fedc74.png">

`function testDisplayBaseFeeAndGasPrice() public {
        emit log_uint(block.basefee);
        emit log_uint(tx.gasprice);
    }`

**Comment by onbjerg** [comment]
@gakonst @brockelmore So gas price is 0 because that is what we use to actually *execute* the transaction. The same is true of the block - the basefee is actually 0, but once execution starts the cheatcode handler replaces the block that the EVM sees with one configured by the user (or from the fork) that may have a basefee > 0.

So essentially:

- Block always has 0 gas price, high gas limit from our POV, but from EVM POV these can be non-0
- Transaction always has 0 gas price, since we do not replace tx info the same way as we do for blocks

I see two paths forward:

- We remove the gas price thing. I'm not sure how much that would break, but honestly, I can't really see any use case for it, given that we never surface the actual value spent on the call, only the gas consumed
- We handle transactions the same way as blocks - this would only be the case for some parameters

Wdyt?

**Comment by gakonst** [comment]
Either can work - it feels like handling it the same way we handle blocks is better though?

**Comment by benesjan** [comment]
> @benesjan What is the use case here/what are you trying to achieve with `tx.gasprice`?

Hello,
I use tx.gasprice to compute how much a swap path would cost. I need to decide what complexity of a path it makes sense to use for a given token amount and this is best represented by gas cost. [Here](https://github.com/benesjan/path-registry/blob/30a908e123cc4bfc34c0a030df2434efac27a4ba/src/PathRegistry.sol#L260) is the line where I use it.
