### ISSUE TITLE
Do not squelch ETH RPC errors that affect test execution

### ISSUE THREAD

**Issue by aathan** [foundry-rs/foundry#1294]
### Component

Forge

### Describe the feature you would like

Forge verbose (-v*) and/or other logs should include ETH RPC errors so that problem like #385 and #1287 cause a bigger failure instead of only returning invalid (zero) values in the EVM emulation.

**Comment by Peter-Flynn** [comment]
Invalid RPC data has caused me more grief than I'd like to admit. Passing those errors through to the terminal would have saved me hours of troubleshooting. Even though it's an issue that one would recognize immediately on subsequent occurrences, it'd definitely be helpful to have forge recognize the issue and deal with it appropriately rather than failing tests, or the like.
