### ISSUE TITLE
Better error message if config failed to parse

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1372]
### Component

Forge

### Describe the feature you would like

currently, the parsing error in the config is rather verbose, ideally, it should highlight the very value that's erroneous.

### Additional context

Ref #275

**Comment by lattejed** [comment]
I assume this about `foundry.toml`, if not please ignore.

It would also be good if pointing `FOUNDRY_CONFIG` to a non-existent or invalid file printed an error. 

I made the mistake of exporting `FOUNDRY_CONFIG=foo` instead of `FOUNDRY_PROFILE=foo` and then spent half an hour trying to figure out why my config file wasn't being read.

**Comment by mattsse** [comment]
oh, thanks for this, will add a check and warning if the path does not exist!
