### ISSUE TITLE
Surface more information about revert reasons (Dapp/HEVM parity)

### ISSUE THREAD

**Issue by iamchrissmith** [foundry-rs/foundry#1387]
### Component

Forge

### Describe the feature you would like

Currently when a call reverts during a test, we get limited reasons for the revert.  Dapp/HEVM test provides more information (see screen shots of the two outputs).

![forge-failure](https://user-images.githubusercontent.com/1408372/164765002-292cc035-9e2d-41b8-90bf-531614451506.png)
![dapp-failure](https://user-images.githubusercontent.com/1408372/164765003-81f735ff-c4b8-4883-bef4-5ce48600e4bc.png)

### Additional context

adjusting the verbosity of the tests did not seem to change this part of the output

**Comment by onbjerg** [comment]
That's weird, what kind of errors are you using? I assume custom errors? Can you share an example of where this happens? The reverts should be decoded, so this is a bug (marking it as such)

**Comment by mds1** [comment]
I think there are at least a few revert edge cases that don't currently show any information except `()`, which should be handled better. Let me try to come up with a test file demonstrating these and I'll drop it here.

**Comment by iamchrissmith** [comment]
@onbjerg and @mds1 thanks for taking a look at this.  I created a basic and arbitrary example of how to recreate this specific issue in this branch https://github.com/makerdao/dss/pull/265 

Let me know if that helps or if I can provide any more information

**Comment by mds1** [comment]
Ok there are actually _a lot_ more cases than I realized, so maybe I won't be putting a POC together for each just yet 😅
- [Here](https://github.com/dapphub/dapptools/blob/master/src/hevm/src/EVM.hs#L71) is the list of revert cases HEVM handles, you can see the `StateChangeWhileStatic` one that @iamchrissmith is looking for. 
- [Here](https://github.com/NomicFoundation/hardhat/blob/43dd1d5a519084529fedba411eb5d665405d28da/packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-stack-trace.ts#L7) are the ones Hardhat looks for.

An additional one is deploying a contract to an address that already has code.

I've encountered a few of those in testing and they usually just show `()` in the trace and `[FAIL. Reason: Revert]` as the revert reason.  For reference, some geth errors are [here](https://github.com/ethereum/go-ethereum/blob/f32feeb260054d7c90c1efd57dfec6b717717e18/core/error.go#L97-L98), though not all would be applicable.

The ones that I think should be prioritized are based on what I've seen in foundry support:
- ETH balance too low
- State change while static
- Function not payable
- `fallback` not payable and no `receive`
- Calling an address that has no code
- No fallback method and function selector not found
- Deploying a contract to an address that already has code

**Comment by onbjerg** [comment]
Ahh those, ok. I was under the impression that this was a custom revert, but these reverts are already on my todo list. It requires some changes in REVM - at a top level, REVM just turns all of this into a revert, so we need to catch the actual revert reason in `call_end`/`create_end` before this transformation. This is not currently the case for all code paths that can revert

**Comment by gakonst** [comment]
@meetmangukiya is this something of interest to you?

**Comment by meetmangukiya** [comment]
Yeah, have been looking into this past few days. Most of these are solidity security features and no direct status from revm.

Hardhat does most of [these detections](https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/stack-traces/error-inferrer.ts) by looking into last few steps / opcodes. Thinking how to maintain such state, can store steps history with current inspector's `step` / `step_end` and on a revert can peek that the same way hardhat does. `call_end` / `create_end` won't be of much help here because most of these inference require looking into past few steps. I think we want to be able to decode the reverts in [trace decoder too](https://github.com/gakonst/foundry/blob/f2b88826e9613948b96bbdd520c4d63cb43fc978/evm/src/trace/decoder.rs#L272-L279) but inspector context won't be available there even if we end up storing and collecting steps history in one of the inspectors. 

Any suggestions on a good way to share the steps history context with the trace decoder and in multiple other places where [`decode_revert`](https://github.com/gakonst/foundry/blob/6f2ce13208cde6f7241b2a3d97b3c8d79fb3a6c2/utils/src/lib.rs#L305) gets used?

**Comment by meetmangukiya** [comment]
Yes, that seems like the only way to record the execution steps.

**Comment by onbjerg** [comment]
I don't think doing it in `step` is necessary - essentially it is a "bug"/incompleteness in REVM where the `call_end`/`create_end` method is *not* called in the correct places (e.g. when you're out of funds), so we'd need to redesign the call_inner/create_inner functions in REVM to *always* call `call_end`/`create_end` whenever it returns.

**Comment by onbjerg** [comment]
See for example here:

If we're too deep, we just return an error (which will unwind all execution so it's OK, but we don't catch this error):

https://github.com/bluealloy/revm/blob/eb7af7080dd89d5d75e9438395d02ee623651135/crates/revm/src/evm_impl.rs#L467-L469

Same for funds etc. These are then converted by REVM to just being a "revert". We only ever call `call_end` in the end after the interpreter has run: https://github.com/bluealloy/revm/blob/eb7af7080dd89d5d75e9438395d02ee623651135/crates/revm/src/evm_impl.rs#L552-L553

Or if we short-circuit using an inspector: https://github.com/bluealloy/revm/blob/eb7af7080dd89d5d75e9438395d02ee623651135/crates/revm/src/evm_impl.rs#L451

**Comment by onbjerg** [comment]
Also ref #476 (same underlying issue)

**Comment by mds1** [comment]
> The ones that I think should be prioritized are based on what I've seen in foundry support:
> 
> - ETH balance too low
> - State change while static
> - Function not payable
> - fallback not payable and no receive
> - Calling an address that has no code
> - No fallback method and function selector not found
> - Deploying a contract to an address that already has code

Just to confirm, where all of the above implemented and now properly decoded in traces as part of #2130? There are also other revert reasons linked in https://github.com/foundry-rs/foundry/issues/1387#issuecomment-1107518351 which we should track somewhere (maybe they are tracked somewhere, but this issue was the main one I'm aware of, so given that it's now closed I'm just checking status here)

**Comment by onbjerg** [comment]
If they surface VM errors then they are covered by #2130, yes. If they require deeper analysis from our side then it was not implemented

**Comment by mds1** [comment]
How do you/we know which error is which? For example I would have suspected https://github.com/foundry-rs/foundry/issues/2479 to be a VM error but I don't actually know.

Lack of clear error messages in traces has been a pain point IME, so I'm happy to help setup issues or something for tracking these if you need 🙂

**Comment by onbjerg** [comment]
It is a VM error, so I'm unsure if the person that posted that issue did not update. They didn't post the version of Forge they are using
