### ISSUE TITLE
Nul Byte Error when using FFI 

### ISSUE THREAD

**Issue by Gaonuk** [foundry-rs/foundry#1447]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (107f477 2022-04-28T00:12:56.368074407+00:00)

### What command(s) is the bug in?

forge test --ffi

### Operating System

Linux

### Describe the bug

Running forge test with ffi enabled and trying to pass an encoded array of addresses generates a `[FAIL. Reason: nul byte found in provided data]`

Here is the code i'm using that creates the error
``` solidity
(address[] memory components, uint256[] memory quantities) = exchangeModule.getRequiredIssuanceComponents(address(issuanceModule), false, outputToken, web3Amount);
string[] memory inputs = new string[](4);
inputs[0] = "node";
inputs[1] = "scripts/fetch-quotes.js";
inputs[2] = string(abi.encode(components)); // I want to pass the array to the JS file
inputs[3] = string(abi.encode(quantities));
bytes memory res = vm.ffi(inputs);
```

Here is the error i'm getting

![nul](https://user-images.githubusercontent.com/43006704/165855951-125a7efb-3e53-4da5-a38a-c0042645256c.png)

**Comment by onbjerg** [comment]
Does your script expect raw bytes encoded as a string, or does it expect bytes encoded as a hexadecimal string? The reason I'm asking is that `string(bytes(..))` just converts the bytes to their corresponding UTF8 characters, it does not result in a string like "0xblablabla".

I think the FFI cheatcode is working, but the input to your script is incorrect, which makes it exit with exit code 1, which is why you revert here.

If you want to convert the bytes to a hexadecimal string, you need to use some conversion function that handles that for you

**Comment by Gaonuk** [comment]
Thanks! I found a conversor to change from bytes to bytes32 and then from bytes32 to hex and that did the work!
