### ISSUE TITLE
`vm.prank` design comment

### ISSUE THREAD

**Issue by 0xdavinchee** [foundry-rs/foundry#1454]
### Component

Forge

### Describe the feature you would like

When I use `vm.prank(msgSender);` and execute an external/public call, the behavior works as expected:

```
vm.prank(msgSender);
somePublicOrExternal.function();
```
However, when I do the same with an internal call/calling a library function I have to use this syntax:
```
vm.startPrank(msgSender);
someLibOrInternal.function();
vm.stopPrank();
```
otherwise, it fails because any calls inside `function` no longer have `msg.sender` set as the pranked `msgSender`.

It would be nice if we could just do:

```
vm.prank(msgSender);
someLibOrInternal.function();
```

**Comment by onbjerg** [comment]
Related to #432. We only mock *calls*, not jumps - internal functions are not calls, they are jumps. Not sure what the best path forward here is

**Comment by hellwolf** [comment]
I understood the technical difference, but I guess it's more of a design issue, that "surprises" are baked in depending on what type of call the next line is which is not obvious just by looking at locally.

**Comment by onbjerg** [comment]
Sure, but what I am trying to convey is that it's not as much of a design decision as it is a technical limitation. In order to support calls to internal functions, we'd have to first figure out where in the bytecode that function is, and then pass that info along to the cheatcode handler. However, the issue with doing this is that functions may be inlined, and they may even in some cases be merged, so it would only work with the optimizer off. On top of this, we'd have to identify contracts on the fly as well (this is done later), leading to slowdowns overall.

For prank it might be simpler since we could "just" prank everything instead of only calls above a certain depth. This would imply that the prank is always in effect though, since we wouldn't know when to stop it, so `prank` and `startPrank` essentially become the same thing. This is also a breaking change, so it's not easy to do without people definitely having to rewrite their tests

**Comment by mds1** [comment]
Not sure if there are plans to support JUMPs, and if we do there's a lot of cheats this would cover (not just prank), so going to close this in favor of a broader solution that I'll mention in #4439
