### ISSUE TITLE
Cacheing bug for forge test

### ISSUE THREAD

**Issue by 0xBeans** [foundry-rs/foundry#1629]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f21a775 2022-04-20T00:07:28.177553+00:00)

### What command(s) is the bug in?

forge test --gas-report -vvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

Occasionally `forge test` won't run my test files. 2 cases:

Case 1) I haven't made any change to my contracts nor test file and I run `forge test --gas-report -vvv`. Occasionally no tests will be run and no gas reports outputted.

Case 2) I have made a change to my contracts but not my test files. Same results as above, no tests run and no gas report produced.

We believe it is a cacheing bug as `forge clean && forge test` will run the whole test suite and output the proper logs. 

Reproduction: Unfortunately this happens at random and I am not able to repro it on a consistent basis. This project is a typical `forge init` project. 

Other ppl have seem to run into similar issues https://twitter.com/0x_Beans/status/1525694826024296448?s=20&t=kDRzz8VahzMrLUxwUh3hqA

Severity: 2/5 - Whenever this happens, I simply run `forge clean` to fix this issue. However, it is somewhat cumbersome and annoying to do this and there is additional burden during tests because I have to think "is this actually running my changes or cached versions?". So I am running `forge clean` a lot more since Im paranoid.

**Comment by mattsse** [comment]
thanks for raising this.

trying to reproduce this on a template project

**Comment by mattsse** [comment]
having a hard time trying to reproduce this -.-

Are you by any chance using different solc versions for parts of your project?

I suspect this happens when we're merging cached and compiled artifacts that for some reason cached artifacts are not actually included, but I wasn't able to reproduce this...

if you notice this again, can you please try running with `RUST_LOG=ethers=trace forge test --gas-report -vvv` again and share the logs?

I also noticed your version is a bit outdated

**Comment by gakonst** [comment]
Agree with consolidating to one issue

**Comment by onbjerg** [comment]
Consolidated into https://github.com/foundry-rs/foundry/issues/1666
