### ISSUE TITLE
Didn't I just provide that argument?

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#1695]
Hello,

I'm BM. A very nice and polite guy.

Trying out some examples with Forge. This example (https://book.getfoundry.sh/tutorials/solmate-nft.html?highlight=create#create-project-and-install-dependencies) looks fun but I cannot get this input to work. What am I doing wrong here? Didn't I just provide that argument?

forge create --rpc-url https://polygon-rpc.com --private-key 0xc96bf26aa396abaf1aaxxx --constructor-args src/NFT.sol:NFT

error: The following required arguments were not provided:
    <CONTRACT>

USAGE:
    forge create --rpc-url <RPC_URL> --private-key <PRIVATE_KEY> --constructor-args <constructor_args>... <CONTRACT>

**Comment by mattsse** [comment]
Have a look at this example:

https://book.getfoundry.sh/tutorials/solmate-nft.html?highlight=create#implement-a-basic-nft

you provided the contract as constructor args instead of the actual constructor args to use when deploying the `NFT` contract
```console
--constructor-args src/NFT.sol:NFT
```

if you're following the example then the correct command would be

```console
forge create NFT --rpc-url=$RPC_URL --private-key=$PRIVATE_KEY --constructor-args <name> <symbol> 
```

where `name` and `symbol` are the arguments the constructor of the `NFT` contract expects
