### ISSUE TITLE
Cast parsing `int` types as `uint`

### ISSUE THREAD

**Issue by arjun-io** [foundry-rs/foundry#1719]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fc534d9 2022-05-23T00:04:42.704454Z)

### What command(s) is the bug in?

cast call

### Operating System

macOS (Apple Silicon)

### Describe the bug

`cast` appears to be parsing `int` types as `uint` types. A minimal example: 

```
pragma solidity ^0.8.0;

contract MyInt {
    constructor() {}

    function getInt() public pure returns(int256) {
        return -1;
    }
}
```

```
❯ cast call 0x50D75C1BC6a1cE35002C9f92D0AF4B3684aa6B74 "getInt()(int256)"
115792089237316195423570985008687907853269984665640564039457584007913129639935
```

**Comment by mds1** [comment]
Going to add on that in general ints seem to be poorly supported in foundry and ethers-rs too. Related:
- https://github.com/foundry-rs/foundry/issues/29#issuecomment-1015480601
- https://github.com/gakonst/ethers-rs/issues/842
- There's also some issues with them in forge, e.g. if you run `RUST_LOG=foundry_evm=trace forge test`, ints get logged with the unsigned value (same as shown here) instead of the two's complement representation

**Comment by distractedm1nd** [comment]
Related to https://github.com/rust-ethereum/ethabi/issues/249
