### ISSUE TITLE
forge remappings doesn't merge the `remappings.txt` setting.

### ISSUE THREAD

**Issue by wiasliaw** [foundry-rs/foundry#1772]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (562d876 2022-05-29T06:04:51.945921Z)

### What command(s) is the bug in?

forge remappings

### Operating System

macOS (Apple Silicon)

### Describe the bug

remappings.txt
```txt
ds-test/=lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
@openzeppelin/=lib/openzeppelin-contracts/
```

run command below.

```sh
$ forge remappings
ds-test/=lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
openzeppelin-contracts/=lib/openzeppelin-contracts/
```

**Comment by mattsse** [comment]
this is intended as `forge remappings` only returns the auto detected remappings, the main usecase is to initialize a remappings.txt like `forge remappings > remappings.txt`


check `forge config` to ensure your remappings.txt is actually picked up.


But since this came up numerous times I wonder if we should change this and simply include _all_ remappings @gakonst ?

**Comment by gakonst** [comment]
I think this is a dupe of some other issue, I had suggested that `forge remappings` respects all overrides, yep, let's do that.
