### ISSUE TITLE
`forge install --package` for supporting npm package.json manifest

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#1847]
### Component

Forge

### Describe the feature you would like

`forge install --package` for supporting installing by *version* via the npm package.json manifest `version` field

much like you can use npm to install a package on github by giving the FQDN URL to the repo, this would do the same but have support for the versioning. Versioning support is naive in that it only reads the package.json manifest file and only update install on a value increase in the field for version.

### Additional context

technically you would have to do a partial clone (fetch --depth 0) to be able to construct the version field so this feature is kind of debatable really.

**Comment by sambacha** [comment]
or maybe generate a lockfile, that way you could also store submodules hash and compare if there are changes to the submodules possibly idk

**Comment by sambacha** [comment]
> What is the use case for this feature? I don't fully understand

decouple dependency management from vcs

**Comment by ufoscout** [comment]
> What is the use case for this feature? I don't fully understand

@onbjerg in my company, we are migrating some of our projects to foundry and, while the overall experience is great, we found the submodules-based dependency management system quite bothersome. For example:
- some repositories have more contracts in dedicated subfolders, each subfolder has its own package.json with nodejs dependencies. We did not find a good way to migrate those repositories because foundry pollutes the root git folder with submodules and we cannot easily separate the dependencies of each project
- sometimes, people manually added dependencies in the foundry.toml file and the git submodules were not updated
- we had issues due to the fact that the code in the git submodules was not exactly in different developer's machines
- we often have to manually update the git submodules to fix "strange" issues

I honestly believe that a dependency management system more similar to the one of `cargo` (using a `target` folder) or `npm` would alleviate lots of pain and feel more natural.

**Comment by onbjerg** [comment]
>some repositories have more contracts in dedicated subfolders, each subfolder has its own package.json with nodejs dependencies. We did not find a good way to migrate those repositories because foundry pollutes the root git folder with submodules and we cannot easily separate the dependencies of each project

You can add submodules anywhere you'd like and have a `foundry.toml` in each subfolder to alleviate this

>sometimes, people manually added dependencies in the foundry.toml file and the git submodules were not updated

If they use `forge install` this should not be the case

>we had issues due to the fact that the code in the git submodules was not exactly the same in different developer's machines

If they use `forge install` this should also not be an issue - it sounds like they are updating the ref when pulling instead of pulling what has been committed in the repository

>I honestly believe that a dependency management system more similar to the one of cargo (using a target folder) or npm would alleviate lots of pain and feel more natural.

I feel like this is an issue that is separate from this one, and would also be a breaking change of course. It's not super high priority for us right now, but I would encourage you to open up an issue with an outline of what you would want to see ideally and we can discuss there :smile:

**Comment by sambacha** [comment]
Just nuke the submodules folder then run forge install. 

Way less complicated.

**Comment by ufoscout** [comment]
> You can add submodules anywhere you'd like and have a `foundry.toml` in each subfolder to alleviate this

Maybe I am doing something wrong, but I don't see how to make it work properly. Here an attempt at adding a foundry project in a new empty subfolder of an existing git repository, please note that there are no changes in the working/staging area contrarily to what was reported by the error:

```bash
ufo@ufo-laptop-2:~/workspaces/foundry_test/lottery/contract
$ forge init
error: `forge init` cannot be run on a non-empty directory.

        run `forge init --force` to initialize regardless.

ufo@ufo-laptop-2:~/workspaces/foundry_test/lottery/contract
$ forge init --force
Initializing /home/ufo/workspaces/foundry_test/lottery/contract...
Installing forge-std in "/home/ufo/workspaces/foundry_test/lottery/contract/lib/forge-std" (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
Error: 
   0: There are changes in your working/staging area. Commit them first or add the `--no-commit` option.

Location:
   cli/src/cmd/forge/install.rs:116

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

```

> > we had issues due to the fact that the code in the git submodules was not exactly the same in different developer's machines
> 
> If they use `forge install` this should also not be an issue - it sounds like they are updating the ref when pulling instead of pulling what has been committed in the repository. If you run `forge install` with no arguments it will install what is committed in the repository instead of updating the submodule

The problem here is that, if the submodule point to the main branch, for example, due to the fact that foundry does not keep track of the exact commit ID, then the commit pushed on the developer machine depends on the moment he executed the "forge install" command and there's no way to guarantee a reproducible build. 
Please note that sometimes we are forced to use the main branch and that git tags, anyway, are also not immutable.


> > I honestly believe that a dependency management system more similar to the one of cargo (using a target folder) or npm would alleviate lots of pain and feel more natural.
> 
> I feel like this is an issue that is separate from this one, and would also be a breaking change of course. It's not super high priority for us right now, but I would encourage you to open up an issue with an outline of what you would want to see ideally and we can discuss there smile

I am not sure, I understood that this issue is proposing to decouple foundry and the vcs, so, it seems to me that this is the correct place. Anyway, I'll do as you propose if you think it's more appropriate.

**Comment by sambacha** [comment]
> > You can add submodules anywhere you'd like and have a `foundry.toml` in each subfolder to alleviate this
> 
> Maybe I am doing something wrong, but I don't see how to make it work properly. Here an attempt at adding a foundry project in a new empty subfolder of an existing git repository, please note that there are no changes in the working/staging area contrarily to what was reported by the error:
> 
> ```shell
> ufo@ufo-laptop-2:~/workspaces/foundry_test/lottery/contract
> $ forge init
> error: `forge init` cannot be run on a non-empty directory.
> 
>         run `forge init --force` to initialize regardless.
> 
> ufo@ufo-laptop-2:~/workspaces/foundry_test/lottery/contract
> $ forge init --force
> Initializing /home/ufo/workspaces/foundry_test/lottery/contract...
> Installing forge-std in "/home/ufo/workspaces/foundry_test/lottery/contract/lib/forge-std" (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
> Error: 
>    0: There are changes in your working/staging area. Commit them first or add the `--no-commit` option.
> 
> Location:
>    cli/src/cmd/forge/install.rs:116
> 
> Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
> Run with RUST_BACKTRACE=full to include source snippets.
> ```
> 
>  > > we had issues due to the fact that the code in the git submodules was not exactly the same in different developer's machines
> > 
> > 
> > If they use `forge install` this should also not be an issue - it sounds like they are updating the ref when pulling instead of pulling what has been committed in the repository. If you run `forge install` with no arguments it will install what is committed in the repository instead of updating the submodule
> 
> The problem here is that, if the submodule point to the main branch, for example, due to the fact that foundry does not keep track of the exact commit ID, then the commit pushed on the developer machine depends on the moment he executed the "forge install" command and there's no way to guarantee a reproducible build. Please note that sometimes we are forced to use the main branch and that git tags, anyway, are also not immutable.
> 
> > > I honestly believe that a dependency management system more similar to the one of cargo (using a target folder) or npm would alleviate lots of pain and feel more natural.
> > 
> > 
> > I feel like this is an issue that is separate from this one, and would also be a breaking change of course. It's not super high priority for us right now, but I would encourage you to open up an issue with an outline of what you would want to see ideally and we can discuss there smile
> 
> I am not sure, I understood that this issue is proposing to decouple foundry and the vcs, so, it seems to me that this is the correct place. Anyway, I'll do as you propose if you think it's more appropriate.

great points. Foundry wont be able to decouple from git, so there has to be an external tool to manage external dependencies.

 Managing dependencies by git is ultimately an insecure by default proposition: git is part of the trusted computing base and was never designed to be cryptographically secure. Most people do not use tags to cut a release.

**Comment by sambacha** [comment]
foundry now supports outputting its config as a json file


maybe supporting remappings as a json file instead of a txt file is more appropriate whenever foundryup gets replaced with a native version, as this format is a legacy of using shell scripts from dapptools

**Comment by onbjerg** [comment]
remappings.txt is used by other solc tooling too, like the VSCode extension

**Comment by sambacha** [comment]
> remappings.txt is used by other solc tooling too, like the VSCode extension

good point, additionally remappings are also limited in that it only works in the context of a local filesystem (the typical use case). 

i couldn't as an example, do 

```ini
libdep=ipfs://${CIDv1}

**Comment by onbjerg** [comment]
Going to close this as out of scope; I don't think supporting Node.js's package.json format makes sense, given we would need to implement an npm resolver just for this use case. If you want to use npm use npm.

As for decoupling from VCS, some exploration is being done in #2386

**Comment by martinvol** [comment]
This would be a huge plus, working with submodules is a real pain
