### ISSUE TITLE
Cheatcode to expect ANY revert

### ISSUE THREAD

**Issue by vdrg** [foundry-rs/foundry#1897]
### Component

Forge

### Describe the feature you would like

Currently, `vm.expectRevert()` expects a revert with no return data. IMO this is unintuitive, to me `expectRevert` should pass with any revert data, and if you want to test empty return data you should do `expectRevert("")`.

There is currently no way to expect a revert without specifying the exact return data. This is inconvenient, as errors are not always part of a contract's specification.

Another alternative would be to introduce a different cheatcode just for this, but feels unnecessary. For future iterations, I believe a more intuitive api could be:

```
    // Expects any revert
    function expectRevert() external;

    // Expect specific return data
    function expectRevertWith(bytes calldata) external;
    function expectRevertWith(bytes4) external;
```

**Comment by onbjerg** [comment]
The issue with `expectRevert("")` denoting reverting with no data is that it is actually expecting an empty string, which has attached data even if there are no characters present (e.g. the length of the string), so that would break that use case.

I'd strongly advise that reverts are tested strictly in order to accurately test smart contract behavior.

As for this feature, I think we would need a new cheatcode.

**Comment by gakonst** [comment]
@vdrg do you mind adding it to the foundry book? https://github.com/foundry-rs/book - didn't realize we forgot to document htat

**Comment by vdrg** [comment]
Sure!
