### ISSUE TITLE
Parametrizable setUp

### ISSUE THREAD

**Issue by Van0k** [foundry-rs/foundry#1924]
### Component

Forge

### Describe the feature you would like

It would be useful to have fuzzing for the `setUp()` function before tests, in order to run tests for various settings of a testing suite.

Currently this can be done, but requires creating a parametrized `setUp<X>()` function and calling it at the beginning of each test where fuzzing is needed. Sometimes one can forget to add this at the beginning of the test, which leads to improper coverage.

E.g.:
Instead of:
```solidity=
   function setUp() public {
   }

   function test(uint8 setupParam) public {
       _setupSuite(setupParam);
      ....
   }
```

It should be like this:
```solidity=
   function setUp(uint8 setupParam) public {
     _setupSuite(setupParam);
   }

   function test() public {   
      ....
   }
```

Doing this would automatically make all tests fuzzed, even if there are no parameters in the test itself.

**Comment by onbjerg** [comment]
Not super simple to implement and also has some open questions:

If `setUp` is parameterized, how do fuzz tests works? Would you run 256 runs of setup, each with 256 fuzz tests, i.e. 65536 fuzz runs total? Seems a little bit excessive, but I'm not sure how this should work otherwise.

**Comment by LilaRest** [comment]
@onbjerg I think `setUp()` would indeed be inefficient when requiring >50 executions and at the same time being combined with fuzz tests.

However, in all other scenarios, `setUp()` fuzz would be terribly useful.

For example, I'm writing tests for a kind of staking contract that can accept any invested ERC20 token at initialization-time, and therefore any `decimals()` possible value.

I want to make sure that this contract works for all decimals in `[0, 18] using `vm.assume(decimals <= 18)`. In this scenario, the `setUp` fuzzing would have allowed me to test this with just one extra line of code.

I think this feature should definitely be implemented but with a message in the documentation to inform users that in some scenarios it can be really inefficient and should therefore be used with caution.

**Comment by onbjerg** [comment]
That still exhibits the exact same issue. We don't use a solver for fuzz tests, we use shrinking, so your security here is directly proportional to the amount of runs you do.

**Comment by LilaRest** [comment]
> That still exhibits the exact same issue. We don't use a solver for fuzz tests, we use shrinking, so your security here is directly proportional to the amount of runs you do.

I'm not sure to properly understand shrinking, but an idea could be to allow pre-defining a set of values to runs `setUp()` with. In my use case this would prevent writing 18 times the same contracts for the 18 decimals scenarios

**Comment by a-t-0** [comment]
Thank you for your evaluating this issue and for asking for clarification. I would like to take the liberty to express my desire for the requested functionality, and motivate it with the following scenario:

I have a contract `someBase` which I initialise with roughly 11 random parameters. In some cases the `someBase` contract can be validly initialised with those parameters and sometimes it cannot. In the cases it is valid, I would like to run a particular test on that contract. 
- I have multiple fuzz test files.
- Each fuzz test file has a few fuzz tests

 Since it is quite verbose to initialise the `someBase` contract with 11 parameters in **each**  test in **each** file, (even if it is just calling the initialisation function with 11 parameters), it would be more convenient to be able to initialise the `someBase` contract once in the `setUp()` function, and have a boolean `valid/invalid` in the setup, to determine if need to run the tests in that file. 
  
Would that be a reasonable motivation for requesting the parameterized `setUp()` function?

Regarding the `how to combine setUp() parameters with test function parameters` aspect, perhaps users can choose between:
- Throw an error if the fuzz test function also has random arguments (that are not in the setUp() args).
- Just create the list of random parameters in that file once per run.
- Per random `setUp()` parameter configuration, have `n` random parameter configurations per test function.

Though I expect option 0 or 1 are easier to implement, and more in line with how fuzzing works right now. Once again, thank you for all your work on contributing to this marvelous framework!
