### ISSUE TITLE
Coverage: Fuzz test support

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1964]
We don't collect coverage for fuzz tests.

By default this should be the case unless you specify `--include-fuzz-tests`. When fuzz tests are run, each iteration will generate a hit map. These hit maps should be merged together and then passed along the coverage pipeline

**Comment by varunsrin** [comment]
i'm not sure if intentional, but coverage for fuzzing tests *briefly* worked a few days ago, and then stopped working today

see: https://github.com/farcasterxyz/contracts/pull/64 (working coverage in ci 3 days ago) 
see: https://github.com/farcasterxyz/contracts/pull/65 (back to no coverage today) 

currently forge version is `forge 0.2.0 (5910e7b 2022-08-25T00:39:34.760251Z)`. unfortunately, don't remember what it was when it worked.

**Comment by onbjerg** [comment]
Yeah the fix that made it work was reverted because it used a lot of memory.
