### ISSUE TITLE
Stack Overflow in forge test

### ISSUE THREAD

**Issue by maurelian** [foundry-rs/foundry#2106]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b2d95d 2022-06-23T00:22:22.617534Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

It seems our test suite has just reach some threshold that causes a stack overflow. 

**Repro steps:**

(I tested these on a fresh clone)

```
git clone https://github.com/ethereum-optimism/optimism
cd optimism/packages/contracts-bedrock
yarn         # to install contract deps
forge test   # this will work fine

git checkout 093244521b1f0f9489cd573ad66c3c317d7ecea4
forge test
```
The output of the final test on will terminate with:

```

thread '<unknown>' has overflowed its stack
fatal runtime error: stack overflow
[1]    62889 abort      forge test
```

The same bug is visible in this CI output: https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/3503/workflows/19bb9e25-731e-4dcf-9fc2-9edfb8b928a7/jobs/45876/parallel-runs/0/steps/0-105

**Comment by mattsse** [comment]
git checkout 093244521b1f0f9489cd573ad66c3c317d7ecea4

gives me 

fatal: reference is not a tree: 093244521b1f0f9489cd573ad66c3c317d7ecea4

fwiw I couldn't reproduce this with `forge 0.2.0 (d89f6af 2022-06-24T00` on this PR https://github.com/ethereum-optimism/optimism/pull/2825

**Comment by maurelian** [comment]
Ahh, sorry about that, I'd overwritten that commit.
Try `git pull https://github.com/maurelian/optimism-1 forge-overflow-repro` then `forge test` in the same dir.

As you'll notice, something about how I refactored the tests seems to have resolved it. I think I might have reduced the depth of inheritance in the refactoring, honestly it's not 100% clear to me. 

Another observation, is that smaller subsets of the tests work fine. Before refactoring the tests, we had planned to workaround it by looping over the test files as you can see here: https://github.com/ethereum-optimism/optimism/commit/bb8cdf2f3ecce1456c01e668f36b1429e02934d1#diff-8867d60c5856f3dd26f4c8e44f748fc94cb23bedf280def40159d6977153456b

**Comment by mattsse** [comment]
@onbjerg couldn't figure this one out,

apparently this is caused by the second prank in the setup function, which then triggers a loop where the proxy either calls itself or the proxy which triggers a fallback.

couldn't fully make sense of how the pranks are (re)set tbh

**Comment by mattsse** [comment]
@maurelian could you perhaps describe how the proxy setup is supposed to work?
from what I've gathered, 

* the `L2OutputOracle` is created 
* create a proxy and set the oracle as implementation
* set the oracle to `L2OutputOracle(proxy)`
* create another proxy and set its implementation to `L2OutputOracle(proxy)`

so now we have
proxy -> proxy -> oracle 
right?

I believe due to the second prank we end up in a loop that's either
proxy <-> proxy

or 
proxy that calls itself, perhaps due to `proxyCallIfNotAdmin`

**Comment by onbjerg** [comment]
I don't entirely follow either, would be nice with an overview of how this is supposed to work

**Comment by onbjerg** [comment]
I don't think this is a bug on our end, forgive me if I misunderstand:

In `L2OutputOracle_Initializer::setUp` you create a proxy that delegates to `L2OutputOracle` (the address of which is stored in `oracleImpl`. Let's call this Proxy 1. The address of this proxy is then stored in `oracle`.

In `L2OutputOracleUpgradeable_Test::setUp` you set `oracleImpl = oracle` and then you call some init function on a new Proxy (let's call it Proxy 2). Proxy 2 delegates to Proxy 1.

So by my understanding, the call to Proxy 2 will delegatecall into the code of Proxy 1. Proxy 1's code will just execute the fallback function which looks up it's implementation using the storage of Proxy 2. The implementation noted in the storage of Proxy 2 is Proxy 1, so this delegatecall will delegatecall into Proxy 1. The same happens, and it loops.

So I don't think this is because of prank or Forge, I think it's because of https://github.com/maurelian/optimism-1/blob/093244521b1f0f9489cd573ad66c3c317d7ecea4/packages/contracts-bedrock/contracts/test/L2OutputOracle.t.sol#L347?

I hope that made some sense.

**Comment by maurelian** [comment]
@mattsse  you're right it looks like an infinite recursion where proxy1 delegatecalls proxy2 over and over. 

So yeah, my bug there, and it explains why the refactor fixed it. But shouldn't it lead to an OOG, or is there no gas limit in the tests?

**Comment by onbjerg** [comment]
The gas limit is super high, AFAIK it's like 2^32 by default or something, so we simply just hit stack overflow before we run out of gas

**Comment by mattsse** [comment]
let's add a recursion check + warning

**Comment by maurelian** [comment]
Hmmm, OK. 
Is it possible to catch the overflow and give a warning about a possible infinite loop in the contract's control flow?
Otherwise there's probably not much to be done here.

**Comment by gakonst** [comment]
> let's add a recursion check + warning

where would we add this? this seems like it'd require static analysis

**Comment by mattsse** [comment]
if there's a loop then we'll end up in a loop where `Backend::call` is called until the stack overflows, this happens at around ~120 depth in this case.

I think we could check this with an inspector that keeps track of entered calls, exited calls etc. but perhaps not worth it

**Comment by gakonst** [comment]
Yeah - feels lower prio. Let's keep open for visibility anyway

**Comment by DaniPopes** [comment]
Since this issue was opened, recursion was removed from the EVM implementation (revm), and gas limit is configurable with `--gas-limit`.
