### ISSUE TITLE
I strongly recommend that you add two examples to the CLI-Readme: How to make an ERC-20 and how to make and ERC-721 as easily as possible using Forge tools.

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#2145]
Hello,

I'm MB. A very nice and polite guy.

I strongly recommend that you add two examples to the CLI-Readme: How to make an ERC-20 and how to make an ERC-721 as easily as possible using Forge tools.

Why? Well the reason that Solana is gaining so much ground is because when you install Solana you can make an ERC-20 or ERC-721 equivalent directly from their command line interface. You can't really do that with Geth, so we have to rely on third party tools like Foundry.

Which is fine. But you guys are still thinking too low level. You are low level programmers. Please provide some love for the tens of millions of webdevs out there.

You have to provide these two examples so that everybody can start making millions of ERC-20's and ERC-721's on the Ethereum chains as soon as possible. 

Please think a bit about the high level programmers as well. Making an ERC-20/ERC-721 should preferably be even easier than making a HTML web page. Just add two one-liners into the example that WORKS right out of the box on every device so we can make things happen.

I requested this before and the guy who replied said "well Solana is complicated as well because you have to code in Rust". But what I'm referring to specifically is the very easy tools that Solana has for those very common use cases (ERC-20/721) that everyone kind of need to have access to. Those two tools will be the foundation of the finance of the future. Please enable those tools for the  Ethereum community.

**Comment by bitcoinmeetups** [comment]
(The examples in the book are a bit convoluted and they don't necessarily work. The 2 examples on the front page should be as concise as possible, preferably one-liners and they may need a little bit of maintenance once in a blue while to ensure that the compiler version is still up to date and so on).

The gochain/web3 repository on github offers something similar, easy tools for ERC-20/ERC-721 generation but they are not really functioning all the time and maybe not up to date. Foundry might become the goto tool for deployment so you are probably best suited for providing these two working examples that everyone needs and wants.

**Comment by onbjerg** [comment]
I think you've created this issue in some form before - there are many visual editors online that can create a valid ERC20 or ERC721 and deploy it for you if you just want to create one of those without needing to code. I also think I referred you to this one: https://wizard.openzeppelin.com/

Foundry is a general purpose development tool for smart contracts - the goal is not really to have ready-made templates to quickly deploy templated contracts like standard tokens or the like.

The book is primarily written to help developers learn how to use Foundry, not how to code Solidity: for this I'd refer you to other articles on the subject. We've talked about creating a "learn Solidity using Foundry" book at some point but it's not high priority right now

I'm going to go ahead and close this issue since it's out of scope for Foundry, but if you feel like something is lacking from the book in terms of how to use Foundry, please open up an issue in https://github.com/foundry/book :slightly_smiling_face: And again I'd reiterate that if you just want to deploy an ERC20 or ERC721 without needing to code, you can use one of the many visual editors that are available like OZ Wizard
