### ISSUE TITLE
Allow setting broadcasted tx's gas limit in `forge script`

### ISSUE THREAD

**Issue by pyk** [foundry-rs/foundry#2224]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f016135 2022-07-04T00:05:06.364672Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Not sure if this expected behaviour or not, but I can't set the gas limit of transaction that broadcasted via `forge script`. Somehow it ignores the `--gas-limit` and `--block-gas-limit`

**Comment by onbjerg** [comment]
Those are for Forge's execution environment (they're listed under "Executor Environment Config"), not for the broadcasted transactions. I don't think we currently support setting the gas limit for broadcast transactions (cc @joshieDo) and I'm also not sure how that would work with multiple transactions :thinking:

**Comment by gakonst** [comment]
@mds1 cc we've discussed before

**Comment by mds1** [comment]
Yep, in https://github.com/foundry-rs/foundry/issues/2002

As described in that issue, my suggestion would be to add `vm.broadcast` overloads that allow you to specify margin on the gas estimate. So if I'm estimating gas for a uniswap v2 trade where cost varies by block position, I can do `vm.broadcast(20)` or `vm.broadcast(myDeployer, 20)` to mean "add 20% margin to transaction's gas estimate". IMO this is better UX than specifying specific, hardcoded gas limits which will need to vary per-transaction anyway

**Comment by ckoopmann** [comment]
I think the most natural syntax would be to let users specify gas limits the same way they normally do in solidity:
`someContract.someFunction{gas: 100000}()` 

In fact I expected this to work already but was a bit surprised when these values were just ignored inside my forge solidity script.

**Comment by mattsse** [comment]
good point, @joshieDo I think that's doable, right?

**Comment by mds1** [comment]
> Wouldn't it be most intuitive to let users specify gas limits for individual contract calls in their script the same way they normally do in solidity ?:
> `someContract.someFunction{gas: 100000}()`
> 
> I had expected this to work already in one of my scripts but was a bit surprised when these values were just ignored.

Ah, that's a good idea.

> Imo this would also be more flexible and cover more use cases than only allowing the user to specify a percentage increase relative to the existing estimation.

However, I'm not convinced it's actually the optimal UX, because it feels clunkier and harder to use. Personally, when I'm writing a script, I don't want to spend time figuring out "this tx should cost X gas, let me hardcode a 1.2X gas limit to ensure it has enough gas". Especially if I want to execute that script on, for example, mainnet and Arbitrum, because Arbitrum uses different gas metering so I now need to have a conditional gas limit based on `block.chainid`. I'd be curious to hear more about why you think this is more flexible and covers more use cases that specifying a relative increase.

Supporting both might be a good idea. Then if a user supplies both (instead of just one of the two options) we default to the hardcoded value and skip gas estimation, ignore the percentage tolerance, and print a warning that the percentage is being ignored.

**Comment by gakonst** [comment]
> Supporting both might be a good idea. Then if a user supplies both (instead of just one of the two options) we default to the hardcoded value and skip gas estimation, ignore the percentage tolerance, and print a warning that the percentage is being ignored.

:+1: supportive

**Comment by onbjerg** [comment]
This seems to be solved in #2524? :smile:

**Comment by mds1** [comment]
Ehh yes and no 😅

#2524 does add a way to change the gas limit, but in a different way than the approach that it seems was agreed on above: The PR only lets you globally scale _every_ tx's gas limit by a the same factor, instead of providing granularity in the script + supporting standard solidity syntax for specifying gas limit.

Personally I prefer the more granular approach because IME most tx's don't need this functionality,

**Comment by onbjerg** [comment]
Hmm, I'd track the `{gas: x}` syntax in another issue to be honest, since it is more complex than you might think; we are going to get it from the traces, but the fact is that it will always be there, no matter if you specify it or not :/ Might require a bit more thinking

**Comment by mds1** [comment]
> Hmm, I'd track the {gas: x} syntax in another issue to be honest, since it is more complex than you might think; we are going to get it from the traces, but the fact is that it will always be there, no matter if you specify it or not :/ Might require a bit more thinking

Good point, that does seem tricky. I personally would not often/ever use that syntax, so @ckoopmann I'll defer to you to create the issue if it's a feature you still want / would use.

Regarding the alternative broadcast syntax, it's may be worth a discussion to get some opinions from others. I'd be ok keeping it simple with just this global flag for now, I don't think it does much harm

**Comment by ckoopmann** [comment]
> {gas: x}



> > Hmm, I'd track the {gas: x} syntax in another issue to be honest, since it is more complex than you might think; we are going to get it from the traces, but the fact is that it will always be there, no matter if you specify it or not :/ Might require a bit more thinking
> 
> Good point, that does seem tricky. I personally would not often/ever use that syntax, so @ckoopmann I'll defer to you to create the issue if it's a feature you still want / would use.
> 
> Regarding the alternative broadcast syntax, it's may be worth a discussion to get some opinions from others. I'd be ok keeping it simple with just this global flag for now, I don't think it does much harm

I'd definetely like / use this feature, so I created issue: https://github.com/foundry-rs/foundry/issues/2627

I looked into implementing it  but I think it is beyond my current skill-level / depth of understanding, as a new contributor and rust-newbie.
