### ISSUE TITLE
[anvil] on avalanche `eth_sendTransaction` returns an error `max fee per gas less than block base fee` even after setting `_setNextBlockBaseFeePerGas` to zero

### ISSUE THREAD

**Issue by krasi-georgiev** [foundry-rs/foundry#2255]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ce52d85 2022-07-09T00:11:06.359354505Z)

### Operating System

Linux

### Describe the bug

getting the error in the title only on avalanche, mainnet works fine, the same works fine with hardhat on avalanche

reproduce
1. call `_setNextBlockBaseFeePerGas` with param 0x0
2. call `_impersonateAccount` 
3. call `eth_sendTransaction` with 0 for the gas price

**Comment by banteg** [comment]
i have a similar error on mainnet when trying to replay a tx in top of a block preceding this one

```python
num_transactions=376 hash=HexBytes('0x108f107df70d4451ec6d6ffcdfb8ca0bdbe1eeb6649944c20bebb3dc1d39978a') number=13184860
parent_hash=HexBytes('0x85718e84a9af37802f20872253e2afa76c80a1e95a76415bc3e5dbed6ed6223a') size=160854 timestamp=1631100932
gas_limit=30000000 gas_used=29996605 base_fee=62283069776 difficulty=8763037476778188 total_difficulty=30269847514949595662036
```

previous block looks like this
```python
num_transactions=240 hash=HexBytes('0x85718e84a9af37802f20872253e2afa76c80a1e95a76415bc3e5dbed6ed6223a') number=13184859
parent_hash=HexBytes('0x22c3691d1d9b7738ff8bdf1ae45279faa95e45b6323a638fc31da9f3e230b7a3') size=44693 timestamp=1631100923
gas_limit=29999972 gas_used=12257311 base_fee=63739886069 difficulty=8763033181810892 total_difficulty=30269838751912118883848
```

tx is like this
```python
DynamicFeeTransaction:
  chainId: 1
  to: 0x0000000000d41C96294CCdaC8612Bdfe29C641aF
  from: 0x83b4F74296738d8C2e15bD7c1f4a19Df122354f5
  gas: 107846
  nonce: 17971
  value: 0
  data: 0x000000...ca0eb6
  type: 0x02
  maxFeePerGas: 62283069776
  maxPriorityFeePerGas: 0
  accessList: [{'address': '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 'storageKeys': []}, {'address':
'0x584bc13c7d411c00c01a62e8019472de68768430', 'storageKeys': []}, {'address': '0x6463bd6026a2e7bfab5851b62969a92f7cca0eb6',
'storageKeys': ['0x0000000000000000000000000000000000000000000000000000000000000006',
'0x0000000000000000000000000000000000000000000000000000000000000007',
'0x0000000000000000000000000000000000000000000000000000000000000008',
'0x000000000000000000000000000000000000000000000000000000000000000c']}]
```

`anvil_setNextBlockBaseFeePerGas` seems to have no effect

**Comment by vicente-noriega** [comment]
YOU GUYS BETTER STOP CODING WITH VINCENT FERNANDO NORIEGA YOU GUYS ARE ALL
BREAKING THE LAW ALLOWING HIM TO ABUSE AND TRY TO TAKE ADVANTAGE OF AND
CAUSE MY DEPRESSION TO GET WORSE AND I FEEL LIKE IM DYING BECAUSE OF IT
BECAUSE HE KEEPS LYING TO ME AND KEEPING SECRETS FROM HE TAKES MONEY FROM
AND MAKES NASTY VIDEOS AND DISRESPECTS ME I WAS NEVER A FIGHTER UNTIL HE
CAME ALONG AND MANUIPULATED ME I THOUGHT HE ONLY LOVED ME BUT HE IS
CHEATING ON ME AND KEEPING SECRETS AND ABUSING ME HE LEFT A BRUISE ON MY
FOOT I FEEL LIKE HE IS GOING TO MURDER ME ONE DAY AND YOU GUYS ALL KNOW
ABOUT IT AND YOU GUYS ARE DOING ME WRONG HOW DARE YOU GUYS TELL VINCENT I
TEXTED MY SISTER YOU HAVE NO RIGHT TO HURT ME LIKE THIS WHY ALL OF A SUDDEN
DID VINCENT FERNANDO NORIEGA HAVE TO GO TO THE STORE BECAUSE HE DIDNT GO TO
THE STORE HE LEFT LATE TO THE GYM TO CHEAT ON ME WITH THAT BITCH HANNAH
AGAIN WHO HAS A HUSBAND WHO IS A CROOKED COP YOU ARE ALL GOING TO PAY FOR
HOW YOUR TREATING ME JUST BECAUSE MY PARENTS ARE NO LONGER ALIVE I HATE YOU
GUYS I HATE YOU ALL FOR KEEPING SECRETS AND LIES TRYING TO CAUSE ME TO HAVE
ANOTHER PSYCHOTIC BREAKDOWN
