### ISSUE TITLE
Extract setUp transaction from forge

### ISSUE THREAD

**Issue by ehildenb** [foundry-rs/foundry#2298]
### Component

Forge

### Describe the feature you would like

My understanding is that `forge test` is taking the `setUp` function of a given test-suite, and somehow building a transaction which is then submitted to a local private network or a remote network. Maybe my understanding is not correct :sweat:

But if it is correct, ti would be very helpful to be able to extract that transaction which is created, as a way to setup the pre-state for other testing tools. In our case, we want to run that setUp transaction to get the initial KEVM state to use for verifying the foundry property tests, so we have to run that transaction through KEVM's client instead of Foundry's.

We likely _only_ need the `data` field of the `setUp` transaction, not the whole transaction. But I suppose whichever is easy for forge to export.

### Additional context

https://github.com/runtimeverification/evm-semantics/issues/1278

**Comment by ehildenb** [comment]
It appears that `forge create` may also be helpful here?

**Comment by onbjerg** [comment]
The setup phase for tests is very simple:

1. We deploy the test contract (and any libraries, if it needs any)
2. We send a transaction to the test contract that calls `setUp` - this can *not* have any parameters, so the data is always exactly the same: `0x0a9254e4`.

These are all submitted directly to an EVM we have full control over, so it is not submitted to a private network or anything like that. It is always sent to an in-process VM, regardless of whether or not you are forking.

Let me know if that was sufficient - if not, I'd like to continue this in the Discussions tab instead since it's not really a feature or bug (I think?) :smile:
