### ISSUE TITLE
anvil: add a `--script` option

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#2324]
### Component

Forge

### Describe the feature you would like

Add a `--script path/to/script.sol` option to anvil to run a script at startup.

### Additional context

For running tests locally it is helpful to spawn anvil, then run `forge script ...` against it to do some setup. This is a little cumbersome and also prevents using cheatcodes since those are not broadcasted.

**Comment by onbjerg** [comment]
Unsure about this one, as I see it we would clutter Anvil by depending on more Forge stuff to save 1 command. I'm not entirely following the cheatcode usage point - scripts are not supposed to broadcast cheatcodes under any circumstance, and having a situation where that would be the case is a bit weird? At least, from my perspective, it would make it harder to reason about scripts since you would essentially have two separate environments with their own behaviors

**Comment by adhusson** [comment]
Using cheatcodes to setup a testing environment can be useful -- in my case, setting the code of a magic address to provide the addresses of other contracts.

It is definitely possible to wrap "start anvil, wait until server ready, run deploy script" in a script, but it's a little cumbersome.

**Comment by onbjerg** [comment]
I'm not entirely sure I follow still - is this for use with Hardhat? A lot of the cheatcodes are exposed in Anvil like they are in Hardhat

**Comment by adhusson** [comment]
Thanks I had missed the `anvil_setCode` method! Still (something I just found myself wishing for) it would allow using `console.log`. The context is testing a js lib against a local deployment.

**Comment by onbjerg** [comment]
Closing this as out of scope

**Comment by adhusson** [comment]
While everything went fine thanks to `anvil_setCode`, it would still have been much easier to do everything in solidity and run `anvil --script file.sol` rather than go through the `spawn`-based node process I now have (which everyone wishing to test deploys locally and automatically will have to do in one form or another).
