### ISSUE TITLE
Add ssh based modules installation

### ISSUE THREAD

**Issue by kyzia551** [foundry-rs/foundry#2407]
### Component

Forge

### Describe the feature you would like

Would be very cool to be able to call 
```sh
forge install git@github.com:foundry-rs/foundry.git
```
and to have in .gitmodules SSH integration, not HTTPS. Currently [HTTPS forced](https://github.com/foundry-rs/foundry/blob/65a37e4f6d1b529a403ba8c2a3d68474aefec897/cli/src/opts/forge.rs#L258).

It helps when working with private modules. You don't need to pass an access token or login/password every time.

**Comment by onbjerg** [comment]
Primary issue with not forcing HTTPS is that we instead force everyone who touches a project with SSH submodules to create an SSH key in order to pull, whereas with HTTPS you can at least cache the username/password.

We ended up deciding to force HTTPS because of this, see https://github.com/foundry-rs/foundry/issues/924 for context.

Closing this issue because of that, but if you feel very strongly about it I'd recommend opening up a discussion on GitHub and we can discuss if we should flip the decision or not. I still feel very strongly that SSH is less used by most developers right now, though, and that it would likely end up being an increased support burden for new users.

It might be a non-issue later on if we end up implementing something like #2386 though
