### ISSUE TITLE
Gas cost discrepancies when testing calls through a proxy

### ISSUE THREAD

**Issue by elenadimitrova** [foundry-rs/foundry#2503]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (33dbaa5 2022-07-23T00:04:10.615195Z)

### What command(s) is the bug in?

forge test --gas-report

### Operating System

macOS (Apple Silicon)

### Describe the bug

When comparing the gas cost test results between `hardhat-gas-reporter` and `foundry` they significantly differ for the following sample test cases:
a) ContractA.mint() calling external contract ContractB.mint() where ContractB is the implementation of a Minimal Proxy 

foundry reports 68,530 gas
hardhat reports 105,796 gas

b) ContractB.mint() getting called on top of an implementation Proxy (where ContractB is the implementation set on Proxy)

foundry reports 68,992 gas
hardhat reports 93,040 gas

I would normally expect test case a) to be more expensive than test case b) as it is doing a cross contract call (even if in test case B the proxy does an extra read from storage to get implementation address). 

Additionally (as this maybe related symptom), when measuring gas costs for calls routed through a proxy referencing an implementation contract, there are two sets of gas costs `foundry` reports, one for the Proxy itself and another for the implementation contract as seen in screenshot below

<img width="1223" alt="Screenshot 2022-07-27 at 20 47 32" src="https://user-images.githubusercontent.com/703848/181529050-1f36fa29-1cd7-4a48-874a-df4754895efc.png">

However when a different proxy is used that does no local storage reads (e.g. a minimal proxy or the same as above but with immutable implementation instantiated in the proxy constructor) the Proxy gas cost table is no longer displayed and only implementation costs show.

**Comment by onbjerg** [comment]
Are the first gas numbers from `forge test` or from `forge test --gas-report`? Also, it is expected that there are two sets of reports (one for proxy, one for implementation) as we do not give special treatment to proxies (and probably won't). I would expect the gas to differ somewhat since Forge still obeys cold/warm account and storage slots, so given everything is in the context of one call, you may end up in situations where the gas cost is lower because the slot or account is already warm when called

**Comment by elenadimitrova** [comment]
First gas numbers are from `forge test --gas-report`

I still don't understand the separate reports you have for the proxy and the implementation, what are you saying is the difference for example for the call to `mint` function which is only ever called once in the test but is reported under both the Proxy and the implementation?

As for the cold/warm storage costs, that cannot explain the gas cost difference as I am executing the exact same single unit test on `foundry` and `hardhat` and executing both on a clean slate of contracts as you would expect in a unit test.

There is 37,266 gas difference in the first call and 24,048 gas difference in the second call so still a lot unaccounted for.

**Comment by elenadimitrova** [comment]
I've reproduced the issue in an MVP in https://github.com/elenadimitrova/foundry-hardhat-gas-compare where you can run the two identical set of tests and see the difference between `foundry`

<img width="1004" alt="Screenshot 2022-07-29 at 14 31 31" src="https://user-images.githubusercontent.com/703848/181751172-c815d926-1378-455d-a153-4d56c14d803e.png">

vs `hardhat`
<img width="1280" alt="Screenshot 2022-07-29 at 14 30 31" src="https://user-images.githubusercontent.com/703848/181751184-76241456-240d-4c06-86f2-885734735c09.png">

**Comment by onbjerg** [comment]
1. The difference for `MinimalProxyFactory` is accounted for as explained above; Foundry's output does not include the 21000 gas stipend. There is a small difference of about 400 gas outside of that which is probably explained by the fact that the account is hot as you are not deploying the factory in `setUp`
2. I would *assume* it is a similar story for the mint call on `MintModule` - both the implementation and the `MintModule` contract are hot
3. The `RouterProxy` contract shows up because we analyze gas usage based on EVM traces, not individual start-to-end transactions like Hardhat does. It's not really possible for us to do it like Hardhat does, since each test is executed within the context of a single transaction

I don't really have a lot of time currently to go in and individually dissect each opcode to find out if there is some larger thing unaccounted for, but the EVM implementation we use conforms to the Ethereum tests that all nodes use.

We've also investigated the smaller gas discrepancies more closely before, where we did account for the discrepancy: https://github.com/mds1/convex-shutdown-simulation (see the note about Foundry)

I'd love to hear some input from anyone who has suggestions on how we can improve the reports, but it does not seem like a trivial problem to solve due to how Forge executes tests vs other frameworks

**Comment by elenadimitrova** [comment]
@onbjerg I have confirmed the storage slots aren't "hot" as you explain, with [this commit](https://github.com/elenadimitrova/foundry-hardhat-gas-compare/commit/fc83e3b0fd953c21411ceca6de95febf3acbdda9) which is testing storage slots are "cold" before writing.

There is effectively around 5200-5500 unexplained gas difference in the `mint` functions in both types of proxies used. I think this is non negligible considering I am testing a minimal repro scenario, with potentially this gas difference being more significant in more complex cases.

|                         | foundry                | hardhat | diff  |
|-------------------------|------------------------|---------|-------|
| MintImplementation.mint | 22425 + 210000 = 43425 | 48660   | -5235 |
| MintModule.mint         | 23236 + 21000 = 44236  | 49808   | -5572 |

This is quite critical considering the importance of gas cost analysis in smart contracts for decision making, i.e. we are currently trying to weigh in the costs of the two different proxy patters and finding it difficult to trust what foundry reports.

**Comment by zerosnacks** [comment]
This has likely been resolved by the new isolation mode enabled by default when using `--gas-report`: https://github.com/foundry-rs/foundry/pull/7186

Tentatively closing as resolved, feel free to re-open if this is still an issue.
