### ISSUE TITLE
Failing forge-std fuzz I256 tests

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2560]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

latest test of forge-std showed failing fuzz test 

https://github.com/foundry-rs/forge-std/runs/7637381093?check_suite_focus=true

of `testAssertApproxEqRel_IntErr_Fail`

https://github.com/foundry-rs/forge-std/blob/c19dfd2f2a88a461216b0dd1f4961e1a85dcad46/src/test/StdAssertions.t.sol#L435-L443

this first happens with this PR https://github.com/foundry-rs/foundry/pull/2499 which changed fuzzing behaviour of ~~I256~~ could only reproduce this for `int128`

there's something weird going on because if you change 

the test function to just `vm.assume(false)` this condition is not always true

https://github.com/foundry-rs/foundry/blob/91f02fc8e79de2a67522935818444ae9bbd59c50/evm/src/fuzz/mod.rs#L88-L91

but it should

https://github.com/foundry-rs/foundry/blob/91f02fc8e79de2a67522935818444ae9bbd59c50/evm/src/executor/inspector/cheatcodes/fuzz.rs#L9-L13

maybe there's something weird with the `calldata/output data` @alexeuler ?

here's a minimal example

```solidity
    function test_IntErr_Fail(int128 a) external {
        vm.assume(false);
    }
```

that reverts with

```
[FAIL. Reason: EvmError: Revert. Counterexample: calldata=0x0b6249c80000000000000000000000000000000080000000000000000000000000000000, args=[170141183460469231731687303715884105728]] test_IntErr_Fail(int128) (runs: 0, μ: 0, ~: 0)
````

where as 

```solidity
    function test_IntErr_Fail(int256 a) external {
        vm.assume(false);
    }
```

fails with

```
[FAIL. Reason: Too many global rejects] test_IntErr_Fail(int256) (runs: 0, μ: 0, ~: 0)
```

**Comment by gakonst** [comment]
@alexeuler any thoughts?

**Comment by moose-code** [comment]
Issue here is same that I mentioned in #2570 I believe. 

The `args=[170141183460469231731687303715884105728]]` provided in the counter example here is +1 greater than the max of the int128 type.

**Comment by onbjerg** [comment]
Logged the selected integer for the strategy, it seems to generate numbers with too many bits in some cases:

```
[evm/src/fuzz/strategies/param.rs:25] x = 170141183460469231731687303715884105728
[evm/src/fuzz/strategies/param.rs:25] x.bits() = 129
```

**Comment by onbjerg** [comment]
After more investigating it seems that it is not the complicate/simplify step, the random tree generator simply generates invalid trees. I'm not sure if this is related to endianess or something (`I256` is LE, Eth is BE) and it's lost in translation? The signum resides in the last bit of the 4th word in the I256. I've tried swapping hi/low in the random tree generator but it didn't work, presumably because ethers does some swapping around or something when encoding. Unsure.

Something that did sort of work, though, is changing the range of `bits` from `0..=self.bits` to `0..self.bits`, but it would not generate negative numbers. Something interesting though: it seems that for `intN` with `N < 128` negative numbers from random trees are never generated currently.

**Comment by gakonst** [comment]
wonder if it's this part of the logic? https://github.com/foundry-rs/foundry/blob/master/evm/src/fuzz/strategies/param.rs#L79-L86

**Comment by onbjerg** [comment]
The integers are already too big once you hit the first link, it just seems that the random tree generation is unsound somehow.

I'm not entirely sure why, but the start of the tree is way bigger than it should be, and somehow that is safe until x amount of runs in when the tree has been complicated enough - at this point `hi` is just above the maximum value allowed for i128, and `curr` ends up being the max value + 1.

It's a bit odd because I would assume we could take the random strategy from u256 that we already have and just cast it to an integer - and that's what we do, it just doesn't work :D Even weirder is that the edge tree works perfectly and it casts a u256 in the same-ish manner

**Comment by alexeuler** [comment]
Hey guys, sorry I think I missed smth in the PR. The fix is ready. @onbjerg @gakonst @mattsse

**Comment by gakonst** [comment]
thanks king
