### ISSUE TITLE
Failed expectRevert does not fail the test

### ISSUE THREAD

**Issue by nazariyv** [foundry-rs/foundry#2575]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (01325bc 2022-08-03T00:04:34.894101923Z)

### What command(s) is the bug in?

forge test -vvvvv

### Operating System

Linux

### Describe the bug

You can clone the repository on [this commit](https://github.com/rumble-kong-league/tiny-rkl-erc721/commit/7d8257f8c9b72a6d0f24c861708806d8d537f5e5#diff-bc91395dccf9efc1ddf7609abd94429457ce563249ba3f48931722270c974a87R30). I am trying to mint (51 tokens) more than max supply (50 tokens) here and expect to get a revert. This test code is not correct (the expect revert should be immediately before the mint). However, it serves the purpose of showing that when something is expected to revert, and it does not, then it should be flagged as a failing test. In this case, it passes the test.

<img width="866" alt="does-not-fail" src="https://user-images.githubusercontent.com/13678461/182589103-60d9a29d-cf6f-494f-8b5e-7cb01a209965.PNG">

**Comment by onbjerg** [comment]
Uhh, that's a new one. Will prioritize it, it has to be a recent regression

**Comment by onbjerg** [comment]
Ahhh, whew. I really thought this was a bug for a second: the reason your test doesn't fail is because `testFail` *inverts* the result of the test. So, `vm.expectRevert` failing *actually makes the test pass*. I do not recommend using `testFail`: in general it's somewhat of an anti-pattern left over from DappTools. In some cases it is ok to use but generally you should prefer explicit assertions instead, e.g. instead of `testFail` and `assert(a == b)` to test that `a != b`, just write `assert(a != b)` :)

**Comment by onbjerg** [comment]
Yes! It's a little bit counterintuitive if you didn't know. What people usually do is name their tests like `test_Fail` or `testDoesNot` or something along those lines :)
