### ISSUE TITLE
jsonrpc node over the evm instance used

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#26]
given an implementer of the `EVM` trait mentioned in #23 and a database type (probably in-memory map), we should be able to run an RPC node that "acts" like a blockchain. 

the logic under `service` could act as inspiration https://github.com/brockelmore/rust-cevm/blob/35cdefb760d41197ccfadc8c446343f20eba9080/service/src/EVM/mod.rs, but if possible we should try doing this with the tokio/hyper stack for performance reasons and the ability to inject extra middleware etc., e.g. https://github.com/tokio-rs/axum#usage-example with a jsonrpc module like how https://github.com/AtsukiTak/warp-json-rpc would work with https://github.com/seanmonstar/warp

ref: #174

**Comment by jparklev** [comment]
Non-standard RPC method wishlist:

* `evm_snapshot` – useful for externally-managed testing environments (JS SDK tests are maybe the most common example)
* `trace_replayTransaction` – fork mainnet and get state diffs for actions you otherwise wouldn't be able to perform (eg run a governance proposal for a protocol that's behind a governance delay and observe the variable changes)
