### ISSUE TITLE
`selectFork()` does not update all state

### ISSUE THREAD

**Issue by david-k** [foundry-rs/foundry#2629]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b3af602 2022-08-05T11:04:59.840369372Z)

### Operating System

Linux

### Describe the bug

Calling `selectFork()` correctly updates the block state `block.*`, but other state remains stale:
```solidity
function testSelectFork() public {
	address coinbase = 0x0193d941b50d91BE6567c7eE1C0Fe7AF498b4137;

	uint f1 = vm.createSelectFork(RPC_ENDPOINT, 9);
	vm.selectFork(f1);

	assertEq(block.number, 9);
	assertEq(coinbase.balance, 11250000000000000000);

	uint f2 = vm.createFork(RPC_ENDPOINT, 10);
	vm.selectFork(f2);

	// Works
	assertEq(block.number, 10); 
	// Fails, because coinbase.balance is apparently not updated when switching forks
	assertEq(coinbase.balance, 16250000000000000000);
}
``` 
In this example, the address `coinbase` should earn 5 ETH in block 10, but the last assertion fails because the balance remains unchanged compared to block 9.

(Note that this behavior remains even after https://github.com/foundry-rs/foundry/pull/2625)

**Comment by mattsse** [comment]
thanks for this, was able to discover the bug.

juggling different evm states at a time is a bit complex.

The way this works with https://github.com/bluealloy/revm is, that there's a `Subroutine` that holds the "hot" accounts loaded from the underlying `Database` that feeds the Account/State data to the subroutine so it can apply changes to the state while the evm executes.
In a way the `Subroutine` is something like a cache that
1. check if account is already loaded (hot)
2. if not load from the `Datbase` (this will then retrieve the account via RPC in forking mode)

when we created a fork, we only replaced the  `Database` object, so if the account was loaded (`1.`) previously, then wouldn't reach `2.` and the state is not updated on this new fork.

the fix is to adjust the `SubRoutine` when creating a fork.
