### ISSUE TITLE
USDT transactions reverts with [FAIL. Reason: EvmError: Revert] 

### ISSUE THREAD

**Issue by joshualyguessennd** [foundry-rs/foundry#2655]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (92f8951 2022-08-08T00:04:27.676816Z)

### What command(s) is the bug in?

forge test -vvv -f $mainnet-url

### Describe the bug

Working on some contracts, I have noticed I'm unable to do basics operations like `approve`, `transfer` and `transferFrom` with usdt on the test contract, I received error `[FAIL. Reason: EvmError: Revert]`

example code to test:
`    
function deposit(uint256 amount) external {
        require(amount > 0, "!amount");
        if (IERC20(usdt).balanceOf(msg.sender) < amount) {
            revert InsufficientBalance();
        }
        IERC20(usdt).transferFrom(msg.sender, address(this), amount);
    }
`
example test function:

`    function test_deposit() public {
        vm.startPrank(usdtWhale);
        IERC20(usdt).approve(address(depositContract), 200e6);
    }`
    
  you can find a public repo with sample code [https://github.com/joshualyguessennd/foundry-usdt](https://github.com/joshualyguessennd/foundry-usdt)

**Comment by onbjerg** [comment]
Not a Forge bug: The ERC20 spec requires tokens to return a boolean for both `approve` and `transferFrom`, which USDT does not do. The issue here is that the OpenZeppelin ERC20 interface that you are using specifies that the functions are going to return, so as a part of Solidity's "success check" for the call it will attempt to parse the return data - since there is none, the call reverts.

You can fix it by using your own ERC20 interface that follows USDT's behavior:

```solidity
interface IERC20 {
    function approve(address spender, uint256 amount) external;
    function transferFrom(address from, address to, uint256 value) external;
    function balanceOf(address account) external view returns (uint256);
}
```

I've tested this locally on your repository and it works as expected :) There's a bunch of tokens like this: https://github.com/d-xo/weird-erc20
