### ISSUE TITLE
`forge script --verify --resume` does not retry all latest transactions

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#2688]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:20:50.211015Z)

### What command(s) is the bug in?

forge script --verify

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have deployed multiple contracts through scripting using `forge script --broadcast --verify` and ran into the problem
```
Error: 
Etherscan could not detect the deployment.
```
Usually, I am able to continue contract verification by running `forge script --verify --resume`. This time, however, forge will only retry verification of only 1/5 contracts.
<img width="435" alt="image" src="https://user-images.githubusercontent.com/103113487/183830935-a3669635-eb62-4811-8ee7-3f3a85209f30.png">
Re-running doesn't change this.

If I look into `broadcast/../run-latest.json` I see all of the `CREATE` transactions and nothing seems unusual to me.
<img width="337" alt="image" src="https://user-images.githubusercontent.com/103113487/183832253-c02717bb-b466-4df9-831f-245fda3b4feb.png">

**Comment by joshieDo** [comment]
So after troubleshooting over DMs, two issues came out of here.

* Contract 1: one of the transaction receipts had the wrong `transactionIndex`. I'm not sure how this could have happened. It's important, since we sort the receipts using that field. This lead to mismatched bytecode/contract/transaction/receipt. (1) 

* Contract 2: we were comparing bytecodes of different compiled versions of the same contract. However, we didn't show any kind of information regarding that. We just skip that contract.

**Comment by mds1** [comment]
@joshieDo @0xPhaze is this still an issue, or have changes to the script code since august resolved the two issues above?

**Comment by 0xPhaze** [comment]
I think there might have been multiple confounding factors. The overall experience has improved a lot and I would not be able to reproduce this atm, so closing for now.
