### ISSUE TITLE
CREATE2 address not properly generated in Forge

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/foundry#2777]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e385736 2022-08-13T00:08:48.145581Z)

### What command(s) is the bug in?

forge test

## Description

I can't get a test to pass in which I'm testing the address of a contract created with create2. I'm using the [`computeCreate2Address`](https://github.com/foundry-rs/forge-std/blob/aa2e9a3f240e48ce801d54d68bccc6ac0e2b8ca7/src/Utils.sol#L49-L51) utility from forge-std, and then checking the value I get with the actual contract being deployed. What I did:

1. Checked that bytecode hashes match
2. Checked that the salts match
3. Checked that the deployer contracts' addresses match
4. Disabled the metadata hash in the Foundry configuration file

## How to Reproduce

1. Clone https://github.com/paulrberg/create2-repro
2. Run `forge test -vvvv` to see how the `testDeploy__Event` fails (a mismatch between proxy addresses).

**Comment by mds1** [comment]
When computing `deploymentBytecodeHash`, you need to use `abi.encodePacked` or `bytes.concat` (the latter is cheaper and simpler and IIRC will ultimately replace `encodePacked`), instead of `abi.encode`. You can also use `type(MyContract).creationCode` instead of the `getCode` cheatcode, but both are equivalent

**Comment by paulrberg** [comment]
Oh, good catch. Thanks very much for your help @mds1!

Both `abi.encodePacked` and `bytes.concat` made the test pass. Interestingly, not using anything at all, i.e. passing the `bytes memory` bytecode directly to `keccak256`, also worked. Solidity is changing so fast!

Sorry for the false positive.

**Comment by mds1** [comment]
>  Interestingly, not using anything at all, i.e. passing the `bytes memory` bytecode directly to `keccak256`, also worked. 

Good point, this would also work for your case, but only because you have no constructor args. Basically what happens is the constructor args are just ABI encoded and concatenated to the end of the bytecode. So that's why (1) using the bytecode directly, (2) `abi.encodePacked`, or (3) `bytes.concat` all work: they just return the input bytecode since you have no constructor args. Whereas `abi.encode` is encoding the bytes array and so it does not return the input bytecode.

If you did have constructor args, you'd do `bytes.concat(bytecode, abi.encode(arg1, arg2))` and use that as the keccak input. 

Anyway, glad you got it working!

**Comment by paulrberg** [comment]
Thanks for the additional color - again, very helpful.

> Whereas `abi.encode` is encoding the bytes array and so it does not return the input bytecode.

Makes sense.
