### ISSUE TITLE
vm.expectRevert unable to use custom errors declared outside of contract

### ISSUE THREAD

**Issue by ammonwerner1** [foundry-rs/foundry#2829]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fb9bc90 2022-08-15T16:31:02.329212Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

To my knowledge, there is no way for vm.expectRevert() to detect a custom error that has been declared outside of a contract although this is a common place to declare them: https://docs.soliditylang.org/en/v0.8.11/contracts.html#errors

---

Example:

When I define a custom error outside a contract:

```
pragma solidity ^0.8.13

error CustomError();

contract MyContract {}
```

and I call

`vm.expectRevert(MyContract.CustomError.selector);`

I get the following error: 

> error[9582]: TypeError: Member "CustomError" not found or not visible after argument-dependent lookup in type(contract MyContract). 

Only declaring the error inside the contract fixes the error:

```
pragma solidity ^0.8.13

contract MyContract {
    error CustomError();
}
```

**Comment by rkrasiuk** [comment]
this error occurs because the `CustomError` is no longer defined in the scope of the contract, but you are trying to access it as such. 
if you are importing the file with the directive in a form of `import "some-path.sol"`, it imports all global symbols (like `MyContract` & `CustoError`) into the current scope. the solution is to call `vm.expectRevert(CustomError.selector);`

**Comment by rkrasiuk** [comment]
i am closing this issue as irrelevant to foundry. otherwise, happy to elaborate more on solidity imports
