### ISSUE TITLE
`vm.setEnv` won't work

### ISSUE THREAD

**Issue by nduchak** [foundry-rs/foundry#3107]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

2.0

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

Let's say we have a contract that deploys a butch of contracts. If we rich block limit then this deployment will fail (execution of SC method). I try to split deployment into 2 methods and run `forge script` for both of them. As I need deployed addresses from first deployment run in the second method I simply try to put it to env using `vm.setEnv`, but when I try to execute the second method this env vars is empty. Not sure maybe I misunderstood or doing something wrong.

**Comment by Elyx0** [comment]
Your deployment script can use storage to split deployment in several txs if needed can't it?

```c
contract Deploy is Script {
	
	deployedAddressPart1 address[];

	doPartOne() public {
		// deploy
		deployedAddressPart1 = (new Part1Deployer()).getDeployedAddresses();
	}

	doPartTwo() public returns (address[]) {
		// deploy
		new Part2Deployer(deployedAddressPart1);
	}

	run(){
		doPartOne()
		doPartTwo()
	}		

}
```

or you can look at `vm.readFile` / `vm.writeFile`. You might be able to read from the `./out/` informations about part1

**Comment by nduchak** [comment]
```
run(){
		doPartOne()
		doPartTwo()
	}
```
This one doesn't solve the block limit issue. I want to have two runs of `forge script` for `partOne()` and `partTwo()`
Do you confirm that `vm.setEvm` doesn't work?(As this one is a most easier way to share state which doesn't require any additional parsing of json file)

**Comment by nduchak** [comment]
I already have a workaround where I parse `broadcast`  file , but it's quite tricky to determine wich address related for which contract (If you deploy the same contract few times, you have the same `contractName` in broadcast file )

**Comment by 0xYYY** [comment]
environment variables set by a process are only accessible by itself and its child processes

thus, calling `setEnv` will only modify env vars of the currently running `forge` process, and won't affect the shell (`forge`'s parent process), that's why you can't access them in the second `forge` run

(we should probably clarify this in the book)

**Comment by onbjerg** [comment]
Yeah if I understand correctly you're doing:

- Run the first script, which does `vm.setEnv` and then exits.
- Run the second script, expecting environment variables to be set from the first run

This won't work and is not the intended use case - environment variables only exist for the current process in which it is set, so once the process exits the environment variable is not persisted.

You can write what you need to a file using the file cheatcodes, and read it in the other script. It seems like you're also saying that you're running out of gas - would you mind opening up a discussion on this repository with some more information on how you achieve that/what the gas limit is? It should be *very* high, so it should not present a problem. You might also be able to raise it.

Information you'd ideally give:

- What is the gas limit in your script?
- How much gas does the script use?
- A trace of the script so we can figure out if something else is consuming all of your gas

Closing this since environment variables can't work this way
