### ISSUE TITLE
Turn off solc optimizer for test harness contracts

### ISSUE THREAD

**Issue by hexonaut** [foundry-rs/foundry#317]
If test files are very large / complex it can take `solc` a long time to process with optimizations turned on. You can see an example of this in https://github.com/makerdao/spells-mainnet where compiling `DssSpell.t.sol` with optimizations turned on takes around 10 minutes. We still do want to test against the optimized target contract though.

I don't see a strong need to optimize test files as they aren't going on chain. I think the default behaviour should be to just turn off the optimizer for all test files even when it's turned on in general. Maybe there can be an override to turn it on, but I fail to see the use case.

**Comment by wilsoncusack** [comment]
Many of us use the tests to track gas changes and optimizations. Though you could still see improvements with the optimizer off, IMO it is nice to get a sense for what gas will be when deployed, which of course will have been optimized. 

That said, not opposed to defaulting to off for test performance and having a config.

**Comment by hexonaut** [comment]
So I'm not suggesting we turn off the optimizer for the actual contract which is where you care about the gas improvements. This is just for the test harness contracts that are calling into the target contracts. Whether the test harness is optimized or not should not affect the gas usage delta which is what you are interested in.

**Comment by wilsoncusack** [comment]
Ah I see. Misunderstood. Fully support!

**Comment by hexonaut** [comment]
Just realized the title was confusing. Updated.

**Comment by brockelmore** [comment]
Possible solution but would need to know more about `ethers::solc` from @mattsse, but we already support multiple solc jobs for different pragma versions. Not sure how we could exactly configure this, but should be possible to spin up a solc instance with optimizations off for test contracts

**Comment by onbjerg** [comment]
Looked into this, I don't think it's currently possible(?) in solc.

Looking at the compiler input, the optimizer is set globally for all sources in the compilation job, and there is no way for us to manually specify the bytecode of a contract that should be imported, unless that behaviour is undocumented. So there is no way for us (as far as I can tell) to compile non-test contracts with the optimizer on, and then afterwards compile test contracts, specifying the optimized version of the bytecode for non-test contracts when solc resolves imports.

A way to get around it short-term, I guess, is to first compile the non-test contracts with the optimizer on, and then in tests use `vm.getCode` instead of importing the contracts, but that's not a super nice solution.

>Possible solution but would need to know more about ethers::solc from @mattsse, but we already support multiple solc jobs for different pragma versions.

I think this is only supported if you do not import contracts with conflicting versions, i.e. you sort of have two "isolated" source trees.

**Comment by lucas-manuel** [comment]
Close-able? @mds1

**Comment by mds1** [comment]
hmm it would still be great if we can find a workaround here, so src contracts can always be compiled with production settings and tests can be compiled with no optimizers

**Comment by hexonaut** [comment]
Yeah I'm still in favour of this if possible.

**Comment by hexonaut** [comment]
Actually, I'm not sure what's changed, but the spells example above is now going much faster (27s vs 10m from before). Was this implemented? It's also possible the solc optimizer is just much better since 0.6 as spells mainnet was upgraded to 0.8.

In any case this isn't a big deal anymore so I'm going to close.
