### ISSUE TITLE
`forge build` compile the YUL file with the error "Field "settings.remappings" cannot be used for Yul."

### ISSUE THREAD

**Issue by bixia** [foundry-rs/foundry#3173]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1d1e182 2022-09-11T00:04:31.351526Z)

### What command(s) is the bug in?

forge b

### Operating System

macOS (Apple Silicon)

### Describe the bug

i write an YUL file, and i hope the forge can compile it for me. but it fails with the corresponding error:
```js
(base) ➜  temp git:(master) ✗ forge b  
[⠢] Compiling...
[⠢] Compiling 10 files with 0.8.16
[⠆] Solc 0.8.16 finished in 1.99s
[⠰] Compiling 1 files with 0.8.16
[⠔] Solc 0.8.16 finished in 6.38ms
Error: 
Compiler run failed
Field "settings.remappings" cannot be used for Yul.

```
and also, i create an repo to replicate this error, please check:
https://github.com/bixia/temp/tree/master/src

**Comment by rkrasiuk** [comment]
@bixia this error comes straight from the compiler since the remappings to `forge-std` & `ds-test` are added by default.
https://github.com/ethereum/solidity/blob/f808855329c8c704f0fb5d7d0738a439a5d2bfaf/libsolidity/interface/StandardCompiler.cpp#L1389-L1398

@mattsse @gakonst wdyt about doing a separate compiler run for `.yul` files if there are any detected?

**Comment by mattsse** [comment]
that makes sense and another `sanitize` call on the CompilerInput to make it work with yul

**Comment by rkrasiuk** [comment]
@mattsse sry for no update, i actually found the PR with support for yul in ethers that did that. i'll put out the PR shortly which omits remappings and revertStrings for yul
