### ISSUE TITLE
Getting OutOfGas error on Aurora

### ISSUE THREAD

**Issue by vyorkin** [foundry-rs/foundry#3247]
### Component

Cast, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (152e200 2022-09-13T00:05:42.069519Z)

### What command(s) is the bug in?

cast call

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hi! I'm running:
```
anvil --fork-url https://aurora-mainnet.infura.io/v3/3ea24ab163f04f4893a91af359d24258
```
And trying to get the [USDT (0xdAC17F958D2ee523a2206206994597C13D831ec7)](https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7) `balanceOf` `0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266` (first anvil-generated account) using the following `cast` command:
```
cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 --from 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 "balanceOf(address account) external view returns (uint256)" 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
```

The error is:
```
Error:
(code: -32603, message: EVM error OutOfGas, data: None)
```

**Comment by mattsse** [comment]
thanks for this

turns out aurora's gas limit is always `0` in the `eth_getBlockByNumber` response, I guess since it's basically unlimited: https://doc.aurora.dev/compat/evm/#gaslimit

this resulted in anvil setting `0` for the block gas limit, basically always ensuring OutOfgas

I guess the right fix here would be to not set the gas limit of it's 0

**Comment by mattsse** [comment]
also, the USDT contract you linked is on ethereum, and does not exist on aurora

**Comment by vyorkin** [comment]
@mattsse thank you!
yeah, I messed up a bit, changing networks too often %)
