### ISSUE TITLE
bug (config): file paths not resolved if submodule specifies root path remappings

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#3440]
### Component

Forge

### Describe the feature you would like

Steps to reproduce:
1. Clone [this repo](https://github.com/mds1/forge-test-my-proj) and run `forge install`
2. Run `forge build`, it fails with the below error
3. In `lib/forge-test-my-dep`, open `foundry.toml` and comment out the remappings
4. Run `forge build`, it passes

```
[⠊] Compiling...
Error: 
Failed to resolve file: "/Users/mds/Documents/projects/forge-test-my-proj/lib/forge-test-my-dep/script/BaseScript.sol": No such file or directory (os error 2).
    --> "/Users/mds/Documents/projects/forge-test-my-proj/script/Counter.s.sol"
        "script/BaseScript.sol"
    Check configured remappings.
```

**Comment by h0tw4t3r** [comment]
suffering from the same exact issue.
importing @thirdweb contracts and OZ in the project breaks remappings.
I have the latest foundry and foundry-std versions

**Comment by mattsse** [comment]
this is a general problem with absolute import paths.

you can fix this by using relative paths for contracts you import from folders like script or test, or simply overwrite the remapping.

I'd recommend against remappings for folders in the same project.

**Comment by mattsse** [comment]
ref #1855

**Comment by PaulRBerg** [comment]
Just bumped into this issue while installing @mds1's library [solidity-generators](https://github.com/mds1/solidity-generators).

I also have absolute import paths, and I want to counter @mattsse's suggestion from above that we should simply use relative paths.

Relative paths can get really ugly and hard to maintain in complex projects. [Several Foundry users](https://twitter.com/jtriley_eth/status/1594047400057921536) use absolute paths because of the aforementioned reason.

**Comment by PaulRBerg** [comment]
Don't think this issue should have been closed?

https://github.com/mds1/solidity-generators/pull/2 was related but it didn't fix the issue with Foundry itself.

**Comment by mds1** [comment]
Huh interesting. I guess because I opened this issue originally, a PR from a repo in my namespace was able to close it? Either way, re-opening it now

**Comment by 0xGabi** [comment]
I started experiencing the same issue when I upgrade `foundry` to the latest nightly for the submodule https://github.com/0xPhaze/upgrade-scripts.

In my particular case everything was working fine with foundry commit https://github.com/foundry-rs/foundry/commit/3d5f038.

**Comment by PaulRBerg** [comment]
For future reference: when @mattsse said this:

> simply overwrite the remapping.

He was referring to set one or more of the following remappings in your project:

```txt
script/=script/
src/=src/
test/=test/
```

You only have to do this for those remappings that are overwritten by your dependencies.

**Comment by aathan** [comment]
I guess my #4597 is this same issue. I just want to add that relative imports in the dependent project suffer from this problem (which seems to contradict some earlier suggestions in this thread). I believe solc resolves those relative paths into relative paths, relative to the project root. Thus `import "./SomeOtherFile.sol";` in the dependent project resolves to `src/SomeOtherFile.sol` and then this matches `src/=src/`, which is remapped into the dependency.

It seems to me that relative in remappings.txt in `lib/...` should be prepended with `lib/...` as they're loaded into foundry's vfs or solc command-line builder?

**Comment by onbjerg** [comment]
Related to https://github.com/foundry-rs/foundry/issues/1855

**Comment by thedavidmeister** [comment]
it seems like remappings are not compatible with code that might ever be used as a dependency elsewhere, which is probably most code if you consider that people often like to test their smart contracts against external protocols without needing to always work from mainnet forks.

maybe the docs could explain this better

examples like

```
import "forge-std/Test.sol";
```

should really be 

```
import "../lib/forge-std/src/Test.sol";
```

for a project with a flat `./src/*.sol` structure.

The issue I see is that the former promotes/allows unsafe behaviours because, if i understand correctly what foundry is doing, it seems that the version of libs compiled into contracts is whatever version is in the root `lib/*` NOT the version in `lib/somedep/lib`.

It would be very easy for some subtle change to be made in a lib that would break the functionality of the dependency, but still compile, and not necessarily show up in testing because the SUT is the current repo, not the test suite of the dependency.

I'm still a bit confused as to how this works, but it seems to me like the only way for code to be sure that consumers get the same code including its dependencies is to always use relative paths for everything, including dependency libs.

i.e. `forge install` recursively checks out dependencies but then `forge build` always remaps every lib to whatever is in the root `lib/` rather than the recursive libs.

**Comment by aathan** [comment]
The fundamental issue is that *using* a solidity project as a dependency does not mean using its build artifacts, it means using its source code, and therefore its source files, while being built, must resolve *their* dependencies based on that project's own dependencies. When this is combined with the fact that many projects have similar dependencies (e.g., on openzep), import resolution conflicts become likely. We can look to other languages for inspiration so as not to reinvent the wheel (e.g., c's include file search paths, rust toml's [patch...], etc.

It seems that a necessary/baseline feature would be for solc to be able to resolve imports based on the context of the instant file being parsed. I think this may NOT be a current feature of solc. What I mean by this is that the imports for a file in a/b/c/d should be resolved based on the fact that that file is in a/b/c/d not based on the fact that the file is in a. Then, if a dev wants to globally override what `lib/openzep` means, there would be some mechanism to explicitly override that resolution everywhere (.e.g., like the toml [patch] or a command line argument to NOT use local context for certain prefixes).

The additional problem here is that what a dev has chosen to specify in the import statement, in the source files of a project, plays a big role. As noted in other comments, whether they've chosen to use relative import paths in the source and whether those relative import paths state simply `lib/` or `../[whatever]/lib` can matter.

At least some of the above I think can be achieved even without explicit compiler support by re-writing of files, and by clever use or remappings. E.g., all dependencies (recursively) could have the imports that match *their locally specified remappings* re-written to `import "dep1/lib/...";` and the remappings specified to the top level compiler would then contains a `dep1/lib` remapping. This would mean foundry is essentially pre-processing the source files and compiling the pre-processed output, not the original files.

pre-processing of solidity is another topic. I almost always find it necessary to use a (custom) python based pre-processor to generate deployment vs dev versions of solidity files for anything but trivial projects. E.g., to strip out console2.log() calls, and/or restructure source files so that contracts deployed to public chains, vs those deployed to anvil or hardhat nodes for testing, are lean and clean.

The solidity language devs, IMHO, are not spending enough effort on these issues and need to do an iteration on some of the language features that relate to devops.

**Comment by thedavidmeister** [comment]
@aathan FWIW i just went down the road of switching to relative imports and it looks like a bit of a dead end actually

the problem is if you have two deps with the _same_ dependency as a relative path in their respective `lib` directories

any types that exist in this _same_ dependency (i.e. exact commit same) are treated as different types by the compiler

i've had this experience in rust as it is strict about types only being the same type if the dep is exactly the same, but rust is aware of git revisions so treats identical deps as identical, however they are imported

i'm now wondering, in lieu of what sound like large low level upstream changes, if it would be possible to have some kind of warning/error if foundry detects a discrepency between the ?unavoidable? root level dep commit/version and the same dependency used somewhere in the tree of submodules

**Comment by thedavidmeister** [comment]
or alternatively, if same-commit identical submodules are found, perhaps there's a way for forge to normalize/dedupe them to avoid the type issues

**Comment by aathan** [comment]
Oh ya, I forgot about the type names. solc would need to "namespace" the type names based on which source files are referencing the type name, such that the types are matched vs those defined only in the imports of that source file; and, if a type reference in a file outside said project resolves to a type in that project, e.g., via a qualified name, that has to resolve correctly too.

For example, if some global `struct Foo` is defined in an import inside a `lib/` project, but is also defined in the top level project, should that be an error? Or should the source files inside `lib/` find that struct, and the source files at the top level should find the other one? It's a mess, but that sounds about right.

The foregoing paragraph was written before I read https://github.com/foundry-rs/foundry/issues/3440#issuecomment-1638108427 which seems to imply solc *does* distinguish types based on import source. I've simply not done any careful observation of this issue. Are you sure about that? My assumption would have been than a global scope struct is resolved irrespective of it's import source, and any conflicts have more to do with the import ordering of a particular compilation unit, than the namespace or type annotations made by solc when traversing a type def. Some experiments are in order, and/or I am going to reference this conversation to the solc devs.

@thedavidmeister as far as the relative imports go, that is precisely the issue I was addressing in the prior comment. To clarify, what I was suggesting is that foundry's build strategy should change to a "preprocess then compile the preprocessed output dir", and all imports in the output (i.e., preprocessor output) would be rewritten such that relative imports in subprojects are prepended with a unique id (`lib/...` --> `projA/lib/...`) such that they become distinguishable, and (possibly *generated*) top-level remappings can specify `projA/lib/...` `projB/lib/...` in a completely disambiguated fashion.

**Comment by aathan** [comment]
@onbjerg I've PTAL'ed and commented there.

**Comment by thedavidmeister** [comment]
@onbjerg that sounds basically perfect to me, does it introduce the issue i saw with relative paths though?

namely that some type can be defined in two commit-identical dependencies and treated by solidity as different types?

**Comment by thedavidmeister** [comment]
@Evalir @onbjerg  actually i'm still getting quite a lot of errors that mean i can't compile based on import resolving

```
thedavidmeister@davids-iMac rain.orderbook % forge build
[⠊] Compiling...
[⠒] Unable to resolve imports:
      "rain.datacontract/lib/LibDataContract.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/concrete/RainterpreterExpressionDeployerNP.sol"
      "rain.datacontract/lib/LibDataContract.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/concrete/RainterpreterNP.sol"
      "rain.solmem/lib/LibStackPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/op/evm/LibOpTimestamp.sol"
      "rain.solmem/lib/LibMemCpy.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/op/LibOp.sol"
      "rain.solmem/lib/LibPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/state/LibInterpreterState.sol"
      "rain.lib.memkv/lib/LibMemoryKV.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/state/LibInterpreterState.sol"
      "rain.solmem/lib/LibUint256Array.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/caller/LibContext.sol"
      "rain.solmem/lib/LibPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/integrity/LibIntegrityCheck.sol"
      "rain.solmem/lib/LibMemCpy.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/state/LibInterpreterStateDataContract.sol"
      "rain.solmem/lib/LibStackPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/integrity/LibIntegrityCheck.sol"
      "rain.solmem/src/lib/LibPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/concrete/RainterpreterExpressionDeployerNP.sol"
      "rain.solmem/lib/LibStackPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/concrete/RainterpreterExpressionDeployerNP.sol"
      "rain.solmem/lib/LibUint256Array.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/op/LibOp.sol"
      "rain.solmem/lib/LibPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/op/LibOp.sol"
      "rain.solmem/lib/LibBytes.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/state/LibInterpreterStateDataContract.sol"
      "rain.solmem/lib/LibStackPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/op/evm/LibOpBlockNumber.sol"
      "rain.solmem/lib/LibPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/state/LibInterpreterStateDataContract.sol"
      "rain.solmem/lib/LibStackPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/op/evm/LibOpChainId.sol"
      "rain.solmem/lib/LibStackPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/op/LibOp.sol"
      "rain.solmem/lib/LibPointer.sol" in "/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/parse/LibParse.sol"
with remappings:
      caller/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/caller/
      compile/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/compile/
      ds-test/=/Users/thedavidmeister/Code/rain.orderbook/lib/forge-std/lib/ds-test/src/
      erc4626-tests/=/Users/thedavidmeister/Code/rain.orderbook/lib/openzeppelin-contracts/lib/erc4626-tests/
      eval/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/eval/
      extern/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/extern/
      forge-std/=/Users/thedavidmeister/Code/rain.orderbook/lib/forge-std/src/
      integrity/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/integrity/
      ns/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/ns/
      op/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/op/
      openzeppelin-contracts/=/Users/thedavidmeister/Code/rain.orderbook/lib/openzeppelin-contracts/
      parse/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/parse/
      rain.chainlink/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/lib/rain.chainlink/src/
      rain.erc1820/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.erc1820/src/
      rain.extrospection/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.factory/lib/rain.extrospection/
      rain.factory/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.factory/
      rain.interpreter/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/
      rain.lib.hash/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/lib/rain.lib.memkv/lib/rain.lib.hash/src/
      rain.lib.typecast/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/lib/rain.lib.typecast/src/
      rain.math.fixedpoint/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.math.fixedpoint/src/
      rain.math.saturating/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.math.fixedpoint/lib/rain.math.saturating/src/
      rain.metadata/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.metadata/src/
      state/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.interpreter/src/lib/state/
      lib/openzeppelin-contracts:openzeppelin/=/Users/thedavidmeister/Code/rain.orderbook/lib/openzeppelin-contracts/contracts/
      lib/rain.factory:rain.datacontract/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.factory/lib/rain.interpreter/lib/rain.datacontract/src/
      lib/rain.factory:rain.lib.memkv/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.factory/lib/rain.interpreter/lib/rain.lib.memkv/src/
      lib/rain.factory:rain.solmem/=/Users/thedavidmeister/Code/rain.orderbook/lib/rain.factory/lib/rain.extrospection/lib/rain.solmem/src/
```

The only way I can see to fix these is to install the deps globally in the root of the project, they aren't being picked up by the submodule as the submodule's own deps

I think this issue is still unresolved (i ran foundryup just now)

```
thedavidmeister@davids-iMac rain.orderbook % forge --version
forge 0.2.0 (8e365be 2023-07-18T00:32:55.929185000Z)
```

**Comment by thedavidmeister** [comment]
It also looks like the same issue as relative paths has now been introduced for remapped paths @onbjerg 

```
thedavidmeister@davids-iMac rain.orderbook % forge test
[⠊] Compiling...
[⠑] Compiling 115 files with 0.8.19
[⠘] Solc 0.8.19 finished in 2.71s
Error: 
Compiler run failed:
Error (2333): Identifier already declared.
 --> lib/rain.interpreter/src/concrete/RainterpreterExpressionDeployerNP.sol:8:1:
  |
8 | import "rain.datacontract/lib/LibDataContract.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> lib/rain.solmem/src/lib/LibPointer.sol:16:1:
   |
16 | library LibPointer {
   | ^ (Relevant source part starts here and spans across multiple lines).

Error (2333): Identifier already declared.
 --> lib/rain.interpreter/src/concrete/RainterpreterExpressionDeployerNP.sol:8:1:
  |
8 | import "rain.datacontract/lib/LibDataContract.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> lib/rain.solmem/src/lib/LibPointer.sol:8:1:
  |
8 | type Pointer is uint256;
  | ^^^^^^^^^^^^^^^^^^^^^^^^

thedavidmeister@davids-iMac rain.orderbook % cd lib/rain.interpreter/lib/rain.datacontract/lib/rain.solmem/
thedavidmeister@davids-iMac rain.solmem % git log
commit 7b2f04d6e0d7d4573e6b0a17bd9c7b84a7fde05f (grafted, HEAD, origin/main, origin/HEAD, main)
Author: David Meister <thedavidmeister@gmail.com>
Date:   Mon Jul 10 14:26:49 2023 +0400

    Merge pull request #4 from rainprotocol/2023-07-10-index-signed
    
    toIndexSigned
thedavidmeister@davids-iMac rain.solmem % cd ../../../rain.solmem 
thedavidmeister@davids-iMac rain.solmem % git log
commit 7b2f04d6e0d7d4573e6b0a17bd9c7b84a7fde05f (grafted, HEAD, origin/main, origin/HEAD, main)
Author: David Meister <thedavidmeister@gmail.com>
Date:   Mon Jul 10 14:26:49 2023 +0400

    Merge pull request #4 from rainprotocol/2023-07-10-index-signed
    
    toIndexSigned
```

**Comment by thedavidmeister** [comment]
@aathan the problem with just saying that types should be different if they are in different folders, is that sometimes they _are_ the same

in the example i'm running into now ^^ i did start going down the road of manually differentiating between `Pointer` depending on where it comes from, like `import { Pointer as DataContractPointer } from ...`

then what you run into is "can't automatically convert between types" which involves wrapping and unwrapping every type at every function boundary. If you write some library that wants its type as an input/output then you can't use that library in two places in a single repo.

now, if these `Pointer` types were from different source code, no matter how "minor" the difference, then sure I agree that the correct thing to do is treat them differently (that's what rust does)

in this case though, the exact same commit of a dependency is being treated as "already declared" simply because two different deps use it

perhaps if we were to use the preprocessing idea that you are suggesting, all the nested deps could be "hoisted" to the root
lib and have a few bytes of their commit appended like `openzeppelin-contracts@01234567` which would have the effect of "deduping" while preserving the ability to "mess around" manually for debugging if the need arises.

**Comment by thedavidmeister** [comment]
kk, so i did some experimenting comparing 

```
forge 0.2.0 (cc5637a 2023-06-02T00:22:41.615504000Z) - some old "stable" commit
forge 0.2.0 (0e72b71 2023-07-19T00:37:22.147807000Z) - today's nightly
```

what I found was, that i had added `auto_detect_remappings = false` to the data contract dep and this changed how things behave. Also, depending on whether I have a copy of the `rain.solmem` dependency in the project root or not changes how things behave (with every version of `rain.solmem` in the nested deps being on the same commit).

Running `forge build` from root.

| version | auto detect | dep in root | error |
| -- | -- | -- | -- |
| cc5637a | Y | Y | Identifier already declared. |
| cc5637a | N | Y | Identifier already declared. |
| cc5637a | Y | N | - |
| cc5637a | N | N | Identifier already declared. |
| 0e72b71 | Y | Y | Identifier already declared. |
| 0e72b71 | N | Y | Identifier already declared. |
| 0e72b71 | Y | N | Unable to resolve imports |
| 0e72b71 | N | N | Unable to resolve imports |

**Comment by PaulRBerg** [comment]
Related: https://github.com/foundry-rs/foundry/issues/5447

**Comment by thedavidmeister** [comment]
@PaulRBerg in my case some of what i'm seeing could potentially be #5447 as i do have multiple instances of the same dep in my tree
