### ISSUE TITLE
Incorrect Gas Report 

### ISSUE THREAD

**Issue by amit-supraoracles** [foundry-rs/foundry#3475]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (def1d61 2022-09-23T00:11:51.396013251Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Following code snipped gas costs different when deploy and test using Remix IDE and Foundry.

I used following smart contract.
```
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.8.7;

contract GasCost {
  
  mapping(uint256 => uint256) internal SomeData;

  // REMIX IDE : 1st execution cost: 44117
  // REMIX IDE : 2nd onwards cost  : 24217
  function store(uint64 _key, uint256 _value) public {
     SomeData[_key] = _value ;
  }
}  

```
And this test contract
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import "../src/Counter.sol";

contract CounterTest is Test {
    Counter public counter;
    
    function setUp() public {
       counter = new Counter();
    }

    function testStore(uint64 _key, uint256 _value) public {
        counter.store(_key, _value); 
     
    }
}
```
I run the test and got following result.

![image](https://user-images.githubusercontent.com/84004854/195004721-71ce5849-07f5-4d32-9576-55e2d31640d9.png)

**Comment by kasodesyn** [comment]
I have the same problem.

**Comment by mds1** [comment]
In remix the 44117 number likely includes the 21000 intrinsic gas, which forge hides from the gas report since the gas report just shows the cost of executing the function. Subtracting this away gives a first execution cost in remix of 23117 (not sure what they're reporting in the second execution cost). 

The remaining difference of 23117 - 22426 = 691 gas is from the calldata cost, which remix is likely including and forge excluding. Calldata costs 4 gas per zero byte and 16 gas per nonzero byte. There are 64 bytes of calldata for this method. This implies the cost of the mix of zero and nonzero calldata bytes adds up to 691 gas, though ChatGPT tells me that "solve `691 = 4x + 16y` with the condition `x + y = 64`" has no solution so I assume the inputs to each call (remix vs. forge) was different

Per the above these numbers seem roughly correct and inline with what I'd expect, so going to close this, but feel free to ask any more questions here
