### ISSUE TITLE
`forge init` a project from Etherscan sources

### ISSUE THREAD

**Issue by DaniPopes** [foundry-rs/foundry#3615]
### Component

Forge

### Describe the feature you would like

We already support fetching Etherscan sources and creating a project for it, we could also expose this to the user with a `forge init` flag that replaces the default `Counter.sol` with the Etherscan source tree.

### Additional context

Relevant functions:

https://github.com/foundry-rs/foundry/blob/8b0af47f4493430a9f6f12b2c55e06dcfd215374/common/src/compile.rs#L396-L399

https://github.com/foundry-rs/foundry/blob/8b0af47f4493430a9f6f12b2c55e06dcfd215374/common/src/compile.rs#L425-L426

https://github.com/foundry-rs/foundry/blob/8b0af47f4493430a9f6f12b2c55e06dcfd215374/common/src/abi.rs#L283-L287

**Comment by mds1** [comment]
> We already support fetching Etherscan sources and creating a project for it

How do you currently do this?

Possibly related to this issue: `cast etherscan-source` pulls etherscan sources into a local dir, but the resulting file structure cannot be immediately compiled with forge, which was tedious last time I used that command (which was a few months ago, so maybe it's changed since). Seems we could fix `etherscan-source` logic to be compatible with forge, and reuse the same code for this issue

**Comment by DaniPopes** [comment]
> How do you currently do this?

Linked the functions under Additional context

> Possibly related to this issue: cast etherscan-source pulls etherscan sources into a local dir, but the resulting file structure cannot be immediately compiled with forge

Yeah, Etherscan provides compiler settings and remappings when present which would need to be saved to a `foundry.toml`

**Comment by mds1** [comment]
> Linked the functions under Additional context

Ah sorry I misinterpreted, thought you meant this functionality was already exposed somewhere else in the cast/forge CLI 😅
