### ISSUE TITLE
`forge test` incorrectly assigns balances to the tested contracts

### ISSUE THREAD

**Issue by lekhovitsky** [foundry-rs/foundry#3616]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c06b532 2022-11-05T00:10:39.000335Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

When the instance of the tested contract is created, it is expected that its balance is zero or the value passed via `--initial-balance`. The actual value however might be non-zero, and `--initial-balance` has no control over it.

Consider this simple test:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";

contract X {}

contract XTest is Test {
    X private x;

    function setUp() public {
        x = new X();
    }

    function testBalanceIsZero() public {
        assertEq(address(x).balance, 0);
    }
}
```

It passes if we don't fork the state:
```bash
forge test -vvv
```

However, if we fork the Ethereum mainnet state, it fails:
```bash
forge test -vvv --fork-url <SOME_MAINNET_RPC_URL>
```

Examining stack traces, one'll find a strange number `5656000000000000000`. This is, in fact, the actual mainnet balance of an address [`0xce71065d4017f316ec606fe4422e11eb2c47c246`](https://etherscan.io/address/0xce71065d4017f316ec606fe4422e11eb2c47c246) at which `x` is deployed.

**Comment by mattsse** [comment]
ah lol `0xCe71065D4017F316EC606Fe4422e11eB2c47c246` is in fact the address that's derived for the first contract created in a test deployed by the default sender (0x00a329c0648769a73afac7f9381e08fb43dbea72)

But since this is triggered by the test contract, I think the correct behaviour here would be to initialize an empty account instead of retrieving it from the forked chain.

wdyt @mds1 ?

**Comment by mds1** [comment]
Ahh interesting! Yea, I agree with that solution—whenever a contract is created in a test, consider that an empty account with the only state being the new code. And let's make sure this only applies to new contract deploys, e.g. if you `vm.etch` to an address it should still access forked chain state even if there's new etched bytecode there (hopefully I explained that well)

Wonder how someone accidentally sent 5.656 ETH to that address on mainnet 😬

**Comment by mattsse** [comment]
hmm, thought about this a bit, and the fix is not trivial and also is unsound, because technically that's the correct behavior here, because the eth do actually exists in the contract's account

**Comment by mds1** [comment]
Yea that’s fair about soundness, it did feel a bit dirty. Some other options:
- Do nothing, and require users to just manually set the balance to zero when this occurs and is an issue for them (and note this in the book so it’s easier to debug). This is trickier if the address has nonzero balance for a rebase token, but so far that’s just a hypothetical issue and we’ve only seen this with ETH. 
-  When deploying a new contract, if the resulting address has a nonzero mainnet balance, bump deployers nonce then deploy (i.e. don’t deploy to addresses that have balance). Downside is you’d also need to run this check for every tokens, not just ETH. so perhaps get a big token list for popular chains, execute a [multicall](https://github.com/mds1/multicall) so it’s just one RPC call, and bump nonce if any call returns nonzero. I don’t think this affects determinism because no one should have a pk for those addrs so funds are stuck

**Comment by grandizzy** [comment]
this can be handled by marking the deployed contract as persistent, e.g.

```Solidity
contract XTest is Test {
    X private x;

    function setUp() public {
        x = new X();
        vm.makePersistent(address(x));
        vm.createSelectFork("mainnet");
    }

    function testBalanceIsZero() public {
        assertEq(address(x).balance, 0);
    }
}
```
results in a pass. Going to close this for now, @lekhovitsky please reopen if still an issue, thank you!
