### ISSUE TITLE
VM revert error when pranking an address that receives ether from contract

### ISSUE THREAD

**Issue by hexcowboy** [foundry-rs/foundry#3625]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8b0af47 2022-11-06T00:06:24.552295Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

minimal reproduction repo: https://github.com/hexcowboy/foundry-bug-repro

It appears that when pranking an address, the VM will revert randomly if a contract method transfers ETH using `payable(prankAddress).transfer()`. This bug is reproducible using the repo above and running `forge test -vvvv`.

Here's the test:

```solidity
    function testFuzzPayable(address[10] memory senders, uint256[10] memory amounts) public {
        for (uint256 i = 0; i < amounts.length; i++) {
            amounts[i] = bound(amounts[i], 0, 500);
        }

        // add funds to contract
        vm.deal(address(counter), 1 ether);

        for (uint256 i = 0; i < senders.length; i++) {
            vm.startPrank(senders[i]);
            counter.hello(amounts[i]);
            vm.stopPrank();
        }
    }
```

Here's the contract:

```solidity
contract Counter {
    function hello(uint256 amount) public {
        payable(msg.sender).transfer(amount);
    }
}
```

Some examples of the error logs:

```
    ├─ [32103] Counter::hello(126) 
    │   ├─ [0] console::fallback{value: 126}() 
    │   │   └─ ← "Invalid data"
    │   └─ ← "Invalid data"
    └─ ← "Invalid data"
```

```
    ├─ [34394] Counter::hello(143) 
    │   ├─ [0] PRECOMPILE::ecrecover{value: 143}() 
    │   │   └─ ← 
    │   └─ ← "EvmError: Revert"
    └─ ← "EvmError: Revert"
```

**Comment by mds1** [comment]
The problem is the addresses being used:
- The first revert is using the [console address](https://github.com/foundry-rs/forge-std/blob/5bafa16b4a6aa67c503d96294be846a22a6f6efb/src/console2.sol#L10). This is a special address to make `console.log` work, any calls to this address are intercepted and handled differently, so you should use `vm.assume` to exclude this address (and maybe it should be excluded from the fuzzer dict)
- The second is a [precompile](https://www.evm.codes/precompiled) address. You can use [`assumeNoPrecompiles`](https://github.com/foundry-rs/forge-std/blob/master/src/StdCheats.sol#L286-L316) to  remove these 

Related: https://github.com/foundry-rs/forge-std/issues/211

**Comment by hexcowboy** [comment]
> The problem is the addresses being used:

There are still a few addresses causing trouble [after ignoring the log address and the precompile addresses](https://github.com/hexcowboy/foundry-bug-repro/commit/0d601d3fc91390dccc957d4bfbb93e7487c36404). Here are a few I could find:

```
    ├─ [0] VM::startPrank(Create2Deployer: [0x4e59b44847b379578588920cA78FbF26c0B4956C]) 
    │   └─ ← ()
    ├─ [9394] Counter::hello(408) 
    │   ├─ [34] Create2Deployer::fallback{value: 408}() 
    │   │   └─ ← "EvmError: OutOfGas"
    │   └─ ← "EvmError: Revert"
    └─ ← "EvmError: Revert"
```

```
    ├─ [0] VM::startPrank(VM: [0x7109709ECfa91a80626fF3989D68f67F5b1DD12D]) 
    │   └─ ← ()
    ├─ [7103] Counter::hello(433) 
    │   ├─ [0] VM::fallback{value: 433}() 
    │   │   └─ ← "Invalid data"
    │   └─ ← "Invalid data"
    └─ ← "Invalid data"
```

```
    ├─ [0] VM::startPrank(CounterTest: [0xb4c79daB8f259C7Aee6E5b2Aa729821864227e84]) 
    │   └─ ← ()
    ├─ [7139] Counter::hello(64) 
    │   ├─ [45] CounterTest::fallback{value: 64}() 
    │   │   └─ ← "EvmError: Revert"
    │   └─ ← "EvmError: Revert"
    └─ ← "EvmError: Revert"
```

What are these addresses?

**Comment by hexcowboy** [comment]
Here's my workaround for now

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "@forge-std/Test.sol";
import "@forge-std/StdCheats.sol";
import "../src/Counter.sol";

contract CounterTest is Test {
    Counter public counter;

    function setUp() public {
        counter = new Counter();
    }

    uint256 constant LOAD = 10;

    function testFuzzPayable(
        address[LOAD] memory senders,
        uint256[LOAD] memory amounts
    ) public {
        for (uint256 i = 0; i < LOAD; i++) {
            amounts[i] = bound(amounts[i], 0, 500);
            vm.assume(senders[i] != 0x000000000000000000636F6e736F6c652e6c6f67);
            vm.assume(senders[i] != 0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
            vm.assume(senders[i] != 0x4e59b44847b379578588920cA78FbF26c0B4956C);
            vm.assume(senders[i] != 0xCe71065D4017F316EC606Fe4422e11eB2c47c246);
            vm.assume(senders[i] != address(this));
            StdCheatsSafe.assumeNoPrecompiles(senders[i]);
        }

        // add funds to contract
        vm.deal(address(counter), 1 ether);

        for (uint256 i = 0; i < senders.length; i++) {
            vm.startPrank(senders[i]);
            counter.hello(amounts[i]);
            vm.stopPrank();
        }
    }
}
```

Could I propose a cheat that provides safe payable addresses when fuzzing?

**Comment by mds1** [comment]
VM is the cheatcode address (e.g. `vm.assume`) and Create2Deployer is a deterministic create2 deployer used on many chains with `forge script`. For now you'll need to filter out those addresses which can be a bit tedious, since there's currently no way for the fuzzer to only generate addresses that can receive ETH.

Two possible foundry-level solutions if you want to create separate issues for each:

### Exclude Special Addresses

We can consider excluding special foundry addresses from the fuzz dictionary. This would be all addresses that behave differently in foundry than they do on live chains, which includes:
- VM address
- Console address
- Are there others?

Create2Deployer and precompiles are valid inputs an attacker can pass in real life, so we wouldn't want to exclude those. 

### Flag to only fuzz payable addresses

Foundry could check the ABI of a fuzzer generated address and discard it if it has code but there's no fallback/receive method. This would probably need to be a config flag as opposed to a cheatcode just based on the fuzzer architecture.

**Comment by hexcowboy** [comment]
closing for https://github.com/foundry-rs/foundry/issues/3630 and https://github.com/foundry-rs/foundry/issues/3631

**Comment by mds1** [comment]
Thank you!
