### ISSUE TITLE
`msg.sender` different in setUp and tests

### ISSUE THREAD

**Issue by xenoliss** [foundry-rs/foundry#3661]
### Component

Forge, Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8b0af47 2022-11-05T15:13:14.009577258Z)

### What command(s) is the bug in?

forge test --match-test testSameSender -vv

### Describe the bug

`msg.sender` value differs between the `setUp` function and the unit tests. Here is a minimal code to reproduce the issue:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import "forge-std/Test.sol";

contract TestMe is Test {
    address sender;

    function setUp() public {
        sender = msg.sender;
    }

    function testSameSender() public {
        assertEq(sender, msg.sender);
    }
}
```

**Comment by mattsse** [comment]
thanks for this,

there's the caller

https://github.com/foundry-rs/foundry/blob/c5791f5c2a2ccdc8d7d1cd5c77175154fb7ad6cf/evm/src/lib.rs#L39-L44

I can't remember if we deliberately deploy and test from different accounts, or if both should be the same.

cc @mds1 @gakonst

**Comment by xenoliss** [comment]
I personally have lot more use cases where I need `msg.sender` to be the same in both (setting balance, minting tokens, deploying ownable contracts etc.). But as you said maybe I'm missing something worth enough to have them different.

**Comment by mds1** [comment]
I just tested what dapptools does, since my guess was that we inherited their choice. So I ran `forge init`, modified the test file a bit as shown below, then ran forge and dapp against it

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

import "ds-test/test.sol";
import "../Counter.sol";

contract CounterTest is DSTest {
    Counter public counter;

    function setUp() public {
        emit log_named_address("setUp", msg.sender);
        counter = new Counter();
        counter.setNumber(0);
    }

    function testIncrement() public {
        emit log_named_address("testIncrement", msg.sender);
        counter.increment();
        assertEq(counter.number(), 1);
    }
}
```

Resulting output from `dapp test --verbosity 2`:

```
Running 1 tests for src/test/Counter.t.sol:CounterTest
[PASS] testIncrement() (gas: 24611)

Success: testIncrement
  
  setUp: @0x00a329c0648769A73afAc7F9381E08FB43dBEA72
  testIncrement: @0x00a329c0648769A73afAc7F9381E08FB43dBEA72
```

Resulting output from `forge test -vvv`:

```

Running 1 test for src/test/Counter.t.sol:CounterTest
[PASS] testIncrement() (gas: 30315)
Logs:
  setUp: 0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38
  testIncrement: 0x00a329c0648769a73afac7f9381e08fb43dbea72
```

So you can see dapp uses the 0x00a3 address for calling both setUp and tests, whereas forge uses a different address. I'm not sure whether or not this was an intentional decision we made to deviate from dapptools, maybe @gakonst @brockelmore @transmissions11 remember?

Either way it doesn't seem like it should matter too much, my only worry is if we change this to match dapptools, will that break tests for some people? Though intuitively I tend to agree with @xenoliss that it makes more sense for them to be the same address.

@xenoliss in the meantime you can always use `vm.prank` and `vm.startPrank` to ensure you get the same msg.sender in both places

**Comment by xenoliss** [comment]
Thanks @mds1 for the detailed answer and yes I'm currently using `vm.prank` a bit everywhere especially for this !

**Comment by transmissions11** [comment]
> intentional decision we made to deviate from dapptools, maybe @gakonst @brockelmore @transmissions11 remember?

Not that I recall, and I do think it would be the less surprising behavior to match the sender between setUp and tests.

**Comment by gakonst** [comment]
The reason was something about nonces and library pre deployment and linking IIRC during scripts/tests.

**Comment by joshieDo** [comment]
> The reason was something about nonces and library pre deployment and linking IIRC during scripts/tests. 

For `forge script` the `msg.sender` is the same at `setUp` and `run()` (and different than `CALLER`).

Howerver for forge test we're using `--sender` for when calling the test function. I'm sure we can do a `self.sender.unwrap_or(CALLER)` there?
