### ISSUE TITLE
feat(`snapshots`): track internal gas usage

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#3766]
### Component

Forge

### Describe the feature you would like

I would like to have [gas reports](https://book.getfoundry.sh/forge/gas-reports) for [free functions][1], e.g.

```solidity
function min(uint x, uint y) pure returns (uint) {
    return x < y ? x : y;
}
```

Passing `--gas-report` to Forge doesn't generate a report. The only solution as of now is to wrap my free functions in an intermediary mock contract used specifically for testing.

[1]: https://blog.soliditylang.org/2020/09/02/solidity-0.7.1-release-announcement/#:~:text=A%20free%20function%20behaves%20like,and%20in%20this%20case%2C%20msg.

**Comment by rkrasiuk** [comment]
@paulrberg as described in the book, gas reporting traces [the external contract calls](https://book.getfoundry.sh/forge/gas-tracking). since free functions act as internal functions, we cannot correctly identify calls to them.

theoretically, we could record the jumps within each call, but 1) we wouldn't be able to decode them since free/internal functions are not a part of the artifacts 2) that'd produce a lot of data which imo would dilute the value of gas reports

@mattsse @onbjerg @draganrakita curious to hear your thoughts

**Comment by rkrasiuk** [comment]
the config would still not solve the instruction to code reverse lookup, only the collected functions.

some thought dump:
- debugger already performs the reverse lookup. we could attempt to match jumps to the code by using source maps? this would be a cursed piece of code 😆 
- roll a custom ASTInspector? the idea is to traverse the AST alongside the execution bytecode

**Comment by zerosnacks** [comment]
Hi @PaulRBerg we've added gas snapshots over sections here: https://github.com/foundry-rs/foundry/pull/8952, would be great to get your feedback. It handles both external and internal gas usage.

**Comment by zerosnacks** [comment]
Marking as effectively resolved by https://github.com/foundry-rs/foundry/pull/8952
