### ISSUE TITLE
Test reverts with `Assertion failed.` when reverting to a fork snapshot, without any assertion

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#3792]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (15204ec 2022-11-29T00:07:45.954046141Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

# Report

- The following test case `testWtf` reverts with reason `Assertion failed.`, whereas no assertion is explicitly performed within it

```Solidity
// SPDX-License-Identifier: GNU AGPLv3
pragma solidity ^0.8.0;

import "@forge-std/Test.sol";

contract Config {
    address public test = 0xcBa28b38103307Ec8dA98377ffF9816C164f9AFa;
}

contract TestSetup is Config, Test {
    function testWtf() public {
        uint256 snapshotId = vm.snapshot();

        vm.prank(test);

        vm.revertTo(snapshotId);
    }
}
```

- `forge-std` is at the latest commit: `ea1c1f4022f6a7924887106caa64499317295493`

# Findings

It seems to be a very specific case, because the test passes as soon as:
- the order of inheritance is swapped
- the `test` address is moved to the `TestSetup` contract
- the `test` address is `address(1)`, `address(2)`, ...
- any of the line of the body of `testWtf` is commented out

The test fails even if a call is performed on behalf of the pranked address `test`, right after `vm.prank`

**Comment by MerlinEgalite** [comment]
Nice bug ser

**Comment by mds1** [comment]
@mattsse, potentially related to https://github.com/foundry-rs/foundry/issues/3055#issuecomment-1328198508 and https://github.com/foundry-rs/forge-std/pull/241?

**Comment by mattsse** [comment]
thanks, will fix next.

**Comment by mds1** [comment]
@mattsse This still appears to be an issue—seems something is broken with the snapshot/revert functionality. Giving this high priority issue to me since it causes in erroneous test results

**Comment by ZeroEkkusu** [comment]
Hi, @Evalir.

I've seen that you've been trying to solve this issue, so I wanted to clarify a few things, in case it helps you.

I haven't checked the codebase, but it seems that before reverting the state, the thirty first byte of the zeroth slot of the testing contract is checked for a non-zero value.

If that is really the case, I suggest you check the slot at the Keccak-256 hash of the word `"failed"` at the VM address **first**, to see if the value there is one (and it will be).

That is because placing a contract with a state variable before `DSTest` in the inheritance chain causes the storage order to shift, meaning the `_failed` flag won't be the second state variable anymore, that is, its value won't be the byte that's being checked.
