### ISSUE TITLE
`forge test --debug` hangs on large-ish memory expansion

### ISSUE THREAD

**Issue by karmacoma-eth** [foundry-rs/foundry#3805]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f6361e6 2022-12-01T15:20:08.643454Z)

### What command(s) is the bug in?

forge test --debug testCheckMem

### Operating System

macOS (Intel)

### Describe the bug

Using the following test:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";

contract MemTest is Test {
    function setUp() public view {}

    function testCheckMem() public {
        uint256 _ptr = 1e6;
        uint256 val;
        assembly {
            mstore(_ptr, 1)
            val := mload(_ptr)
        }

        assertEq(val, 1);
    }
}
```

Run `forge test --debug testCheckMem`, then `G` to go to the end of the execution.

The `forge` process now stays stuck on 100% for 5+ minutes, even without further interactions with the debugger.

**Comment by karmacoma-eth** [comment]
A process sample suggests that forge is continuously allocating and moving memory with plenty of calls such as 

`_malloc_zone_malloc  (in libsystem_malloc.dylib) `
`_platform_memmove$VARIANT$Haswell  (in libsystem_platform.dylib)`

**Comment by mattsse** [comment]
@brockelmore any ideas or suggestions where to start debugging this?

**Comment by brockelmore** [comment]
Yeah so the TUI is very poorly designed and is 99% tech debt from getting a basic MVP (but its a relatively low usage feature so it never got much love).

My guess is that given we draw the page every 200ms, there is a decent chance we are allocating a ton of stuff each time. I am gonna profile it and post it here...

<img width="1719" alt="Screen Shot 2022-12-01 at 2 22 55 PM" src="https://user-images.githubusercontent.com/31553173/205171683-53e8f309-15bc-4c0e-972a-2802df21cb7f.png">

As I suspected, we do a *ton* of allocations due to strings and building up the TUI. So converting things to `&str`, `&'static str`, etc should help a lot

**Comment by gakonst** [comment]
@brockelmore should we add a 1-line doc on the README on how to generate flamegraphs?

**Comment by brockelmore** [comment]
> @brockelmore should we add a 1-line doc on the README on how to generate flamegraphs and in which platforms it works / doesnt (i haven't tried generating one in a couple months, but mac's lack of pprof made that not super easy)

I believe it should work on macos via dtrace (the above was ran on macos w/o anything besides `cargo flamegraph`). just have to run the tracer as root. 

`sudo cargo flamegraph --manifest-path ./path/to/foundry/Cargo.toml --bin <package> -- <[OPTIONS]>`
