### ISSUE TITLE
Cannot verify contracts with blacksmith and `forge script`

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#3872]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e9f274d 2022-12-11T00:04:59.790449Z)

### What command(s) is the bug in?

script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Trying out [blacksmith](https://github.com/blacksmith-eth/blacksmith), the tutorial suggests using `forge create`, which works. But verification with `forge script` fails silently.

To reproduce:
1. Run a blacksmith and an anvil server
2. `forge init test_verify_fail && cd test_verify_fail`
3. Modify `CounterScript` to deploy the `Counter` contract
4. `forge script CounterScript --verify --unlocked --sender 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 --rpc-url http://localhost:8545 --verifier-url http://localhost:3000/api/verify --etherscan-api-key blacksmith --broadcast`
5. The tx is broadcast but no verification occurs.

Note that the following does verify correctly: `forge create src/Counter.sol:Counter --verify --unlocked --from 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 --rpc-url http://localhost:8545 --verifier-url http://localhost:3000/api/verify --etherscan-api-key blacksmith`

**Comment by unholypanda** [comment]
To provide some additional context here–[blacksmith](https://github.com/blacksmith-eth/blacksmith) relies on the `--verifier-url` flag of `forge create` in order to provide a custom route (e.g. `http://localhost:3000/api/verify`) that accepts the contract source code, compiles it, and stores the ABI (which is used to render contract inputs in the application).

At a cursory glance of the `forge script` code, it seems that `clap` accepts all of the `VerifierArgs` defined in `cli/src/cmd/forge/verify/mod.rs`, but the `verifier_url` doesn't seem to be used by `forge script` like it is when verifying with `forge create`.

I suspect that this isn't just an issue with Blacksmith, but that `forge script` doesn't fully support custom verifier urls.

Also, I believe the label here should be updated to `Cmd-forge-script`, and `Cmd-forge-create` should be removed.

**Comment by jongregis** [comment]
I believe I may have found a workaround for this. While trying to write some custom logic to get this to work with foundry scripting I found that if you run anvil and fork mainnet and then run your script command on that forked network it seems to verify successfully. As a reference here is the command with flags.

`anvil --fork-url $MAINNET_RPC`

`forge script script/Test.s.sol:TestScript --fork-url http://localhost:8545 --verifier-url http://localhost:3000/api/verify --etherscan-api-key blacksmith --broadcast --verify -vvvv`

The UI does seem to work as well but havent done a lot of testing.

**Comment by mattsse** [comment]
> cli/src/cmd/forge/verify/mod.rs, but the verifier_url doesn't seem to be used by forge script

thanks for this.
I'll start with fixing this asap and then see what else needs fixing.

sorry for the delay everyone.
