### ISSUE TITLE
Error message tell you if it's an integer overflow OR underflow error

### ISSUE THREAD

**Issue by jhweintraub** [foundry-rs/foundry#4059]
### Component

Forge

### Describe the feature you would like

When an arithmetic operation occurs outside of an unchecked block the system will revert due to an arithmetic error ```[FAIL. Reason: Arithmetic over/underflow]```. This can be due to either a subtraction underflowing zero or an operation overflowing the maximum integer overflowing the maximum int value allocated. I would like the error message to be slightly more informative, telling me if the issue was due to an integer overflowing or if it was due to an integer underflowing. This would make identifying the location of the bug as well as the reason much simpler. It would also be helpful if the error message could include data such as the values that caused the error. For example, "Integer underflowed, a - b" and then showing what the inputs to the opcode were similar to how a failed assertion displays the information.

**Comment by andyrobert3** [comment]
@mattsse 

Any directions are welcome, some questions before I go deeper into this: 
1. Does the compiler provide the relevant warnings to differentiate between overflow & underflow?
2. If so, where in the repository are the different errors thrown and handled?

**Comment by andyrobert3** [comment]
@Evalir any thoughts here

**Comment by mds1** [comment]
I don't think this is going to be easy. Solidity provides a single [panic code](https://docs.soliditylang.org/en/latest/control-structures.html#panic-via-assert-and-error-via-require), 0x11, to indicate both overflow and underflow. Therefore you'll have to use source maps to map bytecode locations back to source code locations and look at the source code to determine the specific error. This is basically how coverage works. And if you're going to do that, you may as well generalize this to instead print the line number that triggered any revert, instead of only handling the overflow case

**Comment by andyrobert3** [comment]
looks difficult :(

i don't think i have the technical capability to do this for now, passing it to anyone who is interested in taking over

I don't really understand how to use source maps to map bytecode to source code :(

**Comment by andyrobert3** [comment]
@Evalir let's remove the `good-first-issue` flag here then

**Comment by Evalir** [comment]
Yeah agreed with @mds1 here—don't think this is going to be an easy one. Also, as this would be a huge undertaking, I don't think it's worth even keeping this issue open, but rather fill a separate issue for the larger generalization of the problem (which I don't think we plan on doing for the foreseeable future).
