### ISSUE TITLE
Forge filters should be applied before compilation  

### ISSUE THREAD

**Issue by MalfurionWhitehat** [foundry-rs/foundry#4098]
### Component

Forge

### Describe the feature you would like

I am not certain of this, but I believe that test filters (when running `forge test --match-test XXX`) are applied AFTER forge tries to everything, even files that are not touched by the test XXX. 

This is not ideal when testing only one behavior of a large codebase. 

You might want to add `console.log` at specific points, and only test a very specific flow, but since all files impacted by the change are compiled before applying test filters, small changes may take a long time to run.

**Comment by mattsse** [comment]
this is actually supported via the `sparse_mode` setting:

https://book.getfoundry.sh/reference/forge/forge-build?sparse-mode-experimental#sparse-mode-experimental

it's still marked as experimental because this is a bit more tricky than regular compile. It should work, but there could still be some bugs.

**Comment by MalfurionWhitehat** [comment]
Thanks, I'll close this for now.
