### ISSUE TITLE
feat(cast): like "wallet new" but for mnemonics

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4208]
### Component

Cast

### Describe the feature you would like

It would be handy to have a command like `wallet new` but for BIP39 mnemonics, e.g.

```bash
cast mnemonic new
```

**Comment by m0ham3dx** [comment]
If no one picks this , I will give it a shot , my knowledge of rust is limited to making CLI that display blinking lewd messages at the moment , hence will need huge amounts of guidance ( read being disturbed incessantly)

**Comment by rkrasiuk** [comment]
@m0ham3dx go for it! you can start by opening a draft and we will advise/comment on the direction of the PR

**Comment by m0ham3dx** [comment]
> @m0ham3dx go for it! you can start by opening a draft and we will advise/comment on the direction of the PR

Thanks for the vote of confidence. Plan of action  is
1. Investigate how [`ethers.js`](https://github.com/ethers-io/ethers.js) & [`Crypto-Wallet CLI`](https://www.npmjs.com/package/@yerofey/cryptowallet-cli) code generates mnemonics then see how to refactor in Rust
2. Understand which files I need to inject code in the repo for it to execute. 
3. Will open _draftpr_ in some time as advised .

**Comment by m0ham3dx** [comment]
@rkrasiuk 

# Preliminary Investigation 

In order to determine which files contain the logic,  So far I was able to determine that the `cast wallet commands` are [`HERE`](https://github.com/foundry-rs/foundry/blob/master/cli/src/cmd/cast/wallet/mod.rs#L20)  defined in the enum `pub enum WalletSubcommands` ,  and its `implementation` is [`HERE`](https://github.com/foundry-rs/foundry/blob/master/cli/src/cmd/cast/wallet/mod.rs#L77) 

## Testing Injected Code

So for testing I added new field:
![image](https://user-images.githubusercontent.com/82266083/216146586-73aeb138-1e88-4758-8aae-4360d094d0be.png)

And a dummy implementation 
![image](https://user-images.githubusercontent.com/82266083/216149966-875c33d5-b1ec-442a-afc8-e40236445937.png)

## Running `cargo build `  

![image](https://user-images.githubusercontent.com/82266083/216150338-28c26874-ea99-4ffd-9864-97a38aa45715.png)

![image](https://user-images.githubusercontent.com/82266083/216150559-7fe4f170-4200-4819-b967-4f3a70440cfc.png)

> What other files are involved in the implementation of a new cast command ? I also found the a [`bip39`](https://crates.io/crates/bip39) , maybe there are some more newer ones which I might test out. Do let me know ur thoughts

**Comment by m0ham3dx** [comment]
Already being worked on  #4128  - will not proceed with this.

**Comment by L0GYKAL** [comment]
It has been stopped so if you'd like to continue and release your version it would be great.
The doc is deprecated, I created an issue https://github.com/foundry-rs/book/issues/1062

**Comment by mattsse** [comment]
we have this now:

```
cast wallet new-mnemonic --help                                                                                 
Generates a random BIP39 mnemonic phrase

Usage: cast wallet new-mnemonic [OPTIONS]

Options:
  -w, --words <WORDS>        Number of words for the mnemonic [default: 12]
  -a, --accounts <ACCOUNTS>  Number of accounts to display [default: 1]
```

```
cast wallet nm -w 24                                                                                            
Successfully generated a new mnemonic.
Phrase:
guilt transfer spatial bargain quick hub case slender aware insect draw float game essence elevator sniff exact turtle breeze fly grief gauge erode grab

Accounts:
- Account 0:
Address:     0x1Df9CE84bc1eAD115194ff1696b7dd3dc94d01Af
Private key: 0x52de67965988ee6a370128b50fba359c9e0e053258b90b5cbf810ff9f6c70e27
```
