### ISSUE TITLE
Incorrectly formatted invariant tests don't run and don't output an error

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/foundry#4331]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (25fcfef 2023-02-11T00:18:51.728589Z)

### What command(s) is the bug in?

forge

### Operating System

macOS (Intel)

### Describe the bug

1. Setup a default foundry project
```
forge init
```

2. Add this invariant test to `Counter.t.sol`

```javascript
    function invariant_sample() public {
        assert(counter.number() >= 0);
    }
```
3. Remove `setUp` function and tests from `Counter.t.sol`

The invariant test should remain

4. Run invariant test
```
forge test -m invariant_sample
```

You'll see it compile, then not run any tests or invariants. I can't seem to figure out how to undo whatever weird state it's in. Deleting the cache and artifacts doesn't help.

**Comment by PatrickAlphaC** [comment]
Ah... No I think I got it.

```
targetArtifact("LiquidSDIndexPool");
```

When doing these cheats fail, it won't notify you that it failed and just skip running tests.

**Comment by PatrickAlphaC** [comment]
I can't reproduce. But I can't figure out why it randomly doesn't "work" for me.

**Comment by PatrickAlphaC** [comment]
I have updated the original description to a reproducible error.

**Comment by zerosnacks** [comment]
Hi @PatrickAlphaC thanks for the report, sorry for the delay

I'm unable to reproduce it against the latest Foundry

With `forge test --mt invariant_sample`

Not including a `setUp` now yields: `[FAIL. Reason: failed to set up invariant testing environment: No contracts to fuzz.] invariant_sample() (runs: 0, calls: 0, reverts: 0)`

Including a setup, removing the other tests yields:

```
Ran 1 test for test/Counter.t.sol:CounterTest
[PASS] invariant_sample() (runs: 256, calls: 128000, reverts: 883)
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 9.80s (9.80s CPU time)

Ran 1 test suite in 9.80s (9.80s CPU time): 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

There have been quite a few updates to invariants since then and it has likely been fixed or is impossible to reproduce given the now thrown error

Feel free to re-open if you are able to reproduce the issue

**Comment by PatrickAlphaC** [comment]
Yep all good. Sounds like whatever updates were made fixed it. Thanks!
