### ISSUE TITLE
Unable to get selector of an imported smartcontract

### ISSUE THREAD

**Issue by Fabien-Morrow** [foundry-rs/foundry#4382]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31f945c 2023-01-29T15:10:24.6423003Z)

### What command(s) is the bug in?

forge build

### Operating System

Windows

### Describe the bug

I encounter an error when trying to access a function's selector.

- download [this mwe](https://github.com/Fabien-Morrow/foundry-mwe/tree/master/src)
- forge build
-> 
`Error: 
Compiler run failed
error[9582]: TypeError: Member "transfer" not found or not visible after argument-dependent lookup in type(contract DamnValuableToken).
  --> src/Mwe.sol:10:13:
     |
10 |             DamnValuableToken.transfer.selector
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
`
Or just look at this, the mwe is VERY simple.
![image](https://user-images.githubusercontent.com/91032561/219730698-1e51fed1-bf78-4822-905c-e3b2f45cf97a.png)

I'm not a good solidity developer, but I don't get it why it doesn't work. After hours spended on this, I might consider a bug in foundry. Sorry if it wasn't the case, but tell me what I'm doing wrong :)

Thank you for this amazing product guys :)

**Comment by 0xSchellen** [comment]
IMO this is not a Foundry error.

Probably this is a solidity syntax error due to :

1 - The DamnValuableToken address is not declared and initialized: 

2 - The constructor code syntax is incomplete and has missing parameters
abi.encodeWithSelector(token.transfer.selector, to, value)

3 - There's lots of interesting code about DVT challenges in this repo made with foundry.
(and also in lots of other sources).

https://github.com/nicolasgarcia214/damn-vulnerable-defi-foundry

**Comment by DaniPopes** [comment]
The transfer function is declared in `ERC20`, so even if you inherit it you still have to refer to it as `ERC20.transfer`

**Comment by Fabien-Morrow** [comment]
Ok it seems definitively not a bug, I can't suppress this so I'll just close it. Thank you guys
