### ISSUE TITLE
Trace folding in vscode

### ISSUE THREAD

**Issue by tonisives** [foundry-rs/foundry#4423]
### Component

Forge

### Trace folding

Format the traces in a format that vscode automatically recognises as collapsable. This way I could fold setup trace and only see the test function trace when I copy the trace to a file and open in vscode.

One option would be to use tabs instead of `│   │` Vscode folds tabs automatically, but not the current `│   │` format. 

![out](https://user-images.githubusercontent.com/1083534/221327741-7c1e544a-cb5d-4dd6-837e-0e416d375dbe.gif)

PS: It's easy to replace  `│   │` with tabs manually, so this issue can be a reference for other people who look for this feature.

**Comment by mds1** [comment]
Just switching to tabs would make traces hard to read, so I don't think we should do this, especially since like you said it's easy to make the change manually when needed.

As part of #4440 we'd like to makes traces interactive, which includes being able to collapse them, so I'm going to close this in favor of that 🙂

**Comment by aodhgan** [comment]
+1 for this feature
