### ISSUE TITLE
feat(forge): stack traces grab contracts from etherscan when forking 

### ISSUE THREAD

**Issue by brockelmore** [foundry-rs/foundry#447]
When forking, we really should grab the etherscan contracts if the user has provided an etherscan api key

potential logic:
1. execute test
2. check if forked evm
3. identify known contracts for trace
4. check unidentified contract addresses on etherscan
5. compile contracts from etherscan
6. update traces with new known contracts

**Comment by ncitron** [comment]
If nobody has started this I can. I'm a big user of forked tests and this would be a huge UX improvement.

I'm thinking the best way to tackle this would be to change the definition of `CallTraceArea`'s `update_identified` function to take a flag to specify if this is a fork test (which we can get by the presence of `self.evm_opts.fork_url` in `ContractRunner`). From there we just need to update `update_identified` to fetch the ABI from etherscan if it doesn't match the code of any known contracts. I'll also have to think about the best way to figure out what `Chain` to pass the ethers-etherscan `Client`, since we only have access to the chain id at this point (which is as far as I know cannot easily be converted to the `Chain` type). I could write a little lookup table but this would not be fully sufficient as it wouldn't differentiate between chains that use the same chain id as ethereum mainnet such as ETC.

Does this sound like a good plan?

**Comment by brockelmore** [comment]
Yes that sounds like a good plan

**Comment by onbjerg** [comment]
Closed in #1284
