### ISSUE TITLE
sepolia deploys fail (incorrect gas?)

### ISSUE THREAD

**Issue by d1onys1us** [foundry-rs/foundry#4483]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

If I try to deploy a simple Foo contract on Sepolia it fails due to "(code: -32000, message: insufficient funds for gas * price + value, data: None)". If i do the same on goerli, etc. it works fine. i have funds on sepolia as well. please let me know if i can provide more info.

**Comment by mds1** [comment]
Can you provide more info to reproduce? Sepolia deploys should work, it sounds like you may have accidentally specified the wrong deployer to one that has no funds. Alternatively, the cost to deploy on sepolia may be higher (either higher gas price, or more gas used due to e.g. interactions with other contracts), so you may not have had enough balance
