### ISSUE TITLE
Using deal for OUSD token

### ISSUE THREAD

**Issue by amatureApe** [foundry-rs/foundry#4595]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (06f7c9c 2023-03-18T00:16:11.192812Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

Calling ``deal`` when trying to mint OUSD (0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86 - mainnet) returns the following error below. 

``[FAIL. Reason: stdStorage find(StdStorage): Slot(s) not found. Counterexample: calldata=0x202da9aa0000000000000000000000000000000000000000000000000000000000000000, args=[0]]``
![Screenshot 2023-03-18 at 4 59 11 PM](https://user-images.githubusercontent.com/48165147/226146761-9f1dc200-4dc8-41c9-90b1-0d657cb69977.png)

**Comment by mds1** [comment]
The OUSD contract's `balanceOf` method dynamically computes the balance to return (like a rebase token), whereas the `deal` cheat only supports tokens that return `balanceOf` by reading a value directly form a storage slot, because `deal` works by changing the value in the `balanceOf` storage slot. As a result this token is not currently supported by forge-std, similar to https://github.com/foundry-rs/forge-std/issues/140

As a workaround you can find an OUSD whale from [etherscan](https://etherscan.io/token/0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86#balances), prank as that user, and transfer tokens to any address you need

(For future reference, `deal` for tokens is a forge-std cheat, not a native forge cheat, so this issue should be in the forge-std repo)
