### ISSUE TITLE
Improve accessibility for all EVM languages

### ISSUE THREAD

**Issue by ghost** [foundry-rs/foundry#46]
With the development and rise of EVM focused programming languages - besides Vyper and Solidity - like [Fe](https://github.com/ethereum/fe) and [Sway](https://sezna.github.io/EthCC-2021/) I think we should make it as easy as possible to make dapptools-rs accessible for these languages. 

I don't have enough knowledge at the moment to assess if this is already possible or how big the effort would be to make the integration as easy as possible for future languages.

**Comment by gakonst** [comment]
Thanks for flagging this. The test runner operates over compiled EVM bytecode and ABI, so we'd only need bindings to the compilers and calling them [instead of solc](https://github.com/gakonst/dapptools-rs/blob/e40621cbdfc1963995798cf78388dfe28914d3b7/dapp/src/multi_runner.rs#L43).

However, I do think we should be focusing on making the simple Solidity experience as great as possible, and we can think about other languages later.

**Comment by zerosnacks** [comment]
Marking this as completed due to the multi-lingual support having been added recently to https://github.com/foundry-rs/compilers/tree/main/crates/compilers/src/compilers

This lays the foundation for other languages to be added
