### ISSUE TITLE
`forge test` hangs on `invariant` testing

### ISSUE THREAD

**Issue by trojanMcAfee** [foundry-rs/foundry#4656]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (97f070f 2023-03-17T09:30:30.350509Z)

### Operating System

macOS (Intel)

### Describe the bug

When running any type of `invariant` testing, the terminal hangs after compiling the contracts: 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/59457858/228041268-9ad3cf2f-680c-4195-9b00-e656caa89929.png">

This is the function I'm calling:
```js
function invariant_getHello() public {
    assertTrue(true);
}
```

It hangs with either `forge test --match-test $FUNC --fork-url $ARB --fork-block-number $BLOCK -vvv` where $FUNC is `invariant_getHello` or with `forge test --match-test invariant --fork-url $ARB --fork-block-number $BLOCK -vvv`.

If I change the function name to `test_getHello`, the test runs and passes without issues, so the problem is in the `invariant` keyword:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/59457858/228042243-5039ca8e-f2de-4f33-a799-bf1365631a5a.png">

**Comment by cdgmachado0** [comment]
The bug is when passing the `--fork-url $ARB` flag. If I remove it, the test runs and passes.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/59457858/228047626-f7d786e9-d6a7-4d85-a346-3ac6bf6588b6.png">

**Comment by cdgmachado0** [comment]
Selecting the fork directly in the contract with `createSelectFork` doesn't solve the issue.

**Comment by mds1** [comment]
If you run with `RUST_LOG=forge=trace,foundry_evm=trace,ethers=trace forge test <rest of command>` you'll see this is just because it's making a lot of RPC requests since it's a fork test. If you pin to a block and use a fuzz seed, subsequent invocations will be much fast since responses will be cached. You can read more here: https://book.getfoundry.sh/forge/fork-testing

**Comment by cdgmachado0** [comment]
It didn't work @mds1 

As you can see on my screenshots, I was passing the flag `--fork-block-number $BLOCK` with 69254399 as `BLOCK`. 

I also tried removing the flag and setting the block directly in the contract with `vm.createSelectFork(vm.rpcUrl('arbitrum'), 69254399);`  while having my `.toml` file like:

```js
[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'

[rpc_endpoints]
arbitrum = "${ARBITRUM}"

[fuzz]
seed = 10
```

As you can see there, I specified a seed also.

**Comment by cdgmachado0** [comment]
I created #4662 since the problem is unresolved and I can't re-open this issue. 

Once the situation is resolved, I can close that other issue. :)

**Comment by cdgmachado0** [comment]
I think foundry is not properly caching any data. I'm doing `forge cache ls` and this is the output I get:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/59457858/228514654-efd72710-48fd-43d8-b29c-0d1c25a72004.png">

**Comment by cdgmachado0** [comment]
Don't think that it's a cache issue, which would explain why your solution didn't work @mds1 

I removed `cache_path = 'forge-cache'` from my .toml file so the cache would defaulted back to `~/.foundry/cache/arbitrum/69254399` (which it did), but the hangs still remains only for invariant tests.

**Comment by mds1** [comment]
One way you can try to verify that tests are not hanging, and are simply slow due to the RPC queries is as follows:

Modify your foundry config as follows:

```toml
[profile.default.fuzz]
seed = 1

[profile.default.invariant]
runs = 1
depth = 1
```

This specifies a seed for the random number generator, and makes the invariant tests only run a single run of depth 1. Now, run `forge test --fork-url $ARBITRUM_RPC_URL `. I ran `forge init`, and modified `Counter.t.sol` as follows:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import "../src/Counter.sol";

contract CounterTest is Test {
    Counter public counter;

    function setUp() public {
        counter = new Counter();
        counter.setNumber(0);
    }

    function invariant_example() public {
        assertTrue(true);
    }
}
```

With this configuration, it took 2.5s to run the test. Remember that you can modify the test command to be `RUST_LOG=forge=trace,foundry_evm=trace,ethers=trace forge test --fork-url $ARBITRUM_RPC_URL` to see what's happening under the hood so you can see if things are hanging vs. if there's just a lot of RPC requests happening.

However, it does seem that RPC caching is not being leveraged, as it does take ~2.5s each invocation, even if I specify a fuzz seed

**Comment by cdgmachado0** [comment]
Thanks for the reply :) @mds1 

And yeah, setting `runs = 1` makes the test run, and like you mentioned, with `RUST_LOC=....`, it shows the multiple RPC calls being made under the hood, but in the end, the test just sits there (aka it hangs), which is what matters since I'm trying to run an invariant test, and having only one run defeats the purpose. 

<img width="494" alt="image" src="https://user-images.githubusercontent.com/59457858/228575436-687f7412-21b1-4cf5-9534-7a5dbb2dabce.png">

I'm not sure I fully understood your last sentence, but it seems like you were able to reproduce my issue (?). 

In the end, what I'm trying to do is to run a invariant fuzzing campaign on an Arbitrum fork with a standard parameters. Is this a bug or do I have to make a change in my config in order to achieve this outcome?

**Comment by mds1** [comment]
> but in the end, the test just sits there (aka it hangs)

Can you clarify what you mean here? From what I can see it is running and making RPC requests, it's not stuck/hanging

> In the end, what I'm trying to do is to run a invariant fuzzing campaign on an Arbitrum fork with standard parameters. Is this a bug or do I have to make a change in my config in order to achieve this outcome?

Are you running your own node or using a service like e.g. Alchecmy/Infura? If the latter, it's very likely you'll get rate limited due to the number of RPC requests, which will make the tests execute very slowly. Unfortunately there's not much we can do here on the forge side. One solution is to allow forge to be initialized with a list of provider URLs and have it rotate providers with each call, but that might be a nontrivial change. If this is something you need I'd suggest opening a separate issue for this

> I'm not sure I fully understood your last sentence, but it seems like you were able to reproduce my issue (?).

I just meant that it seems the cache is not being used for invariant tests, because every run took ~2.5s, but I'd have expected subsequent runs to be only a few milliseconds thanks to using the cache. However, I had forgotten to pin a block, and with pinning + seed, RPC caching is working as expected (~2.5s for first run, a few millseconds for subsequent runs)

**Comment by cdgmachado0** [comment]
> Can you clarify what you mean here? From what I can see it is running and making RPC requests, it's not stuck/hanging

I can see that the RPC requests are being made when I run `forge test` with `RUST_LOG=....`, but if I run it without it, so I don't see under hood, which is what matters for me, the completion of the test per se (not the behaviour under the hood), it just sits in this screen forever. It doesn't complete the test. That's what I mean by "it hangs". 

<img width="284" alt="image" src="https://user-images.githubusercontent.com/59457858/228583574-efa419bd-15c4-41ff-b4df-812e94da9ab7.png">

Do you manage to actually complete a test with standard invariant-fuzzing parameters on a fork? 

> Are you running your own node or using a service like e.g. Alchecmy/Infura? If the latter, it's very likely you'll get rate limited due to the number of RPC requests, which will make the tests execute very slowly

I'm using RPC services (both Alchemy and Infura), but with other fuzzers like Echidna, running tests with forks work without issue, so it should work with Foundry also, no? Especially if you're mentioning that the RPC catching is not being leveraged, that I can't successfully run an invariant test on a fork, and have the evidence of the issue. @mds1 

Isn't this enough to qualify the issue as a bug?

**Comment by cdgmachado0** [comment]
I understand what you mean now. @mds1 

The "hang" that I'm experiencing is just forge doing the RPC requests. If I have set `runs` to like 100, it's going to feel like forever.

But still, there's a catching issue that foundry is not doing. That's the bug I'm mentioning should be considered no?

**Comment by mds1** [comment]
> it just sits in this screen forever. It doesn't complete the test. That's what I mean by "it hangs".

Got it. So it will complete *eventually*, just slowly, due to RPC queries. Something like https://github.com/foundry-rs/foundry/issues/585 would help make it clear that things are progressing and not actually hanging

> Do you manage to actually complete a test with standard invariant-fuzzing parameters on a fork?

If I run using alchemy on arbitrum, I have not waited long enough for it to complete. However if I use my local mainnet erigon node I get through an invariant run with the default settings (256 runs, depth of 15) in ~20 seconds

> Especially if you're mentioning that the RPC catching is not being leveraged,

Caching is being leveraged if you use a seed and pin to a block, I just forgot to pin to a block my initial test test

> I'm using RPC services (both Alchemy and Infura), but with other fuzzers like Echidna, running tests with forks work without issue, so it should work with Foundry also, no?

Maybe they just make fewer RPC requests somehow? They would have the same issue about being rate-limited, so I'm not sure what they'd do different. Maybe @mattsse has some insight here

**Comment by cdgmachado0** [comment]
> Caching is being leveraged if you use a seed and pin to a block, I just forgot to pin to a block my initial test test

I have a pinned block also, but the behaviour is the same.

```js
vm.createSelectFork(vm.rpcUrl('arbitrum'), 69254399)
```

But don't you think that the fact that I can't successfully complete one invariant test on a fork can be considered a bug?

I have `runs = 100` (which is not that much in what fuzzing concerns), and I still have the same test that I started 10 minutes ago running without producing any output. @mds1

**Comment by mattsse** [comment]
this has to do with how the sender fuzzing in combination with forking mode works

because we're using random callers which all need to be fetched via rpc first.

But I'm not sure if this is really necessary.
manually entering forking mode should get around this though, so

> vm.createSelectFork(vm.rpcUrl('arbitrum'), 69254399)

 should only fetch everything after entering the fork, if the test is not launched in forking mode

**Comment by cdgmachado0** [comment]
What does that mean exactly if I may ask? @mattsse 

I tried both ways, with `vm.createSelectFork(vm.rpcUrl('arbitrum'), 69254399)` in the code directly, and with `--fork-url $ARB --fork-block-number $BLOCK` as flags on the CLI, but with both the issue is still present.

Do I have to do something extra in order to get invariant tests to work?

**Comment by mds1** [comment]
> I guess technically it is correct when running in forking mode that the sender account should be fetched via rpc, but I'm not sure if this is useful here.

What are we actually fetching from the sender up front? vs. just fetching e.g. nonce or something lazily as needed

**Comment by mattsse** [comment]
the account consists of:
* code
* balance
* nonce

that's what we need to create the `Account` object the `evm` needs.

this is actually loaded during evm execution, evm needs to check balance, nonce

**Comment by cdgmachado0** [comment]
This example doesn't work for me unfortunately @mattsse 

I need to use the fork in `setUp()` since I'm doing something with arbitrum's state there.

I tried creating several forks in the setup, end that function up with a different fork, and then select arbitrum fork in my invariant test, but the test still hangs

**Comment by cdgmachado0** [comment]
Any other possible solution that I could try?

**Comment by cdgmachado0** [comment]
How do I do that? Sorry for the ignorant question.

**Comment by mds1** [comment]
> so I suggest we insert an empty sender account into the database first?

agreed it's not too useful, I think it'd be better to just change the default sender approach to the one suggested in https://github.com/foundry-rs/foundry/issues/4656#issuecomment-1489249915, I don't see much value in pulling it from the dict / generating a purely random address

**Comment by cdgmachado0** [comment]
Don't forget about me please. 

I really really want to get invariant testing to work, and I've been struggling for like a week trying to solve it. 

Or is it a bug and there's no workaround I can do to get it to work and a patch from you guys is the only solution? @mds1 @mattsse

**Comment by mattsse** [comment]
> Don't forget about me please.
> 
> I really really want to get invariant testing to work, and I've been struggling for like a week trying to solve it.
> 
> Or is it a bug and there's no workaround I can do to get it to work and a patch from you guys is the only solution? @mds1 @mattsse

sorry about the inconvenience 

I guess we just haven't tested this with forking mode properly. Thanks for flagging this.

@mds1 I think both fixes would be pretty simple

> Perhaps instead, if senders is empty, we change it to 5-10 default random senders to use for invariant testing?

this makes sense, this way we still have the actual accounts

**Comment by mds1** [comment]
@cdgmachado0 If you want a workaround in the meantime just use `targetSenders()` to hardcode a list of 1 or more senders, that way random senders are not generated. You can read more in the docs: https://book.getfoundry.sh/forge/invariant-testing#invariant-test-helper-functions

**Comment by mds1** [comment]
> @mds1 I think both fixes would be pretty simple

Sorry just to clarify, this is just a single solution that would behave as follows:
- Define 5-10 default random senders to use for invariant testing?
- Derive those hardcoded addresses as `address(uint160(uint256(keccak256("invariant sender i"))))` for `i` in the range of `1..=10` (or however many senders we generate)
- Since no one will have the private key for these addresses, we know, code, balance, and nonce will always be zero
- We can consider also adding a flag to switch back to the current behavior of "If `senders` is empty, then it's either a random address (10%) or from the dictionary (90%)." IMO we can leave this out for now and only add it back in if requested, or if @joshieDo has a reason for the current approach that we're not thinking of. I know @lucas-manuel usually uses `targetSenders` so I think he'd be onboard with this change and not need a flag to bring back old behavior

**Comment by cdgmachado0** [comment]
Just to let you know guys, `targetSender` didn't work as a workaround. It still hangs.

Or were you able to get a test going? If you did, let me know and I'll check if the problem is me.

**Comment by lucas-manuel** [comment]
Hi @cdgmachado0!

Just caught up on all of this, for the example outlined it seems like having a constant targetSender should solve the issue. What is in your `setUp` function?

**Comment by cdgmachado0** [comment]
Hi @lucas-manuel 

It's something like this:
```js

address bob = makeAddr('bob');
address alice = makeAddr('alice');
address ray = makeAddr('ray');

function setUp() {
   vm.createSelectFork(vm.rpcUrl('arbitrum'), 69254399);

   //random init code that creates some contracts 

   vm.prank(deployer);
   OZL.diamondCut(cuts, address(initUpgrade), data); //modifies state in the fork 

   deal(address(USDC), bob, 5000 * 10 ** 6);

   targetSender(alice);
   targetSender(ray);

   _setLabels(); //sets the labels of the contracts for the trade
}
```

**Comment by mds1** [comment]
@cdgmachado0 Can you share a minimal repo that we can clone along with the command you're using to run the tests? It would make it much easier to reproduce

**Comment by cdgmachado0** [comment]
There you go guys: https://github.com/cdgmachado0/forReview

The command I'm using is `forge test -m invariant_myTest`, targeting this function in the file `EnergyETHFacet.t.sol`:
```js
function invariant_myTest() public {
    assertTrue(true);
}
```

Running `forge test -m test_getPrice`, which targets this function, runs without issues:
```js
function test_getPrice() public {
     uint price = energyFacet.getPrice();
     assertTrue(price > 0);
}
```

Let me know if you anything else @mds1 @lucas-manuel @mattsse

**Comment by cdgmachado0** [comment]
There's an `env` file there already with an Arbitrum RPC URL so you just need to run the `forge` command.

**Comment by mds1** [comment]
It does seem like we're making too many RPC requests. You'll notice that the alice and ray addresses are:
```
alice 0x328809Bc894f92807417D2dAD6b7C998c1aFdac6
ray 0x0Bf6534a8459BC34CF6e86A3902F68333cF0991D
```

And if I run `RUST_LOG=trace forge test -m invariant_myTest` there are a lot of RPC requests to get transaction count and storage at those addresses. So my guess is that after each call, since we're forking, we don't know if some forked contract changed the state of those addresses, and therefore we have to query for updated state each time? @mattsse 

But we know the transaction count couldn't have changed, so we should be able to drop those requests. Getting storage seems reasonable though and I'm not sure of a way around that. @mattsse lmk what you think

**Comment by mattsse** [comment]
> It does seem like we're making too many RPC requests.

yes, because we're in forking mode context at this point which happens if launched in forking mode or entered during setup

this is a bit horrible, I guess the best solution would be to not fetch the caller from remote and instead use an empty account (so it bypasses the rpc requests for the caller account)

**Comment by cdgmachado0** [comment]
I think I'm using an empty account there. I'm initializing `alice` with `address alice = makeAddr('alice');` , and then targeting her with `targetSender(alice);`.

No further actions are being done. Or by "empty account", do you mean other thing? @mattsse

**Comment by mattsse** [comment]
ah there's targetSender.
i'm not familiar with targetSender works,
will check

**Comment by cdgmachado0** [comment]
Any updates or ideas that I could do to get this to work? @mattsse 

I appreciate a lot the effort that you guys are doing btw. Much respect!

**Comment by cdgmachado0** [comment]
Found another section where this bug happens (in `stdstore`). 

Opened issue #4735

**Comment by thedavidmeister** [comment]
https://github.com/rainprotocol/rain.orderbook/actions/runs/5454746019/jobs/9925276209

I found a single invariant with no fork times out CI, it hangs locally too.

This happens as long as i have `-vvv` specified. Setting `-vv` or `-v` or nothing allows the tests to complete.

However, it _also _ seems to cause the invariant test to not be run at all, I don't see anything in my test output related to invariant tests.

**Comment by 0xMySt1c** [comment]
I'm having similar difficulties when running invariants in CI only.
Local seems to work.
The runs at 500 will fail, but pass at 200.

**Comment by thedavidmeister** [comment]
not sure if related but i'm seeing forge test hang for 6 hours before being killed on CI

hangs locally too https://github.com/rainprotocol/rain.interpreter/actions/runs/5778610955/job/15660019345

**Comment by stobiewan** [comment]
I have similar hangs in a similar situation. Invariant tests with a forked network, pranking actors and deal()ing tokens. When the hang occurs it happens quickly and one core will go to 100%. I've checked on alchemy, this is not related to RPC calls, they're few and fine. Using RUST_LOG=foundry_evm=trace forge test... I see an infinite loop of this sort of stuff being repeated very quickly. Seems like it may be related to switching pranks between accounts which have been forced to have token balances with deal(), that's happening both in my case and it sounds like it is in OPs too. This happens randomly about a quarter of the time when tests could be expected to be the same, locked seed and locked fork block.

```
2023-09-19T09:41:04.361959Z TRACE foundry_evm::executor::backend: setting precompile id
2023-09-19T09:41:04.361962Z TRACE foundry_evm::executor::backend: setting test account acc=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.361967Z TRACE foundry_evm::executor::backend: remove persistent account account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.361971Z TRACE foundry_evm::executor::backend: revoke cheatcode access account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.361975Z TRACE foundry_evm::executor::backend: add persistent account account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.361978Z TRACE foundry_evm::executor::backend: allow cheatcode access account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.362116Z TRACE foundry_evm::executor::inspector::cheatcodes: Rolling back deals deals=0
2023-09-19T09:41:04.362122Z TRACE foundry_evm::executor::inspector::cheatcodes: Rolling back deals deals=0
2023-09-19T09:41:04.362126Z TRACE foundry_evm::executor::inspector::cheatcodes: Rolling back deals deals=0
2023-09-19T09:41:04.362129Z TRACE foundry_evm::executor::inspector::cheatcodes: Rolling back deals deals=0
2023-09-19T09:41:04.362353Z TRACE foundry_evm::executor::backend: setting caller account acc=0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
2023-09-19T09:41:04.362357Z TRACE foundry_evm::executor::backend: allow cheatcode access account=0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
2023-09-19T09:41:04.362359Z TRACE foundry_evm::executor::backend: setting precompile id
2023-09-19T09:41:04.362362Z TRACE foundry_evm::executor::backend: setting test account acc=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.362367Z TRACE foundry_evm::executor::backend: remove persistent account account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.362372Z TRACE foundry_evm::executor::backend: revoke cheatcode access account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.362376Z TRACE foundry_evm::executor::backend: add persistent account account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.362379Z TRACE foundry_evm::executor::backend: allow cheatcode access account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.362992Z TRACE foundry_evm::executor::backend: setting caller account acc=0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
2023-09-19T09:41:04.362997Z TRACE foundry_evm::executor::backend: allow cheatcode access account=0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
2023-09-19T09:41:04.362999Z TRACE foundry_evm::executor::backend: setting precompile id
2023-09-19T09:41:04.363003Z TRACE foundry_evm::executor::backend: setting test account acc=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363007Z TRACE foundry_evm::executor::backend: remove persistent account account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363011Z TRACE foundry_evm::executor::backend: revoke cheatcode access account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363016Z TRACE foundry_evm::executor::backend: add persistent account account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363018Z TRACE foundry_evm::executor::backend: allow cheatcode access account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363600Z TRACE foundry_evm::executor::backend: setting caller account acc=0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
2023-09-19T09:41:04.363604Z TRACE foundry_evm::executor::backend: allow cheatcode access account=0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
2023-09-19T09:41:04.363607Z TRACE foundry_evm::executor::backend: setting precompile id
2023-09-19T09:41:04.363610Z TRACE foundry_evm::executor::backend: setting test account acc=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363614Z TRACE foundry_evm::executor::backend: remove persistent account account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363618Z TRACE foundry_evm::executor::backend: revoke cheatcode access account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363624Z TRACE foundry_evm::executor::backend: add persistent account account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363626Z TRACE foundry_evm::executor::backend: allow cheatcode access account=0xa0cb889707d426a7a386870a03bc70d1b0697598
2023-09-19T09:41:04.363851Z TRACE foundry_evm::executor::inspector::cheatcodes: Rolling back deals deals=0
2023-09-19T09:41:04.363856Z TRACE foundry_evm::executor::inspector::cheatcodes: Rolling back deals deals=0
2023-09-19T09:41:04.363860Z TRACE foundry_evm::executor::inspector::cheatcodes: Rolling back deals deals=0
2023-09-19T09:41:04.364118Z TRACE foundry_evm::executor::backend: setting caller account acc=0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
2023-09-19T09:41:04.364124Z TRACE foundry_evm::executor::backend: allow cheatcode access account=0x7e5f4552091a69125d5dfcb7b8c2659029395bdf

```

**Comment by stobiewan** [comment]
Have a similar issue. Not using a forked network. Sometimes invariant tests never terminate, it may be the same thing. You can check by writing lines to a file in the test and see it keeps calling functions and testing invariant forever as if depth = infinity, or depth counter fails to increment after some point

**Comment by Nikhil8400** [comment]
I was also facing the same problem, but I used a VPN, and my problem was solved

**Comment by grandizzy** [comment]
https://github.com/foundry-rs/foundry/pull/7756 should help, can you guys pls recheck? tested also on a project that had call_override true and was hanging and is no longer reproducible

**Comment by grandizzy** [comment]
I retried with project from https://github.com/foundry-rs/foundry/issues/4656#issuecomment-1497485416 and wasn't able to reproduce, test completed properly

![image](https://github.com/foundry-rs/foundry/assets/38490174/40246d1f-08c6-4e99-af53-5b5053901aed)

also traces show that fork properly initialized and test preformed OK

![image](https://github.com/foundry-rs/foundry/assets/38490174/555671f7-7182-4a9e-b6eb-7488eb9dd096)

I am going to close this ticket for now, please reopen if you hit it again. thank you
