### ISSUE TITLE
`forge build` exclude file 

### ISSUE THREAD

**Issue by jinhoonbang** [foundry-rs/foundry#4709]
### Component

Forge

### Describe the feature you would like

forge allows tests to be excluded through configuration using `no_match_test`. It would be great if we can have similar functionality for excluding files during `forge build`

Our use case is that we have a folder with solidity files and we use both hardhat and forge in that folder. Some files are only needed for hardhat build and tests.

**Comment by mattsse** [comment]
It would be possible with some limitations but it is a bit harder to do, because now we'd need to not only resolve the project graph but also decide what to do with branches that depend on the excluded file.

for example, if A.sol depends on Excluded.sol, how should we also exclude A or ignore ignore the `--exclude`?
