### ISSUE TITLE
Failing invariant sequence is not printed

### ISSUE THREAD

**Issue by hasanza** [foundry-rs/foundry#4754]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (04ce078 2023-04-17T00:04:57.209269000Z)

### What command(s) is the bug in?

forge test 

### Operating System

macOS (Apple Silicon)

### Describe the bug

Issue: when I run the invariant test, it does not print the [Sequence] of the failed invariant test. 

This is the output I get:
![image](https://user-images.githubusercontent.com/49759922/232480783-910b44fe-5400-44fc-af20-6720cbc52276.png)

It should also print the `[Sequence]` like in the example below:
![image](https://user-images.githubusercontent.com/49759922/232480870-f5a21389-0ab7-4553-93fb-80f54429b556.png)

As a result, I am not able to know which call sequence and function args broke the invariant.

I have updated the binaries, tried different configs etc. but nothing is working. I think it is a small and easy to fix issue but I have not been able to find help on my search, which is why as a last resort, I am posting here. Currently, my config file is empty (default).

Ref: 
- The example snippet is from the guide on invariant testing: https://mirror.xyz/horsefacts.eth/Jex2YVaO65dda6zEyfM_-DXlXhOWCAoSpOx5PLocYgw

**Comment by mds1** [comment]
If no sequence is printed, it means the invariant failed before any calls by the fuzzer were executed. The invariant is checked at the very beginning (immediately after setup runs, before any fuzzer calls are made), so if it fails at that point there is no sequence to print

**Comment by hasanza** [comment]
Ah I see. Thanks for the quick response!

If I may, I want to confirm one more thing from you:

Is it possible to use `vm.prank` to impersonate a mainnet account in a fork test? I am trying to use the existing USDT balance of a USDT holder using vm.prank in a fork test but for some reason, any non-view call to the USDT contract fails. Is this the correct way to impersonate? Any help with this is highly appreciated as I cannot find a definitive answer to this.

The test I am running:
```
    function test_approve() public {
        address actualUser = address(0x0162Cd2BA40E23378Bf0FD41f919E1be075f025F);
        vm.selectFork(mainnetFork);
        vm.prank(actualUser);
        // This reverts. 
        IERC20(USDTAddr).approve(address(instance), 50);
    }
```
  
  The output :
    
![image](https://user-images.githubusercontent.com/49759922/232772334-fecf1d9e-e21b-4a36-99bc-16bd80d4b0cc.png)

**Comment by mds1** [comment]
This revert is likely due to an approval quirk in USDT—there's a [race condition](https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729) with ERC-20 approvals, that in practice doesn't matter because most people approve contracts, not individuals. But USDT tries to mitigate this, so if you try to set the allowance to 50, and the existing allowance is already nonzero, UDST will revert. You must first set the allowance to zero, then set it to the new allowance. You can check out the USDT contract's approve method to see specifics.

**Comment by hasanza** [comment]
> This revert is likely due to an approval quirk in USDT—there's a [race condition](https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729) with ERC-20 approvals, that in practice doesn't matter because most people approve contracts, not individuals. But USDT tries to mitigate this, so if you try to set the allowance to 50, and the existing allowance is already nonzero, UDST will revert. You must first set the allowance to zero, then set it to the new allowance. You can check out the USDT contract's approve method to see specifics.

Interesting, will def check it out. But in this case, even `transfer` fails in the same manner. There is a revert after the Transfer event emission.

**Comment by mds1** [comment]
Ah yes, I see now in your screenshot the approve call succeeded, and the revert is after. Hard to say without a reproduction case, if you can share a repo to reproduce I can take a look tomorrow

**Comment by hasanza** [comment]
That is might kind of you!

I have created this public repo with the relevant files: https://github.com/hasanza/forking

**Comment by hasanza** [comment]
> race condition

I put your suggestion to test by using USDC, and approve works! 
It is definitely some quirk with the write functions (approve, transfer) of USDT. Without having looked at USDT code, I wonder what the issue is...

**Comment by mds1** [comment]
One issue us that you're deploying the instance in a local test environment in `setUp`, then switching to a fork environment in the `test_approve` test. So the contract you deployed does not exist. Modify `test_approve` with two console.logs like this:

```solidity
function test_approve() public {
    address actualUser = address(0x0162Cd2BA40E23378Bf0FD41f919E1be075f025F);
    console2.log(address(instance).code.length);
    vm.selectFork(mainnetFork);
    console2.log(address(instance).code.length);
    vm.prank(actualUser);
    // Allowance to instance
    // This reverts. But calls to `view` functions succeed
    IERC20(USDTAddr).approve(address(instance), 50);
}
```

And you'll see

```
Logs:
  3377
  0
```

In other words, the contract exists because it has non-zero length code, but as soon as you switch to the fork, the contract doesn't exist on that new chain.

I'd suggest removing `selectFork` usage in your test and instead just using `createSelectFork` in the `setUp` method.

However I don't think that's the actual cause of your issue, since that shouldn't affect the approve call.
