### ISSUE TITLE
cast send is using eth_sendTransaction when it should use eth_sendRawTransaction

### ISSUE THREAD

**Issue by maurelian** [foundry-rs/foundry#4831]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (dedc31e 2023-04-26T00:13:24.012522000Z)

### What command(s) is the bug in?

cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am having difficulty calling `cast send` to send a tx via remote RPC. It appears that cast is using `eth_sendTransaction` when it should use `eth_sendRawTransaction`. 

## Details

1. The key I'm trying to use is in a local keystore file.
1. The error I receive from Alchemy is (I get something similar from Infura as well):

```
(code: -32600, message: Unsupported method: eth_sendTransaction. See available methods at https://docs.alchemy.com/alchemy/documentation/apis, data: None)
```

2. A minimum viable repro command is:

```
cast send 0x78339d822c23d943e4a2d4c3dd5408f66e6d662d --from 0x78339d822c23d943e4a2d4c3dd5408f66e6d662d
```

However I have also tried multiple variations, including: 
- with `--keystore ~/Library/Ethereum/keystore/UTC-... --password ...`
- with `--keystore ~/Library/Ethereum/keystore/UTC-...` (no --password`)
- various combinations with and without `--keystore`, `--password` and `--from`

I eventually got it working with `seth` using just the `--from` argument.

**Comment by maurelian** [comment]
Apparently related: I get the exact same error when using the `--ledger` flag when no ledger device is connected.

```
cast send MYADDR --ledger --from MYADDR
```

Connecting a ledger, entering the pin and opening the ethereum app fixes it.

**Comment by mattsse** [comment]
cc @Evalir this is likely just a smol quirk where `eth_sendTransaction` is incorrectly used as the fallback

**Comment by Evalir** [comment]
yup looks like so. Happy to look into it!

**Comment by maurelian** [comment]
Regarding my issue signing from  ledger, this was fixed by turning off ledger live, which presumably freed up the connection. From a side channel conversation, it sounds like @Evalir has a fix for the `--keystore` bug. 

To address the general issue, when `--ledger` or `--keystore` (or any other wallet options that imply local signing) are provided, rather than falling back to `eth_sendTransaction`, I think that it would make sense to raise an error indicating that there is insufficient information to sign locally.

**Comment by Evalir** [comment]
Hey hey! Just adding more color about the `--keystore` issue here:

Did some triaging @maurelian and I've reproduced the `--keystore` issue, albeit with one caveat: It involves user error. If you pass a path that specifies the file `~/Library/Ethereum/keystore.json` it will work as expected—but if you don't specify the file and *just the path* (e.g `~/Library/Ethereum`) it will fail. I'd like to know if you can verify one last time if the files have been passed in correctly? I've tried various combinations and the only way I've been able to reproduce this behavior is when the path does not specify the file, both on absolute and relative paths.

On the more broad sense of the issue, the fix you propose is correct: if a local signing method has been provided, we should always raise an error if we're not able to construct a signer, instead of falling back to `eth_sendTransaction`.

I'll be putting up the fix for this tomorrow—will keep you posted!

**Comment by maurelian** [comment]
> I'd love to know if your keystores do have this property?

It does have the address property yes. I think this key was generated by `geth`.
