### ISSUE TITLE
Use standard chain names

### ISSUE THREAD

**Issue by miohtama** [foundry-rs/foundry#4895]
### Component

Forge

### Describe the feature you would like

Currently, forge has its own chain name and id list here:

https://github.com/foundry-rs/forge-std/blob/cffb5628775fbf120bfc3c123149f6a6d99dc275/src/StdChains.sol#L182

It is different from what all other EVM tools use:

https://github.com/ethereum-lists/chains

This causes confusion for the users.

### Additional context

- Figure out what would be the best path to standardisation
- If standardisation does not make sense, then highlight the supported chain names and differences in the documentation

**Comment by 0xDEnYO** [comment]
Thanks for opening this issue @miohtama 

+1
It would be great if there was a simple way to view all available chain names and a standardized way to add new chains.

e.g. for BSC Testnet the chain name seems to be "bsc-testnet" (according to an error message I got when I used another name) but I was not able to find out where this name is defined.

**Comment by mds1** [comment]
Just to clarify the scope of this issue, I think this is referring only to forge-std's `StdChains`, and nothing in foundry/forge?

Looking at e.g. https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-42161.json, presumably it's the `shortName` field you are suggesting that should match? (We can't use `name` since spaces are not allowed in TOML keys). Given that, TBH those short names feel obscure/unused. In all the config files I've seen, people refer to ethereum mainnet as `mainnet`, not `eth`. Similarly they use `arbitrum` or `arbitrum_one`, not `arb1`. Where are these short names used?

[Seems](https://book.getfoundry.sh/reference/forge-std/#forge-stds-test) the `StdChain` features are not documented in the book, so documenting them and listing the aliases currently feels like the best path forward here

**Comment by 0xDEnYO** [comment]
I am not sure if the link to stdChains is correct here. 

Recently I wanted to interact with bsc testnet. In my repo I had it named "bsctest" but then I got an error from foundry saying this name is invalid, maybe I am referring to "bsc-testnet".
So there seems to be a list of how networks should be called according for foundry.
And we (in my company) would love to name all networks according to foundry in order to avoid any potential errors.
Therefore I was looking for that list but I cannot find it anywhere in the code.

Then asked in the Telegram group and @miohtama was so nice to open up this issue here.

So my personal goal would just be to find out where to find this list (>> the docs would be a great place for it).
And for the foundry project I guess it would be great if there is a standardized/automatic way for adding new networks and updating them in the docs, if that makes sense.

**Comment by mds1** [comment]
> Recently I wanted to interact with bsc testnet. In my repo I had it named "bsctest" but then I got an error from foundry saying this name is invalid, maybe I am referring to "bsc-testnet".

Can you share the exact error message and steps to reproduce? I'm still unsure where exactly this is from and whether it's a forge-std issue or a foundry issue

**Comment by 0xDEnYO** [comment]
Here is an example:
I am calling forge verify-contract from a bash script:

`forge verify-contract --watch --chain "$NETWORK" "$ADDRESS" "$FULL_PATH" -e "${!API_KEY}"
`

The NETWORK parameter has the value "okx" which has never been a problem before. All of a sudden it fails and it shows me this list of "allowed" chains. 

The same happened when I used "bsctest" (cause as you can see, there is only "bsc-testnet" in the list so it wants exactly that name. 

<img width="2559" alt="image" src="https://github.com/foundry-rs/foundry/assets/77058885/03db5a6c-bcc9-4512-9ac3-c95b0d2ca18f">

Now with bsctest it was easy, cause there was a corrected name that I could use. 
But for the "okx" case, I dont even know how to deal with this now. Do you have any suggestions?

**Comment by 0xDEnYO** [comment]
Here is an example:
I am calling forge verify-contract from a bash script:

`forge verify-contract --watch --chain "$NETWORK" "$ADDRESS" "$FULL_PATH" -e "${!API_KEY}"
`

The NETWORK parameter has the value "okx" which has never been a problem before. All of a sudden it fails and it shows me this list of "allowed" chains. 

The same happened when I used "bsctest" (cause as you can see, there is only "bsc-testnet" in the list so it wants exactly that name. 

<img width="2558" alt="image" src="https://github.com/foundry-rs/foundry/assets/77058885/4d2ad1c2-abd9-47db-b3ea-2b0c2907e3be">


Now with bsctest it was easy, cause there was a corrected name that I could use. 
According to the --help info, I can also use the chainId. But when I try that (with chainId 66 and passing a valid API key from https://www.oklink.com) it throws an error "ETHERSCAN_API_KEY must be set".
I also tried to call forge verify-contract with an env-variable called ETHERSCAN_API_KEY from bash like this:
`ETHERSCAN_API_KEY=${!API_KEY} forge verify-contract --watch --chain "$CHAIN_ID" "$ADDRESS" "$FULL_PATH" -e "${!API_KEY}"`
and that didnt work either (same error)


Do you have any suggestions how to deal with this?

**Comment by mds1** [comment]
Ah ok this seems like it's the `Chain` enum from ethers-rs: https://github.com/gakonst/ethers-rs/blob/3e7606d81b423593db5a38dcf3b5174987efc74c/ethers-core/src/types/chain.rs#L55

@Evalir @mattsse Not sure what intended behavior is here for unsupported chains or why `okx` used to work and now doesn't

**Comment by zerosnacks** [comment]
We've since updated to use https://github.com/alloy-rs/chains as a central place for canonical type definitions for EIP-155 chains

@miohtama / @0xDEnYO if you are still experiencing issues please report them there or open a PR with the missing network: https://github.com/alloy-rs/chains/pulls?q=is%3Apr+is%3Aclosed
