### ISSUE TITLE
currentPrank currentBroadcast, ...

### ISSUE THREAD

**Issue by wighawag** [foundry-rs/foundry#4927]
### Component

Forge

### Describe the feature you would like

Currently `prank`, `startPrank`, `stopPrank`  and the `broadcast` equivalent operate on a hidden state and code for script and test cannot know whether a prank and broadcast is active.

This prevents inner call to for example disable a prank as they cannot know whether they should reenable it.

It would be great if we could get the current prank status address, same for brroadcast

something like

```
function currentPrank() external view returns(bool active, address account);
function currentBroadcast() external view returns(bool active, address sender, address txOrigin);
```

**Comment by mds1** [comment]
https://github.com/foundry-rs/foundry/pull/4884 is implementing a cheat of `function readPrank() external returns (bool isPrankActive, address msgSender, address txOrigin)`

For now the cheat will be disabled in scripts, but ultimately it should support both script and tests, and return the broadcast info when in a scripting mode and prank info in a testing mode. I don't think separate cheats is the right UX since you can run a script file in a test, which results in broadcasts behaving like pranks (so we might want to rename the cheat once it supports both). Open to ideas if you want to move the convo to that PR

**Comment by Evalir** [comment]
Is this closeable? As #4884 was merged and had substantial discussion

**Comment by mds1** [comment]
Yep this is closeable
