### ISSUE TITLE
Adding `vm.formatUnits`, like EthersJS formatEther and formatUnits function

### ISSUE THREAD

**Issue by Sz0x** [foundry-rs/foundry#5106]
### Component

Forge

### Describe the feature you would like

In the EthersJS library, there is a function called `formatEther` that takes in a value in wei (usually in the form of either a string or Big Number) and outputs it in ether format.

Similarly, the `formatUnits` function does the same thing, but takes an optional second parameter that specifies the number of decimals.

This is helpful when logging the balances of contracts and wallets to make it easier to read

### Additional context

The utility function could be as simple as the following:

```solidity

    function formatEther(uint256 amount) internal virtual returns (uint256) {
        return amount / 1 ether;
    }

    function formatUnits(uint256 amount, uint256 decimals) internal virtual returns (uint256) {
        return amount / (10 ** decimals);
    }
```

**Comment by tynes** [comment]
This seems more like a `forge-std` thing. `cast --to-unit` has this ability on the CLI

**Comment by Evalir** [comment]
yep agreed—this seems useful but more for `forge-std`. There's already similar utils on `cast`. @mds1 wdyt about transferring this issue to forge-std?

**Comment by Tudmotu** [comment]
I might be misunderstanding the request here, but `ethers::utils::format_units` outputs a `string`, not a `uint`.
And simply dividing a `uint` won't preserve decimal precision, so `0.1 ether / 1 ether` will just revert.

Using `console2` is also not ideal IMO because:
1. Sometimes you wanna compose messages before logging
2. `console2` only logs at the end of a script, while sometimes it's useful to write logs into a file for real-time logging

@Sz0x I have an implementation of a `vm.formatUnits` cheatcode on my own Foundry fork. If you have your own fork as well, you can copy the implementation from my branch.

And for Foundry team — it seems this is not something you'd want to merge but if you change your mind let me know and I'll happily open a PR :slightly_smiling_face: 
https://github.com/Tudmotu/foundry/compare/feature/vm.time...Tudmotu:foundry:feature/vm.formatUnits?expand=1

**Comment by Tudmotu** [comment]
@mattsse WDYT ?

**Comment by grandizzy** [comment]
since there are other proposed ways to handle this request going to close it for now. Please reopen if you feel should still be implemented. thank you!
