### ISSUE TITLE
Cast: running txs on optimism result with `Transaction(GasPriceLessThanBaseFee)` error

### ISSUE THREAD

**Issue by soloblack** [foundry-rs/foundry#5122]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (08a629a 2023-06-03T00:14:26.563741000Z)

### What command(s) is the bug in?

cast run

### Operating System

macOS (Apple Silicon)

### Describe the bug

cast run 0xd0f48fb6256e4744386214343691fd0ef9b7f6fc5037d6221e838ac6fabe9659

Executing previous transactions from the block.
Error:
Failed to execute transaction: 0xd0f48fb6256e4744386214343691fd0ef9b7f6fc5037d6221e838ac6fabe9659

Context:
- backend: failed while inspecting: Transaction(GasPriceLessThanBasefee)

**Comment by Evalir** [comment]
i have a hunch this might be fixed by #5126

**Comment by Evalir** [comment]
Not fixed by #5126, will investigate—might be an L2 gas calculation kink.

**Comment by tynes** [comment]
This is probably because of deposit transactions, the first tx in the block is a system tx that updates the L1 context in a special L2 contract. Learn more [here](https://github.com/ethereum-optimism/optimism/blob/develop/specs/deposits.md#l1-attributes-deposited-transaction). An example tx can be found [here](https://optimistic.etherscan.io/tx/0x2683c5d9e983660b2c64e77764245a0dfa384195a9b345030970b55e40fdf8bd).

**Comment by LIYANG-UST** [comment]
same on Arbitrum, how to solve it?

**Comment by dcposch** [comment]
#### To reproduce on Base

```
cast run --rpc-url https://goerli.base.org  0xf674e0989e2721b526eeaa7d7c16b86ecdf362f0ee2ed64d92b08d1fb161bf43
```

**Comment by 0xdapper** [comment]
Same on arbitrum
