### ISSUE TITLE
`--mnemonics` flag is required but ignored when using `--mnemonic-indexes` in a forge script

### ISSUE THREAD

**Issue by julien-devatom** [foundry-rs/foundry#5179]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6d6f854 2023-06-19T00:07:11.657015827Z)

### What command(s) is the bug in?

forge script script/Deploy.s.sol --mnemonics 1 --mnemonic-indexes 1 --ledger --broadcast  --rpc-url $RPC_URL

### Operating System

Linux

### Describe the bug

using ` --mnemonics 1` when running a script gives the following error: the word `1` is invalid

I aim to run a script with the 1st derivation on my ledger.

It was running well before the new forge version (for example, check the usage on [morpho-labs/safer](https://github.com/morpho-labs/safer/tree/main#hardware-wallet-support))

**Comment by Evalir** [comment]
Are you sure you're using the same command? `--mnemonics` receives a path for finding a mnemonic phrase. `--mnemonic` receives a BIP32 compatible mnemonic.

**Comment by sakulstra** [comment]
@Evalir not 100% sure if it's the same issue, but i saw this pop up a few times on telegram as well.

The issue seems to be that until recently, when using ledger `--broadcast --ledger --mnemonic-indexes ${MNEMONIC_INDEX} --sender ${LEDGER_SENDER}` would have worked perfectly fine.

Then some update was made on foundry: `--mnemonics` was suddenly required(but ignored, when using m-index & sender), so ppl started using `--broadcast --ledger --mnemonic-indexes ${MNEMONIC_INDEX} --sender ${LEDGER_SENDER} --mnemonics 1`.

In another update `--mnemonics` validation seems to have been changed, so `1` is no longer valid. We use `--mnemonics foo` as a workaround, which seems to satisfy validation.

**Comment by julien-devatom** [comment]
> The core issue seems to be that this is required, even when not used.
This is also my understanding. `--mnemonics foo` is working so I'm closing this ticket, ty for your answers guys @sakulstra @Evalir

**Comment by sakulstra** [comment]
@julien-devatom wouldn't close it as it's still a bug no? The field should just not be required.

**Comment by julien-devatom** [comment]
> @julien-devatom wouldn't close it as it's still a bug no? The field should just not be required.

Yeah as you want! My point was that my command is now working, but if you can use this ticket to rm the required but ignored `mnemonics` field, go to reopen it

**Comment by DaniPopes** [comment]
https://github.com/foundry-rs/foundry/pull/5277
