### ISSUE TITLE
make fork testing better like hardhat

### ISSUE THREAD

**Issue by iKausik** [foundry-rs/foundry#5207]
### Component

Forge

### Describe the feature you would like

it'll be great if the features to test forked smart contracts are easier and more organized, I like the great experience of foundry tests using solidity but the fork testing should be better and easier like hardhat.

it would be great if we can set up all configurations of the fork in the .toml file and can run the fork test with a simple command, exactly like what we do on a hardhat.

**Comment by rplusq** [comment]
Do you mind expanding on this? Can you reference the docs on how it works on Hardhat?

**Comment by mds1** [comment]
If you want to use this approach you can use the [`--fork-url`](https://book.getfoundry.sh/forge/fork-testing#forking-mode) CLI flag or the equivalent config file flag. Closing since this seems already supported, but let me know if I misunderstood

(FWIW, I'd argue using the cheatcodes is preferable—you can do this in `setUp` to get the same benefit, but it's more flexible/extensible. Here's a [tweet thread](https://twitter.com/msolomon44/status/1564742781129502722) I wrote about this)

**Comment by mds1** [comment]
The `.env` file is automatically loaded by forge on each OS
