### ISSUE TITLE
forge build --sizes ignores contents of at least one sol in the project

### ISSUE THREAD

**Issue by aathan** [foundry-rs/foundry#5240]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31d6498 2023-06-28T00:10:20.700537031Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

There is a bug in `forge build` which prevents it from outputting at least `--sizes` info for a .sol files in my project. Dunno if the abi is valid (I'll try to figure that out tomorrow). No syntax errors or warnings are emitted. Is there a way for me to get forge to output the solc command line it's using so I can see if solc is emitting some console output that may be a hint?

```
library { ... }
contract {
 erc20 stuff...
 other stuff...
 struct localVars {}
 function problemFunction(... calldata params ... ) public view returns (SomeOtherStruct memory ret) {
    ... body that uses localVars / body may be removed...
  }
}
```

The out/ directory contains abi for the affected file. I've tried removing parts of the file to see if it's something about the contents. I placed a certain function definition at the bottom of the contract. If that function appears, no output from `--sizes` occurs UNLESS it's the only function defined in the file (other than a few generic IERC20's at the top). I can remove the BODY of the function and it still causes problems with `--sizes` output if `other stuff...` is in the file. If `other stuff...` does not appear, then irrespective of the existence of the body, `--sizes` contains a line for the file.

This would seem to imply there is some interaction with what's in the body of the function and `other stuff...` , but what kind of interaction would cause NO warnings or errors to be emitted and `forge build --sizes` to not work? Again, the abi seems to exist, and it is too late right now for me to verify what's in it.

Let me know what to look for. This sounds like a problem with forge interpreting the abi output.

using solc 8.19

**Comment by aathan** [comment]
Well, it looks like the issue is actually this:

```

    event TestEvent(address indexed);
    function test() public {
        emit TestEvent(msg.sender);
    }

```

If this is included in the contract, `forge build --sizes` shows no output for the file.

If forge is triaging things simply based on the word "test" appearing in places, that's just (IMHO) ... wrong.

**Comment by mattsse** [comment]
can you prepare a repro please

**Comment by mds1** [comment]
The issue here is because the method is named `test`, so forge thinks it's a test or script contract and excludes it from the size check:

https://github.com/foundry-rs/foundry/blob/642376210f0151794e1bb34c9448c2ee30ab0d88/common/src/compile.rs#L150-L160

https://github.com/foundry-rs/foundry/blob/642376210f0151794e1bb34c9448c2ee30ab0d88/common/src/traits.rs#L63-L65

> If forge is triaging things simply based on the word "test" appearing in places, that's just (IMHO) ... wrong.

`test` is a special function prefix used by forge to identify test functions to execute. Without a special prefix UX would be worse. An alternative is to identify test/script contracts exclusively on the presence of the `IS_TEST` and `IS_SCRIPT` method, but tests still need the special `test` prefix, so also using that is more robust since the user's test contract might not have that method. Additionally, there's not really use cases where a production contract needs to have a method that starts with `test` so this heuristic seems ok, but other ideas welcome :)

**Comment by aathan** [comment]
It's not clear whether this is a "wontfix" or some change to resolve what's a test class differently, has been made?

Lets not make a big deal over trivial things but come on. As developers of potentially foundational technology the attitude of making statements like "there's not really use cases where a production contract needs to have a method that starts with test" is simply inappropriate. Contracts may be deployed to either private or public blockchains for any reason and naming conventions that are not limited by the EVM itself should not be limited by the tooling, if reasonably possible.

Also, you seem to be conflating the naming of test functions with the marking of the entire contract as a test contract. I am not sure what UX you are referring to. There seem to be much better ways to potentially decide that a contract is a test contract, including whether it exists in the `test/` directory, whether it derives from `Test`, etc etc.

It would be MUCH better IMHO to tag a contract as a special contract type based on available information about the devops environment (such as filesystem location), or the presence of forge-specific contents in the ABI, such as a *solitary/single* method of some special name, preferably one that is extremely unlikely to be important in a production deployment, such as "____is_test()" rather than a multitude of methods such as "anything that starts with test"

Imagine a contract with `function testValidityOfSignatureForThisTransaction()`

Anyway, not a big deal, but I do want to push back on the implied attitude towards imposing naming conventions globally on projects by excluding any prefix across a large number of possible function names, particularly when the prefix is a natural language word.

**Comment by mds1** [comment]
> It's not clear whether this is a "wontfix" or some change to resolve what's a test class differently, has been made?

Sorry, maybe I misunderstood the issue. I thought the scope was confusion about why it seemed `forge build --sizes` was ignoring a contract. The answer to that was: this is expected behavior based on how test contracts are identified, and not a bug. Which is why I closed this.

>  As developers of potentially foundational technology the attitude of making statements like "there's not really use cases where a production contract needs to have a method that starts with test" is simply inappropriate. Contracts may be deployed to either private or public blockchains for any reason and naming conventions that are not limited by the EVM itself should not be limited by the tooling, if reasonably possible.

Agreed that wanting to name something like `function testValidityOfSignatureForThisTransaction()` is certainly valid. Note that the behavior used to identify test contracts *does not* affect deployment in any way. The contract can still be tested and deployed like any other contract. I believe the only place the `test` function name prefix would have a noticeable impact on users is this exclusion from the `forge build --sizes` output.

> It would be MUCH better IMHO to tag a contract as a special contract type based on available information about the devops environment (such as filesystem location), or the presence of forge-specific contents in the ABI, such as a solitary/single method of some special name, preferably one that is extremely unlikely to be important in a production deployment, such as "____is_test()" rather than a multitude of methods such as "anything that starts with test"

First you have to define "what is a test contract". Is it only a contract that has executable tests, or does it include helper contracts that have no tests themselves? How do mock contracts fit in? The answer depends on the use case: you may want a different definition for running tests than for identifying contracts to exclude from  the `forge build --sizes` output. So we use [`IS_TEST`](https://github.com/dapphub/ds-test/blob/e282159d5170298eb2455a6c05280ab5a73a4ef0/src/test.sol#L38) as a broad way to identify all test contracts (and [similarly](https://github.com/foundry-rs/forge-std/blob/a3f287afc896bbc3b8a53669d41038cd8a59c083/src/Script.sol#L26) for scripts). But if a user is using their own assertion framework and forgets `IS_TEST`, ideally you still want to be able to find/run the tests, which is why the `test` function prefix is also used.

So you can see it gets a bit complicated, then you also need to consider that users may use different folder structures, various kinds of helper contracts (mocks, test helpers, script helpers, etc).

All that to say: maybe we should change what `forge build --sizes` uses to exclude non-src contracts, and I'm open to ideas there if you have suggestions.
