### ISSUE TITLE
Differentiate between fail_on_assert and fail_on_revert

### ISSUE THREAD

**Issue by aviggiano** [foundry-rs/foundry#5259]
Hello,

I am currently fuzzing Uniswap v2 as part of a comparison between foundry and echidna.

I am having some trouble reproducing what I can do with echidna here. 

More specifically, when echidna is run with `testMode: assertion`, it will fail if an assertion does not equal `true`, but it will continue fuzzing if a `require` does not equal `true` (similar to the behavior of `vm.assume` on foundry). 

However, foundry invariant tests will treat both `assert` and `revert` as a failure. 

This is not ideal when I am trying to catch failed asserts on my `targetContract` but I do not care about failed `require`s on any other contracts. This is the case if I'm doing handler-based testing. For example, my target contract **MUST NOT** have any failed `assert`s, but any other deployed contracts may have failed `require`s.

It would be interesting to have a `fail_on_assert` configuration variable in order to mimic echidna's behavior.

**Comment by mds1** [comment]
Does the `fail_on_revert` flag give you what you need? When `false` reverts are ignored. You can find more info about this flag in the book

**Comment by aviggiano** [comment]
Hi @mds1 

It does not. What I want is to fail on `assert` but not fail on `revert`

Is it possible to do that?

**Comment by mds1** [comment]
Do you mean `assert` as-in the native solidity method, or are you referring to `assertEq` helpers? If the latter, this will work with `fail_on_revert = false` and using `assertEq` in your invariant test contracts. Note that `assertEq` is not yet supported in handler/target contracts, see https://github.com/foundry-rs/foundry/issues/4718. 

If you mean the former, this is not currently supported. Assuming #4718 gets fixed, my question would be: why do you need to use `assert` instead of `assertEq`? Is this for integration with the SMT solver or similar? `assert` creates an error of `Panic(uint256)` and `require` creates an error of `Error(string)`, so we should be able to differentiate them if this is needed.

Can you share more specifics about what you are trying to accomplish? Foundry and echidna structure their tests/failure detection differently, so purely trying to replicate echidna with `assert` might not be the right goal

**Comment by mds1** [comment]
I see, thanks for the explanation.

As of echidna v2.1.1 there should be compatibility with foundry style invariant tests (search "foundry" on echidna releases page), so I don't think any changes to foundry should be required for this goal.

Regardless, my hesitation around supporting this is that it feels like a dangerous distinction, and I don't know why you'd want to rely on it: A test assertion failure such as `assert(x * y == k)` is [indistinguishable](https://docs.soliditylang.org/en/latest/control-structures.html#panic-via-assert-and-error-via-require) from a solidity-generated assertion failure (e.g. arithmetic overflow). The latter feels like you'd want it to be ignored, otherwise e.g. large values generated by the fuzzer are considered assertion failures of the same kind as `assert(x * y == k)` failures. Whereas a test assertion failure from `assertEq` is unambiguous.

Am I misunderstanding something about how echidna works? It seems odd that they're ok with not being able to distinguish those two types of reverts.

**Comment by aviggiano** [comment]
Thanks for the explanation. It is now clear why using `assert` to signify a failure is not ideal. I will replace my test adapters (one for echidna and one for foundry) so that echidna's will use `assert` and foundry's will use `assertEq`. 


I will close this issue.
