### ISSUE TITLE
`vm.mockCall` with only strict calldata matching

### ISSUE THREAD

**Issue by Zer0dot** [foundry-rs/foundry#5305]
### Component

Forge

### Describe the feature you would like

At the moment, [`vm.mockCall()`](https://book.getfoundry.sh/cheatcodes/mock-call?highlight=mockcall#mockcall) checks for loosely matching calldata, without an option to force a strict match.

This could lead to certain issues where a call that shouldn't be mocked gets mocked, and calldata that you think is matching actually isn't.

It would be great to have either a `vm.mockCallStrict()` or a flag that makes `vm.mockCall()` enforce strict calldata matching.

What do you folks think?

**Comment by mds1** [comment]
Can you expand on your use case and give an example? Here's my guess:

```solidity
contract A {
  function foo() external {
    if (msg.data.length > 4) {
      // Do something with the extra calldata
    }
  }
}
```

In the above example we have a function that takes no args so typically you'd have 4 bytes of calldata (for the function selector). But solidity lets you pass extra data, so sometimes the calldata may be longer than 4 bytes. Currently, we cannot configure `vm.mockCall` to only mock a response when the calldata is exactly 4 bytes, because the extra data version also gets mocked, since the function selectors match.

Is that correct?

**Comment by grandizzy** [comment]
@Zer0dot maybe try using the new `vm.mockFunction` cheatcode and see if it works for your case, pls check https://book.getfoundry.sh/cheatcodes/mock-function#description

**Comment by grandizzy** [comment]
Closing for now, @Zer0dot please reopen if comments above not clear and this is still needed. thank you
