### ISSUE TITLE
Relying on a Commit Hash breaks CI builds after new releases

### ISSUE THREAD

**Issue by molecula451** [foundry-rs/foundry#5312]
Title is clear. Relying on a commit hash breaks CI, i by defacto, need a new releases, but also, don't need only "nightly" as this could also break my CI besides the hash, any thoughts on this one 

so I develop a proper solution?

![build](https://github.com/foundry-rs/foundry/assets/41552663/ece6b0ee-6b57-463b-a6cc-ee9c461eff00)

**Comment by Evalir** [comment]
This is expected behavior—nightly releases only stay for 3 days and then are cleared away. There is a monthly pinned nightly that can be used for stability, see https://github.com/foundry-rs/foundry/tree/nightly-cc5637a979050c39b3d06bc4cc6134f0591ee8d0

Also, 1.0 will be released soon which will have stable releases to use on CI.

**Comment by yiyi-wang-rv** [comment]
Hi @Evalir , can I assume https://github.com/foundry-rs/foundry/releases/tag/nightly-d369d2486f85576eec4ca41d277391dfdae21ba7 is the latest monthly pinned nightly that will not be deleted? Thank you!

**Comment by Evalir** [comment]
That is correct @yiyi-wang-rv :) feel free to lock CI to that one!

**Comment by yiyi-wang-rv** [comment]
Thank you!
