### ISSUE TITLE
fuzzer struggles to find values in roughly the top half of all possible inputs

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#5343]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8c48932 2023-07-09T00:05:12.467663000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

`vm.assume` maxes out and fails when constraining values in the top half of all possible `uint256`, if the top 3 values are excluded

i.e.

```solidity
    function testRange(uint256 a) external {
        vm.assume(a > type(uint256).max / 2);
        vm.assume(a < type(uint256).max - 3);
    }
```

gives the error

```
[FAIL. Reason: The `vm.assume` cheatcode rejected too many inputs (65536 allowed)] testRange(uint256) (runs: 651, μ: 3594, ~: 3594)
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 556.16ms
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)
```

I understand that `vm.assume` is known to have difficulty with tight ranges, but this range covers effectively half of all possible values.

**Comment by mds1** [comment]
> but this range covers effectively half of all possible values.

Half of maxUint is 5.8e76. If fuzzer inputs were random and linearly distributed, that means half the values would be 5.8e76 or larger. This is extremely big, and not a good distribution for smart contract systems. Instead the fuzzer uses various strategies (not just randomness) so generated values are closer to evenly distributed across log-space than linear-space.

This means the range you're using here is quite small. With the natural log:
- `ln(type(uint256).max) = 177.4`
- `ln(type(uint256).max / 2) = 176.8`
- `ln(1) = 0`

With that framing you can see the range you have is quite small. 

`vm.assume` is naive and there is no "learning" to try to figure out your criteria, so failures like this are expected. In general you should prefer forge-std's `bound` over `vm.assume`, and `a = bound(a, type(uint256).max / 2 + 1, type(uint256).max - 4)` (because the bounds are inclusive) is a better way to handle your example.
