### ISSUE TITLE
getting values of emitted events

### ISSUE THREAD

**Issue by stillmatic** [foundry-rs/foundry#543]
I'm looking at updating https://github.com/optionality/clone-factory and testing it with forge. 

One of the functions does the following, and emits an event with the clone address (vs returning it)

```solidity
    function createThing(string memory _name, uint256 _value) public {
        address clone = createClone(libraryAddress);
        Thing(clone).init(_name, _value);
        emit ThingCreated(clone, libraryAddress);
    }
```

the tests then pick up this address by doing

```js
 _factory.createThing(name, value)
          .then(tx => {
            return Thing.at(tx.logs[0].args.newThingAddress);
          })
```
Is there a similar way to get the logged / emitted events and their arguments in forge?

**Comment by onbjerg** [comment]
That's not currently possible but it would definitely make sense to explore a cheatcode like that. Ergonomics wise it probably wouldn't be very good since you would need to do some manual `abi.decode` calls etc.

**Comment by fubhy** [comment]
I just ran into a case like that too. This is also slightly related to what's been discussed in https://github.com/gakonst/foundry/issues/512 as extracting parameters from loosely matched events could also be a reasonable solution for that one.

**Comment by mds1** [comment]
I agree this we should have log functionality like this, though like @onbjerg mentioned UX will be probably be pretty gross unless we implement solidity pre-processing first

One note is that in this specific use case you can precaclulate the expected address, then assert there's code at the address after the `createThing` call. If you use `create2` you can do this now, if you use `create` you'd need #554 to be implemented first

**Comment by gakonst** [comment]
Similar to how we record accessed storage slots, should we add a `captureLogs` and `getLogs` cheatcode perhaps? Not sure what the ideal UX here would be, cc @brockelmore

**Comment by bentobox19** [comment]
Is this in the roadmap somewhere? I was porting some [Ethernaut](https://ethernaut.openzeppelin.com/), and while you can modify the contract `Ethernaut.sol` to return you the values instead of emitting an event, would be great to have a cheat code capturing that info for you.

I have 3 days of experience with forge 😅, @gakonst is talking above of some gotchas on implementing this, however I see that the logs are outputted at the traces.:

<img width="854" alt="Screen Shot 2022-06-28 at 13 46 10" src="https://user-images.githubusercontent.com/85324266/176248780-acadf55c-21c8-47a1-b0c4-5590547d0b5b.png">

Anyways, I'm happy to brush up my rust skills and implement this cheat code if it is in the roadmap. Where should I go? Who should I talk to?

**Comment by onbjerg** [comment]
You can use `expectEmit` for now, but yeah, we plan to add this at some point

**Comment by bentobox19** [comment]
What the heck, just started a draft PR. Hope I can squeeze the hours to get it done 😅

https://github.com/foundry-rs/foundry/pull/2161
