### ISSUE TITLE
The function parameter names are the same, but the return value is different. There will be an error

### ISSUE THREAD

**Issue by SolExpDB** [foundry-rs/foundry#5624]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dffdfde 2023-08-14T00:21:17.235733800Z)

### What command(s) is the bug in?

 forge test --contracts exchange.sol

### Operating System

Windows

### Describe the bug

"The same function parameter name, but different return values.
For the 'exchange' function of the Curve pool, the 2.x version does not have a return value. The 3.x version has a return value. If I combine the two contract interface files into one file, there will be an error."

For example：
 2.x version:   
       function exchange(int128 i, int128 j, uint256 dx, uint256 min_dy) external payable;

 3.x version:  
       function exchange(int128 i, int128 j, uint256 dx, uint256 min_dy) external payable returns (uint256);

![屏幕截图 2023-08-14 214437](https://github.com/foundry-rs/foundry/assets/138878504/f67b259a-5df7-4e80-8565-628eff737f79)

**Comment by mds1** [comment]
This error is from solidity, and it's telling you that the `exchange` function is defined twice, but one version has a return value and the other does not. Functions are uniquely identified by their selector, and function selectors are computed from the function name and input arguments, not their return data, so you cannot have two functions with the same input but different return data.

Check out the solidity docs for more info on function selectors. This duplicate definition is a problem because when you call `.exchange`, solidity won't know whether it should expect a uint256 to be returned, or if nothing should be returned
