### ISSUE TITLE
Add cheat code to test if file exists

### ISSUE THREAD

**Issue by guidanoli** [foundry-rs/foundry#5637]
### Component

Forge

### Describe the feature you would like

There would be a new function with the following signature:

```solidity
// Check whether a file in a given path exists
function isFile(string calldata) external returns (bool);
```

### Additional context

This function would be useful to give a better error message to the user when some essential file is missing.

**Comment by mattsse** [comment]
supportive, but this should be three functions

exists, isFile, isDir

**Comment by guidanoli** [comment]
> supportive, but this should be three functions

For my use case, only `isFile` would suffice. But yes, these 3 functions would serve a more complete interface. :-)

**Comment by guidanoli** [comment]
@mds1 I believe it fails when there is no file in the given path.

**Comment by ruvaag** [comment]
I'd be happy to take this on. 

Is there consensus on the approach? Looks like there's two ways --

1. From @mattsse - add three new cheats `isFile`, `isDir` and `exists` that return bools

```
function exists(string calldata path) external returns (bool);
function isFile(string calldata path) external returns (bool);
function isDir(string calldata path) external returns (bool);
```

2. From @mds1 - modify return struct of existing cheat `fsMetaData` to return `exists`

```
struct FsMetadata {
    bool isDir;
    bool isSymlink;
    uint256 length;
    bool readOnly;
    uint256 modified;
    uint256 accessed;
    uint256 created;
    bool exists;
}
```

Personally inclined towards the former because it allows more generalised script ops along the lines of _If X [exists/is a file/is a directory] do Y_ that the latter could hinder, but more than happy to defer to existing contributors.

**Comment by mattsse** [comment]
nice, 
we can add new impls for that and leverage `Path::{is_file,is_dir,exists}`

**Comment by guidanoli** [comment]
But then what values will the other fields in `FsMetadata` have if the file doesn't exist?

**Comment by ruvaag** [comment]
Since they're standalone implementations, `isFile` is decoupled from the `FsMetadata` cheatcode and struct.

Intended usage for your case could look like -

```
string memory path = "path/to/file";
if (vm.isFile(path)) {
    Vm.FsMetadata memory metadata = vm.fsMetadata(path);
    // do stuff with metadata
}
