### ISSUE TITLE
`vm.expectRevert` doesn't register a nested call revert call and proceeds as if the call were successful. 

### ISSUE THREAD

**Issue by dcbuild3r** [foundry-rs/foundry#5693]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6676e81 2023-08-22T00:28:15.086036000Z)

### What command(s) is the bug in?

forget test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have a contract that interacts with Optimism's `crossDomainMessenger` setup, the message gets sent from L1 to L2 and then the `L2CrossDomainMessenger` calls a specified contract on L2 with some message payload, this call is supposed to revert in the test, it reverts when I run forge test and the error appears in the execution trace. However, when I `vm.expectRevert()` that error, forge test complains that: 

```
[FAIL. Reason: Call did not revert as expected. ...]
```

The test in question can be found [here](https://github.com/worldcoin/world-id-state-bridge/blob/a8d3952eb8949c28982216ff90347aaba6b0b5ea/src/test/OpWorldID.t.sol#L178-L268). To replicate this error, uncomment [line 250](https://github.com/worldcoin/world-id-state-bridge/blob/a8d3952eb8949c28982216ff90347aaba6b0b5ea/src/test/OpWorldID.t.sol#L250) and run 

```bash
forge test --match-test test_receiveRoot_reverts_CannotOverwriteRoot -vvvvv 
```

Thanks for any help and don't hesitate to DM me on [TG](t.me/dcbuild3r) or tag me in this issue.

**Comment by Evalir** [comment]
Right I see:

 the call to `Hashing.hashCrossDomainMessageV1(...)` is special because it's a library call, and this library only has internal functions, therefore technically it's a `JUMP`, not a `CALL`. This means that `expectRevert` won't work since it expects reverts to happen in `CALL`s.

One thing you can do to fix this is to wrap the call to the library in an intermediate contract e.g `HashingMock` and make this call `external`, so it properly triggers a `CALL` opcode—lmk if that works!

**Comment by dcbuild3r** [comment]
Awesome, will try thanks!
