### ISSUE TITLE
Building contracts with different compiler settings

### ISSUE THREAD

**Issue by drortirosh** [foundry-rs/foundry#5715]
### Component

Forge

### Describe the feature you would like

Currenlty `forge build` uses a single configuration settings for all compiled contracts.
In our project, we need to compile the production code (2 contracts) using `via-ir`, but all the supporting contracts without.

We currently use [hardhat configuratio](https://github.com/eth-infinitism/account-abstraction/blob/develop/hardhat.config.ts#L46-L49)n with specific "configuration override" for just those 2 contracts.

It would be nice if forge supported such configuration too.

**Comment by drortirosh** [comment]
Is there any plan to implement this feature?
Having few production contracts an a lot of surrounding  test contracts is a common practice.
Current (single-compiler settings) require either very slow project compilation, since all tests (and unused library contracts) are required to be optimized, or testing the production code in un-optimized build - which makes the tests incomplete, and gas tests unusable.

**Comment by arr00** [comment]
Would like this feature as well

**Comment by CodeSandwich** [comment]
Another reason to tune the compiler for specific contracts is that some of them need to be compile into a small bytecode, but they shouldn't force all the contracts in the project to get poor runtime optimization.

- Some contracts are just large, and must have a lower `optimizer_runs` to fit in the 24576B size limit.
- Some contracts are designed to be deployed multiple times by the end users, they too should be optimized for small deployment size, because the gas savings coming from high `optimizer_runs` may never recoup the higher deployment costs.

**Comment by KholdStare** [comment]
@mattsse Any thoughts on this? We're running into this where we have a few contracts, and one is quite large and just over the limit on the our optimizer setting. It would be nice to override the profile settings per contract.

**Comment by zerosnacks** [comment]
Related: https://github.com/foundry-rs/foundry/issues/6099
