### ISSUE TITLE
forge coverge aborts with no explanation

### ISSUE THREAD

**Issue by drortirosh** [foundry-rs/foundry#5716]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6c0fce3 2023-07-14T02:45:44.842244000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

got error:
```sh
$ forge coverage
[⠢] Compiling...
[⠔] Compiling 113 files with 0.8.20
[⠒] Solc 0.8.20 finished in 1.23s
Error:
Compiler run failed:
Error: Compiler error (/solidity/libyul/backends/evm/AsmCodeGen.cpp:68):Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables. When compiling inline assembly: Variable value0 is 1 slot(s) too deep inside the stack. Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
```

The error message is not helpful.
tried to run with `--via-ir` (either in command-line or in `foundry.toml`), but it seemed to be ignored.

**Comment by Evalir** [comment]
Hey! this just means that you hit a stack too deep issue—this is somewhat common sadly and apart from the recommended workarounds in the compiler error we don't have too many ways around it. Let's take this to the foundry support channel so more people can chime in for workarounds!

**Comment by drortirosh** [comment]
The question is why foundry doesn't support the "remedy", which is via-ir compilation mode. 

We had the same issue with sol-coverage, and found out that their latest version supports the via-ir compilation mode, and the solves the attack too deep problem.

**Comment by Valentin-Seehausen** [comment]
Hey, before opening a new issue: Would it be possible to get more information on which file, contract or even function this happens? This would be amazing as otherwise the only method I know is brute force, which means commenting out the code, removing files, etc.

For new projects, I add the coverage report to the GitHub CI pipeline to make sure we don't run into this in the first place, but everyone has to work with legacy code from time to time.

**Comment by vasinl124** [comment]
that would be great to know which one has the issue. +1

**Comment by HadiEsna** [comment]
> that would be great to know which one has the issue. +1

+1

**Comment by HadiEsna** [comment]
I don't have any optimization setting enabled on my normal "build"
Why don't I get this error when compiling the contracts and I get it when calling coverage?

**Comment by Hovooo** [comment]
> I don't have any optimization setting enabled on my normal "build" Any idea why I don't get this error when compiling the contracts and I get it when calling coverage?

Hi @HadiEsna 
Same here. 
Could you find any solution for that? 
I too get no problems when compiling or building, but get 

` Compiler error (/solidity/libyul/backends/evm/AsmCodeGen.cpp:67):Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables. When compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack. Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.` 

when running

 `forge coverage --report summary`
