### ISSUE TITLE
bug(chisel): imported contract instance updates with updates in source contract

### ISSUE THREAD

**Issue by PeterMcQuaid** [foundry-rs/foundry#5889]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

0.2.0

### Operating System

None

### Describe the bug

Say I launch Chisel with a local Sepolia fork, import a contract I have been developing and then deploy an instance of that contract. Then let's say the contract has a public function "getPrice()" which returns 5. Then I modify the source code of "ContractA" in "ContractA.sol" so that "getPrice()" returns 10. 

Now the REPL environment returns 10 when I invoke "getPrice()", even though I haven't reimported the contract and I am working the with already launched instance. Therefore it appears Chisel allows us to arbitrarily rewrite local blocks, because we can overwrite already deployed contracts.

chisel --fork-url sepolia
import {ContractA} from "src/ContractA.sol"
ContractA internal test = new ContractA(arg1,arg2);
test.getPrice();           //returns 5
//modify source code
test.getPrice();          //returns 10

**Comment by grandizzy** [comment]
@PeterMcQuaid indeed, that's how it works, since you modify the src of `ContractA` which is imported as `import {ContractA} from "src/ContractA.sol"` then `test.getPrice();` will return 10.

If you want to call a deployed contract you should call it by its address, e.g. for querying DAI mainnet balance you could use steps below:
- add IERC20 if to REPL contract
- add line to call contract balanceOf
- display balance

![image](https://github.com/user-attachments/assets/2977ea68-88f5-4ef4-9f7c-0a4b170af806)
