### ISSUE TITLE
mockCall not working

### ISSUE THREAD

**Issue by linghuccc** [foundry-rs/foundry#5945]
Counter.sol (contract codes) :
`
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Counter {
    uint256 private _totalSupply;
    uint256 private constant MAX = 100;
    mapping(address => uint256) public whitelistNumber;

    function totalSupply() public view returns (uint256) {
        return _totalSupply;
    }

    function mintWhitelist() external view {
        uint256 totalMinted = totalSupply();
        require(totalMinted < MAX, "All minted");

        uint256 whitelistAmount = whitelistNumber[msg.sender];
        require(whitelistAmount > 0, "Not in whitelist");
    }
}
`

Counter.t.sol (foundry test script) :

`
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console2, stdStorage, StdStorage} from "forge-std/Test.sol";
import {Counter} from "../src/Counter.sol";

contract CounterTest is Test {
    using stdStorage for StdStorage;

    Counter private counter;
    address private addrCounter;
    uint256 private constant OVER_MAX = 3000;
    address private constant USER = address(0x1);

    function setUp() public {
        counter = new Counter();
        addrCounter = address(counter);
    }

    function test_mintWhitelist() public {
        vm.mockCall(
            address(addrCounter),
            abi.encodeWithSelector(counter.totalSupply.selector),
            abi.encode(OVER_MAX)
        );
        assertEq(counter.totalSupply(), OVER_MAX);

        vm.prank(USER);
        vm.expectRevert("All minted");
        counter.mintWhitelist();
    }
}
`

Test logs:

`
Running 1 test for test/Counter.t.sol:CounterTest
[FAIL. Reason: Error != expected error: Not in whitelist != All minted] test_mintWhitelist() (gas: 14297)
Traces:
  [154579] CounterTest::setUp() 
    ├─ [77929] → new Counter@0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
    │   └─ ← 389 bytes of code
    └─ ← ()

  [14297] CounterTest::test_mintWhitelist() 
    ├─ [0] VM::mockCall(Counter: [0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f], 0x18160ddd, 0x00000000000000000000000000000000000000000000000000000000000003e8) 
    │   └─ ← ()
    ├─ [0] Counter::totalSupply() [staticcall]
    │   └─ ← 3000
    ├─ [0] VM::prank(0x0000000000000000000000000000000000000001) 
    │   └─ ← ()
    ├─ [0] VM::expectRevert(All minted) 
    │   └─ ← ()
    ├─ [4571] Counter::mintWhitelist() [staticcall]
    │   └─ ← "Not in whitelist"
    └─ ← "Error != expected error: Not in whitelist != All minted"
`

In my test script, mockCall is used to mock totalSupply to be more than MAX, so error "All minted" should be triggered. But currently it does not appear so.

**Comment by mds1** [comment]
The issue here is that `mockCall` only works for external calls, not internal jumps to functions. When `mintWhitelist` does `uint256 totalMinted = totalSupply()` it's just a JUMP to the logic in `totalSupply()`. If you changed that line `uint256 totalMinted = this.totalSupply()` that would force it to be an external call and your test would pass.

However, you don't want to do that, because making that line an external call is unnecessary so it adds gas and complexity just to facilitate testing, which isn't idea.

Instead, I'd recommend using the `StdStorage` library in forge-std to overwrite the value in the `_totalSupply` slot. You can use `forge inspect MyContract storage-layout --pretty` to view the storage layout of `MyContract` to know which slot number to use

Closing this since there's no issue, but let me know if you have any more questions
