### ISSUE TITLE
Foundry does not create a new, clean EVM environment when the `chainId` is changed

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#6008]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (87283bc 2023-10-07T00:16:07.431446791Z)`

### What command(s) is the bug in?

`forge test`

### Operating System

Linux

### Describe the bug

Foundry does not create a new, clean EVM environment when the `chainId` is changed, and a deployment of a contract to the same address therefore fails. To solve this problem currently, I return to the original snapshot state.

Simple repro:

- `CREATE2` deploy a contract
- Change `chainId` to an ID via `vm.chainId` that is not equal to the original `chainId`
- Redeploy via `CREATE2`
- Will revert due to [EIP-684](https://github.com/ethereum/EIPs/issues/684)

**Comment by Evalir** [comment]
Hmm, this seems like expected behavior and not an issue? I understand there's a point to clean up the evm state if you change chain IDs, but, it severely overloads the `chainId` cheatcode. I'll close this for now but feel free to reopen if you think this should be discussed further. I can see how the current behavior is useful for simulation or CTF purposes

**Comment by pcaversaccio** [comment]
@Evalir fwiw, you should probably close this issue as `Not Planned` instead of `Completed`. The reason why such a feature is desirable to me is that in my [`CreateX`](https://github.com/pcaversaccio/createx) tests I had to mock contract creation frontrunning and redeployment events on other chains, and snapshot reverts can become annoying. But maybe it's an edge case...
