### ISSUE TITLE
Multi-threaded compilation

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#6649]
### Component

Forge

### Describe the feature you would like

This is a completely random idea, but would it be possible to make the project compilation multi-threaded? As of now there's 1 instance of `solc` running in 1 process, apparently compiling the project contract by contract. Would it be possible to compile each contract using a separate instance of `solc` in a separate process? This could be especially useful when using the new via-IR pipeline of Solidity, because it's rather slow, it takes many minutes to compile a larger project.

**Comment by DaniPopes** [comment]
Due to Solc limitations it's currently not possible to spawn multiple compiler processes nor is Solc itself multi-threaded.
Most of the time spent in via-ir compilation is in a few select optimization steps, you could try tweaking them or other optimizer settings, but unfortunately I don't know much more than this.
