### ISSUE TITLE
forge script crashes on resuming 

### ISSUE THREAD

**Issue by yongqjn** [foundry-rs/foundry#6697]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8c11482 2023-11-16T00:32:37.968294000Z)

### What command(s) is the bug in?

forge script <path-to-script> --resume

### Operating System

macOS (Apple Silicon)

### Describe the bug

script runs a deployment sequence that involves cross-chain transactions

script initially exits prematurely with transaction underpriced error. 

running the same script with the resume flag causes the application to crash

<img width="554" alt="Screenshot 2024-01-03 at 5 06 41 PM" src="https://github.com/foundry-rs/foundry/assets/75261605/cd51c3bd-161b-4b4e-a0d4-7107e56f0ddf">

**Comment by DaniPopes** [comment]
Relevant code:
https://github.com/foundry-rs/foundry/blob/2249e077b39dd27fe09f5192223383d4146a6852/crates/forge/bin/cmd/script/sequence.rs#L356-L364

`tx.rpc` here is `TransactionWithMetadata::rpc`, which is `#[serde(skip)]`:
https://github.com/foundry-rs/foundry/blob/ff391b5fbef93a5dc6d28055501d5bdc39aee1c8/crates/forge/bin/cmd/script/transaction.rs#L46-L47

This has been skipped due to being a sensitive value in https://github.com/foundry-rs/foundry/issues/4892

I don't know what's the best solution.

cc @Evalir @klkvr @mattsse

**Comment by klkvr** [comment]
This was fixed in #6447 

@yongqjn could you please update to the latest nightly and try again?

**Comment by DaniPopes** [comment]
Ah missed this was before the fill fix was implemented. Will close with #7179 anyway.
