### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by ethever** [foundry-rs/foundry#6878]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5ea2c5e 2024-01-22T00:21:08.216952070Z)

### What command(s) is the bug in?

forge debug --debug exploit.sol --sig "exec()"

### Operating System

Linux

### Describe the bug

``` bash
(base) root@DESKTOP-Q664A32:~/projects/web3/exploits/dev5/contracts#  RUST_BACKTRACE=full forge debug --debug exploit.sol --sig "exec()"
[⠊] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  range start index 24 out of range for slice of length 23
Location: crates/debugger/src/tui/draw.rs:280

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at ./csu/../csu/libc-start.c:308

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted
```

**Comment by Evalir** [comment]
hi! thanks—is it possible for you to provide a repro so we can look into it?

@brockelmore is this the bug you ran into the other day?

**Comment by ethever** [comment]
> hi! thanks—is it possible for you to provide a repro so we can look into it?
> 
> @brockelmore is this the bug you ran into the other day?

Yes, thank you for your attention to the bug report. I am new to foundry but I will make sure to document the reproduction steps clearly as soon as I am able to dedicate the required time to it.

I seems to be a bug in frontend UI, when I first start the debugger, and then i click the `down` button to navigate the debugger to the next binary code as you can see in the red rectangal
![image](https://github.com/foundry-rs/foundry/assets/25705974/ef7034bb-db2f-44b7-b100-025b8ab4ff83)
And suddenly it will crash (something ran out of the range).

**Comment by mattsse** [comment]
@DaniPopes I don't remember who initially wrote this, so it's hard to make sense of what's going on here, but this looks very fishy:

https://github.com/foundry-rs/foundry/blob/c6790a02bb80b163469e2e3bb0b16ae95ad7334f/crates/debugger/src/tui/draw.rs#L240-L241

this sets the start line to the number of items in the vec, which then causes the index out of bounds

https://github.com/foundry-rs/foundry/blob/c6790a02bb80b163469e2e3bb0b16ae95ad7334f/crates/debugger/src/tui/draw.rs#L280-L280

unclear if the fix is as simple as just using len - 1

**Comment by ethever** [comment]
Thanks to #6886, this bug has been fixed
