### ISSUE TITLE
vm.stopAndReturnStateDiff incorrectly records storage accesses when using delegatecall

### ISSUE THREAD

**Issue by kopy-kat** [foundry-rs/foundry#7006]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Using `vm.stopAndReturnStateDiff()` you can record storage accesses. However, this is incorrectly reported for contracts that are delegatecalled to. If contract A `delegatecalls` contract B and storage is accessed during this call, then the `account` reported is contract B. Instead, it should be reported as happening in contract A.

Here is a quick poc: https://gist.github.com/kopy-kat/1a86b0b46865cf3593c00b8843920237

**Comment by kopy-kat** [comment]
One workaround to this bug is checking if the access kind is a delegatecall and if it is, then treat the accessor address as the address who made the storage read/writes.

However, this does not work because of the following:

1. Contract A calls contract B
2. Contract B delegatecalls contract C

When looking at the account access on contract C, it is of kind `DelegateCall` but the `accessor` is contract A. This makes sense given that the `msg.sender` is contract A but prevents this workaround.

Imo the solutions to this bug would be either:
- Make contract B the accessor of the delegatecall
- Report the storage writes that occur during the delegatecall in the access of contract B

**Comment by Inphi** [comment]
This is expected behavior.

You should think of `AccountAccess` as all EVM operators to an account that doesn't involve storage. That includes when an account is created, called and self destructed. Any storage accesses that occur within the context of an AccountAccess may not be the same as the account's. As you've noted in the PR.
In your snippet, you should check the referenced accounts in the `storageAccesses` array to know where exactly storage was touched.

**Comment by kopy-kat** [comment]
Ah thanks, that makes sense although it is a bit counterintuitive to have `StorageAccesses` of other accounts in an `AccountAccess`
