### ISSUE TITLE
Misleading Error Message: Could not find target contract

### ISSUE THREAD

**Issue by timolson** [foundry-rs/foundry#7244]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ac80261 2024-02-24T00:17:06.154246094Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

Running `forge script MyDeployment.sol` fails with the message `Error: Could not find target contract MyDeployment` even though the file is clearly present and the script contract name is correct.

In my case, the real bug was calling an external library method which had been accidentally marked public/external instead of internal, causing a dynamic linkage failure, and the message "Error: Could not find target contract"

You should be able to reproduce using a `library Foo { function foo() public {} }` along with a contract which calls `Foo.foo()` and finally a deployment script which constructs the contract that uses the external lib.  If you change the visibility to `internal`, the static binding / inlining causes the "Could not find target contract" message to go away.

This is the same error message as reported in #3076 but presumably with a different cause/solution.

**Comment by chad-js** [comment]
I've run into this same error a few days ago. Unsure specifically why, but may also be related to internal/external library usage as I use a few in my contracts as well. I reverted to a commit that I had deployed previously ~2 weeks ago, and I get the error on that commit now as well. I had just ran foundryup before this, which installed `nightly-4a91072e326126cd852b9c43f577e98c8e13f84f`

After installing an older version of foundry `nightly-2cb875799419c907cc3709e586ece2559e6b340e ` (https://github.com/foundry-rs/foundry/releases), I managed to get my deploy working without issue, so seems like a regression somewhere since then.
