### ISSUE TITLE
Finalized always return block 0

### ISSUE THREAD

**Issue by kamiyaa** [foundry-rs/foundry#7245]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4f00ec6 2024-02-17T00:16:39.754919679Z)

### Operating System

Linux

### Describe the bug

JSON RPC call to `get_block(BlockNumber::Finalized)` always returns the 0th block for some reason.

**Comment by mattsse** [comment]
how should we handle these tags, use the latest or do a mod 32 on the chain height?

**Comment by sveitser** [comment]
We've also ran into this. I think for us both would but fine, but if it's not too cumbersome: how about mod N with N being a parameter passed to Anvil at startup?

**Comment by mattsse** [comment]
I think we should do:
* configure an epoch number, default 32 blocks
* make it configurable via CLI

**Comment by mattsse** [comment]
@yash-atreya adding this to anvil cli args would be simple

turns out we already do a mod 32:

https://github.com/foundry-rs/foundry/blob/ce22450e4d625d12ff88fae347a68e3d3d9d2b61/crates/anvil/src/eth/backend/mem/mod.rs#L1487-L1502

but we can move the constant into a field and add a simple test for this:
manuyll mine a bunch of blocks, the request via Safe/Finalized tags

**Comment by yash-atreya** [comment]
@mattsse Thanks for the tag. I'll look into it.

**Comment by mattsse** [comment]
ah I think I know what this is, will check
