### ISSUE TITLE
cast run reports negative refunds

### ISSUE THREAD

**Issue by drortirosh** [foundry-rs/foundry#7281]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (a170021 2024-02-16T00:19:39.144885000Z)

### What command(s) is the bug in?

cast run

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
cast run --quick -r sepolia 0x023bc78f1db07e9e9fc536701ecd8e87f6c4bd60d8eeeff00d8c0f7894a0f71a -t|
```
The above trace shows at least once a refund of 4800 gas after SSTORE, and in another place, a negative refund
```
depth:2, PC:13720, gas:0xdc4c7(902343), OPCODE: "SSTORE"(85)  refund:0x0(0)
depth:2, PC:13721, gas:0xdc463(902243), OPCODE: "SWAP1"(144)  refund:0xffffffffffffed40(-4800)
```

**Comment by zerosnacks** [comment]
Hi @drortirosh what is the expected behavior?

I am not familiar enough with the subject matter to give a conclusive answer here but I would recommend reporting your finding at https://github.com/bluealloy/revm/issues as the `--trace-printer` command dumps directly from Revm, without modifications.

cc @DaniPopes, feel free to re-open if I am incorrect

**Comment by rakita** [comment]
This is possible to happen and a gas refund can be negative inside calls (At tx end it is positive).
This can happen if
* original value is 1
* SSTORE it to zero
* Call contract again and SSTORE it to 2

This will get you -4800 refund, as to negate the refund you got by SSTORE it to zero.
