### ISSUE TITLE
Caching not working by default

### ISSUE THREAD

**Issue by ClaytonNorthey92** [foundry-rs/foundry#7379]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7545c7a 2024-03-12T00:16:54.294788023Z)

### Operating System

Linux

### Describe the bug

When running `forge build` twice in a row, with no changes, the previous build isn't cached.  This affects other commands as well but is most apparent with `build`.

with an older release `forge 0.2.0 (9f6bb3b 2024-03-11T00:16:01.716842530Z)`, notice that the cache is recognized and build is not repeated.
```
forge build
[⠃] Compiling...
No files changed, compilation skipped
```

but with `forge 0.2.0 (7545c7a 2024-03-12T00:16:54.294788023Z)` (the buggy version) the build cache is not recognized
```
forge build
[⠆] Compiling...
[⠰] Compiling 1 files with 0.5.17
[⠔] Compiling 324 files with 0.8.15
[⠑] Compiling 129 files with 0.8.19
[⠊] Solc 0.5.17 finished in 38.53ms
....
```

note that between running these two commands, I didn't modify any source files.

**Comment by onbjerg** [comment]
cc @klkvr, related to https://github.com/foundry-rs/foundry/pull/7358 maybe?

**Comment by ClaytonNorthey92** [comment]
hey @onbjerg , I am realizing that I am requesting `build_info` in `foundry.toml`, so I guess this is _techncially_ working as expected, but it threw me off 🤔 

would it be appropriate to log a message that caching is disabled if `build_info` is enabled?

**Comment by klkvr** [comment]
yeah, it could be, @ClaytonNorthey92 do you have `build_info = true` in your foundry.toml?

**Comment by ClaytonNorthey92** [comment]
> yeah, it could be, @ClaytonNorthey92 do you have `build_info = true` in your foundry.toml?

@klkvr yes I am just realizing that, mentioned here with a question https://github.com/foundry-rs/foundry/issues/7379#issuecomment-1992009683

**Comment by klkvr** [comment]
Yeah, I think such warning could make sense at least when `build_info = true` is appearing in foundry.toml

**Comment by ClaytonNorthey92** [comment]
@klkvr also, how do you feel about changing the `--build-info` flag to a boolean, so you could:
```
forge build --build-info=0
```
and that would disable `build_info`, thus enabling caching

the reason that I ask is that I am running forge on a code base that I don't own, so I don't want to modify their `foundry.toml`, but we also don't use the build info files, so it would be convenient to override that via the cli.  what do you think?

**Comment by sam-goldman** [comment]
Just want to point out that #7358 causes a significant slowdown in repos that set `build_info=true` in their foundry.toml. A full recompilation occurs every time the user runs `forge test` or `forge script`. This recompilation can take minutes if the project has a lot of contracts or uses the IR compilation pipeline. I don’t think Hardhat has this issue because they recompile only the necessary contracts and their parent contracts, which solves the [original issue](https://github.com/foundry-rs/foundry/issues/4981) without force recompiling

**Comment by sam-goldman** [comment]
Just want to point out that #7358 causes a significant slowdown in repos that set `build_info=true` in their foundry.toml. A full recompilation occurs every time the user runs `forge test` or `forge script`. This recompilation can take minutes if the project has a lot of contracts or uses the IR compilation pipeline. I don’t think Hardhat has this issue because they recompile only the necessary contracts and their parent contracts, which solves the [original issue](https://github.com/foundry-rs/foundry/issues/4981) without force recompiling

@klkvr

**Comment by klkvr** [comment]
@sam-goldman foundry would not recompile any of the files if them or their imports have not been changed. Thus, unchanged parent contract would not be recompiled. The #7358 was created with idea that expected behavior is to have all sources in build-info which is only possible when no cache is enabled. 

I feel like we might want to use similar approach as hardhat here: hardhat stores build-info by default on each compiler run and keeps a mapping from contract artifact to build-info file, removing build-info file once no contract are pointing at it. That way, in the case from original issue, latest build info would still only include child contract, but it would be possible to match parent contract to build-info with data for it.

This would be a bit hardher to parse, but will be more precise and would not reauire disabling cache. Do you think such UX would make sense @sam-goldman?

CC @mattsse

**Comment by Magicking** [comment]
I started having issues related to cache as I needed both build info *and* cache files when #7358 hit; it silently disabled cache when build info was set to true (e.g.: it's a requirement for [OZ Upgrades Foundry plugin](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades#before-running))

Cache files - Seems to be needed to run a simple script otherwise, it throws
```
%> forge script SCRIPTNAME --broadcast --rpc-url http://localhost:8545 --unlocked --sender 0xDEADBEEF                                            
[⠊] Compiling...
[⠊] Compiling 105 files with 0.8.20
[⠃] Solc 0.8.20 finished in 26.92s
Compiler run successful!
Error: 
Could not open compiler cache

Context:
- "/home/magicking/PATH_TO/cache/solidity-files-cache.json": No such file or directory (os error 2)
```

And if the build info is disabled, the OZ Upgrades can't do all the validations.

Quite annoying, activating more build information shall not deactivate the cache; seems very counterintuitive!
