### ISSUE TITLE
Add CLI Argument to Disable Logging on Anvil

### ISSUE THREAD

**Issue by JakeXBT** [foundry-rs/foundry#7442]
### Component

Anvil

### Describe the feature you would like

It would be great to have a CLI argument that we could use to disable the logging on calls to the Anvil RPC, particularly for workloads which involve lots of RPC calls as this may be more performant.

**Comment by mattsse** [comment]
I think this should be doable to disable any tracing entirely via a cli argument

https://github.com/foundry-rs/foundry/blob/0026488754512acf0fd902a0d2c90cf8a09367b0/crates/anvil/src/eth/backend/executor.rs#L286-L290

so that we don't use an inspector at all here:

https://github.com/foundry-rs/foundry/blob/0026488754512acf0fd902a0d2c90cf8a09367b0/crates/anvil/src/eth/backend/executor.rs#L293-L294

this needs a new cli flag for --disable-tracing I think and then this this as a new setting

@yash-atreya in case no one picks that up soon, this should be straight forward.

**Comment by lakshya-sky** [comment]
IIRC, @JakeXBT is asking to disble logging rpc call names?

**Comment by JakeXBT** [comment]
Hi @lakshya-sky,

Yes, that's right - the console logs which print the RPC call methods such as `eth_call` or `anvil_setBalance`.

**Comment by grandizzy** [comment]
@JakeXBT using the `--silent` option as shown above suppress any anvil logs, please reopen if you still have issues with this flag applied. thank you
