### ISSUE TITLE
--isolate does not work for tload?

### ISSUE THREAD

**Issue by snreynolds** [foundry-rs/foundry#7499]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (563e062 2024-03-26T00:16:13.950236000Z)

### What command(s) is the bug in?

forge test --version

### Operating System

macOS (Apple Silicon)

### Describe the bug

tload test assertion is failing on `forge test --isolate` but passes with `forge test`.

To reproduce you can clone [this](https://github.com/Uniswap/v4-core/tree/gas-snapshots) branch and run `forge test --isolate`

**Comment by klkvr** [comment]
With `--isolate`, each call from test context is treated as a separate transaction, thus `storageLib.tstore(1, 2)` results in separate transaction context being created in which `StorageLib` transient storage is changed and immediately cleared due to ended tx context.

The simplest workaround here might look like this:
```solidity
function _test_gas_storage_set_warm() public {
    storageLib.sstore(1, 2);
    snapStart("storage store warm");
    storageLib.sstore(1, 3);
    snapEnd();
    assertEq(storageLib.sload(1), 3);
}

function test_gas_transient_set_warm() public {
    this._test_gas_storage_set_warm();
}
```

`_test_gas_storage_set_warm` will be executed atomically in a separate transaction, thus arbitrary transient storage manipulations are persisted.

**Comment by snreynolds** [comment]
Makes sense - closing this
