### ISSUE TITLE
vm.getCode doesn't find artifacts by name

### ISSUE THREAD

**Issue by martinvol** [foundry-rs/foundry#7569]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1281421 2024-04-05T00:21:15.963758000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

In a project I have a contract called `ProxyFactory`. It gets compiled and its artifacts written to `out/ProxyFactory.sol/ProxyFactory.json`.

However `vm.getCode("ProxyFactory")` fails with 
```
    ├─ [0] VM::getCode("ProxyFactory.sol") [staticcall]
    │   └─ ← [Revert] No matching artifact found
    └─ ← [Revert] No matching artifact found
```

But the following call does work: `vm.getCode("./out/ProxyFactory.sol/ProxyFactory.json")`

I've started noticing this issue since upgrading from version `forge 0.2.0 (7b45265 2023-11-21T00:18:30.267248000Z)` to `forge 0.2.0 (1281421 2024-04-05T00:21:15.963758000Z)`.

I think this issue is highly related to #6572, but as the the error messages don't match I though it was worth opening a different one.

**Comment by klkvr** [comment]
@martinvol we've inroduced smarter compilation for `forge test` in #7334 which does not recompile entire project when running tests.

Because of that, we can't anymore guarantee that all artifacts would be fresh when running tests and we've also inroduced additional vaildation of `getCode`/`getDeployedCode` calls - https://github.com/foundry-rs/foundry/pull/7334#issuecomment-1987154623

Can you confirm that this issue occurs on running a `forge test` without filters and that none of your test contracts import `ProxyFactory.sol` source directly? If so, you can simply add an import of that file to any of the test contracts and `getCode` should be working normally.

If you have import of that file somewhere in tests then this is a bug, and would be great if you could provide some kind of repro

**Comment by klkvr** [comment]
After a second thought I think a better UX would be to always recompile all files under `src` when running tests, will create a PR for that soon

**Comment by martinvol** [comment]
Oh, fth this happens even if I run `forge build` first. Is that expected?

**Comment by klkvr** [comment]
ah, I see, yeah in that case you can't have it imported anywhere because your contracts wouldn't compile otherwise.

if this contract is in `src`, then #7572 should resolve this for you

otherwise, you can either move it to `src` or enable `unchecked_cheatcode_artifacts`

**Comment by martinvol** [comment]
Wow Tha was fast
