### ISSUE TITLE
Full original source code restoration for formatter

### ISSUE THREAD

**Issue by shekhirin** [foundry-rs/foundry#780]
### Component

Forge

### Describe the feature you would like

Recently, we've merged https://github.com/gakonst/foundry/pull/201 with basic formatter functionality which includes:
- Parsing source code (respecting project structure) with [solang](https://github.com/hyperledger-labs/solang/)
- Traversing the Parse Tree and reconstructing the code on-the-go
- Reconstructing some basic nodes such as pragma directives, import directives and enum definitions

The caveat is that we've disabled `forge fmt` CLI command for now because it doesn't preserve every piece of original code: comments are missing. Solang recently added support for parsing regular comments: https://github.com/hyperledger-labs/solang/pull/656. All we need to do now is to support it in our formatter.

The hard part about it is that regular comments, in contrast to NatSpec ones, can appear everywhere, so we need to keep that in mind.

**Comment by mattsse** [comment]
comments are not part of the AST right? this makes it significantly harder to traverse the tree and simply to node -> text.

So I guess we need to find a way to inject them somehow. 
this is a bit tricky because we need to check at every node if there's a comment.

~~one idea I have is, to write an additional CommentVisitor that wraps the actual visitor and before delegating to the wrapped visitor, checks if there's comment before the node.~~

perhaps we can solve this with a macro that we add in every visit function, that checks if the next comment's location is before the location of current node, if so visit_comment?

**Comment by gakonst** [comment]
Sean's reply here: https://github.com/hyperledger-labs/solang/pull/656#issuecomment-1068168045

**Comment by mattsse** [comment]
Revert custom error support also just landed https://github.com/hyperledger-labs/solang/pull/700

**Comment by onbjerg** [comment]
@rkrasiuk / @jpopesculian We can close this right? Afaik `forge fmt` restores everything now

**Comment by rkrasiuk** [comment]
yup, closing this as completed
