### ISSUE TITLE
eip1559 gas estimation issue - transaction underpriced: tip needed 1, tip permitted 0

### ISSUE THREAD

**Issue by emilianobonassi** [foundry-rs/foundry#7806]
### Component

Forge, Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (26e6e57 2024-04-28T00:19:12.405804000Z)

### What command(s) is the bug in?

cast send 0x97c75664c1555F958F25b84D91f01aEFaFD4Fe55 --value 0.01ether -r https://sepolia.mode.network

### Operating System

macOS (Apple Silicon)

### Describe the bug

on sepolia.mode.network (and other networks) it seems that gas tip calculation has some issue

tx fails with 

```
server returned an error response: error code -32000: transaction underpriced: tip needed 1, tip permitted 0
```

workaround is go legacy `--legacy` or manual gas setting for both gas price and max gas price e.g. ```--gas-price 0.01gwei --priority-gas-price 0.01gwei```

**Comment by simplyoptimistic** [comment]
+1 encountered this on mode sepolia as well. Did not appear to have the issue on mainnet.

**Comment by mattsse** [comment]
this could be due to https://github.com/ethereum/go-ethereum/releases/tag/v1.13.12

> Fix enforcement of minimum miner tip

@klkvr maybe we should enforce tip of at least 1wei?

**Comment by klkvr** [comment]
> @klkvr maybe we should enforce tip of at least 1wei?

yeah, that should work, though not sure if this should be part of alloy's default estimator

**Comment by joroshiba** [comment]
This has been a thorn in my side since early April, we had a CI smoke test which did a basic cast send which worked until the nightly which contained this: https://github.com/foundry-rs/foundry/pull/7106 . We then switched to an old nightly which got yanked, and have done everything we can to not rely on foundry since.

Notably we are building our own rollups, and working with others who are. The default behavior around gas estimation seems to fail pretty wildly for local dev chains & rollups. Need to either manually set the priority fee or use a `--legacy` on sends. Quite annoying for deploying contracts.

**Comment by RickVM** [comment]
Yep, running into this as well on Sepolia..

**Comment by holic** [comment]
looks like https://github.com/alloy-rs/alloy/pull/808 landed, what do we need to get this into foundry? (I am unfamiliar with foundry's build/dep pipeline)

**Comment by emilianobonassi** [comment]
i think we just need to update the deps and eventually make some wiring

@gakonst @mds1 any guidance to make it happen?

**Comment by klkvr** [comment]
Should be resolved after https://github.com/alloy-rs/alloy/pull/808
