### ISSUE TITLE
Address logged during script execution is different from the actual address deployed 

### ISSUE THREAD

**Issue by 0xAplki** [foundry-rs/foundry#8054]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fbad377 2024-06-04T00:17:42.494712000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

We are noticing some weird behavior whereby when we log the address computed and returned by the ComposableStablePoolFactory using `console2.log`, the actual deployed address deployed and emitted in the pool creation event is different.

Here's a video replicating the issue: 
https://asciinema.org/a/EJNtfBkOVtlD3OdLUHgOh5e4t

We also prepared this repo that we used replicating the issue above:
https://github.com/0xAplki/foundry_bug_replication

For extra context, the PoolFactory seems to be computing the address using a salt:
```
   bytes32 someBytes32 = keccak256(
            abi.encode(address(this), vm.getNonce(ANVIL_PUB_KEY))
        ); // salt


   address csp = IComposableStablePoolFactory(cstFactory).create(
            _name,
            _name,
            tokens,
            200,
            TokenArrays.createTwoTokenArray(address(0), address(0), true),
            TokenArrays.createValueList(10800, 10800),
            false,
            500000000000000,
            makeAddr("asdf"),
            someBytes32 // salt
        );
```

it utilized in two ways:

during pool creation: https://github.com/balancer/balancer-v2-monorepo/blob/36d282374b457dddea828be7884ee0d185db06ba/pkg/pool-utils/contracts/factories/BasePoolFactory.sol#L92

in their code splitting mechanism here:
https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/solidity-utils/contracts/helpers/BaseSplitCodeFactory.sol

**Comment by klkvr** [comment]
This is happening because internally `ComposableStablePoolFactory` is using values affected by `block.timestamp` when constructing CREATE2 salt for pool deployment:

<img width="643" alt="image" src="https://github.com/foundry-rs/foundry/assets/62447812/8354e4de-7396-4681-9f55-93d31b12848c">

here `pauseWindowDuration` is calculated in `getPauseConfiguration` function which does the following:

<img width="491" alt="image" src="https://github.com/foundry-rs/foundry/assets/62447812/343cca03-d5e3-4678-b1bb-95abc37e563f">

when simulating script transactions, we don't know what will the `block.timestamp` value be once transactions land, and because of that there is mismatch between addresses in logs vs on-chain

**Comment by andreiashu** [comment]
@klkvr thanks a lot for digging and finding the root cause of this issue!


Logging the pool address _before_ the `vm.stopBroadcast()` call still outputs what seems to be the pool address computed during the simulation (even with the `--skip-simulation` flag set); with the skip simulation flag set I would have thought that any console.log in between start/stop broadcast is based of TX data that has been broadcast (mined?).

I don't understand the internals of how forge works so this assumption might be off the mark

**Comment by klkvr** [comment]
In fact forge does not collect and display actual on-chain logs at all.

Script execution is performed in 3 steps:
1. A single call to `run` performed on a fork, which collects transactions which should be broadcasted.
2. (that one is being skipped by `--skip-simulation`) All collected transactions are being simulated separately with cheatcodes disabled to ensure correctness and estimate gas usage.
3.  If step 2 was succesful, transactions are getting broadcasted.

I can see how showing the actual execution logs could be helpful, however, it is pretty expensive operation (try `cast run` on a massive tx), so I believe it'd have to be disabled by default

**Comment by halodaodev** [comment]
ok this is great info @klkvr 
happy to have this ticket closed since Foundry / Forge behaves as designed
