### ISSUE TITLE
bug: `anvil_dumpState` full block load doesn't work

### ISSUE THREAD

**Issue by samlaf** [foundry-rs/foundry#8213]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3abac32 2024-06-20T00:22:07.769597000Z)

### What command(s) is the bug in?

anvil --dump/load-state & cast block n --full

### Operating System

macOS (Apple Silicon)

### Describe the bug

This is a followup to https://github.com/foundry-rs/foundry/pull/8160. There was a bug left in that PR, which is now affecting me. It seems like full block are not dumped properly:
```
$ cast block 1 --full
Error:
block Number(Number(1)) not found
```

Does anyone know what the difference between `cast block n` and `cast block n --full`, and any intuition as to why blocks can be found, but not full blocks?

When querying via geth's BlockByNumber (which queries https://www.quicknode.com/docs/ethereum/eth_getBlockByNumber), I get panics, which seems to indicate that geth sets the  `transaction_detail_flag` to true (equivalent to `-full` flag in cast?)

**Comment by mattsse** [comment]
this looks more like an issue with how the state is reinserted

**Comment by samlaf** [comment]
Another weirdness we just noticed:

Start anvil chain with a loaded state (with block > 0). Then:
```bash
cast block-number // prints 200 (or whatever block the loaded state was dumped at)
cast block --rpc-url --field "number" // prints 0... ?!?!?!
```
and then if you `cast rpc anvil_mine` to advance the chain by 1 block. Now:
```bash
cast block-number // prints 201 (or whatever)
cast block --rpc-url --field "number" // prints 201 ?!?
```

**Comment by tuler** [comment]
This is affecting me as well. Any insight about why this happens, and a potential fix?
The dumped json state seems correct, the transactions are there.

**Comment by tuler** [comment]
https://github.com/foundry-rs/foundry/blob/72e44fb87c38b2acfa2b0b136fc1bc833f71e674/crates/anvil/src/eth/backend/mem/storage.rs#L337-L346

state loading above is not hydrating the `transactions` memory structure below, only the `blocks` and `hashes`.

https://github.com/foundry-rs/foundry/blob/72e44fb87c38b2acfa2b0b136fc1bc833f71e674/crates/anvil/src/eth/backend/mem/storage.rs#L214-L230

This makes the get below to fail, because transaction is not there.

https://github.com/foundry-rs/foundry/blob/72e44fb87c38b2acfa2b0b136fc1bc833f71e674/crates/anvil/src/eth/backend/mem/mod.rs#L1545

**Comment by KholdStare** [comment]
Could this issue be related to https://github.com/foundry-rs/foundry/issues/8179 ?
