### ISSUE TITLE
perf: use dyn Database to reduce churn and binary size

### ISSUE THREAD

**Issue by DaniPopes** [foundry-rs/foundry#8404]
### Component

Other (please describe)

### Describe the feature you would like

Currently we pass around DB generic everywhere for very little gain. I believe if we used `Box<dyn Database>` or similar we could remove all of these generics, make `Cheatcode` object-safe unifying it with `DynCheatcode`, and generally deduplicate code.

Made possible by recent improvements by @klkvr

**Comment by klkvr** [comment]
Generics currently allow us to recurse inside of inspectors by using such references: https://github.com/foundry-rs/foundry/blob/72e44fb87c38b2acfa2b0b136fc1bc833f71e674/crates/cheatcodes/src/inspector.rs#L92

how would we handle this when `ccx.ecx.db` would be a concrete type?

I think this is the only blocker rn, and one of the biggest pain points which I've also encountered when looking into custom precompiles, because `ContextPrecompiles<DB>` couldn't be reused when creating those references

**Comment by DaniPopes** [comment]
In that case `ccx.ecx.db` is `&mut dyn Db` or `Box<dyn Db>` which you can just re-borrow, unless I'm misunderstanding

**Comment by klkvr** [comment]
right, I think It'd have to be `&mut dyn Db` then? I believe you can't obtain another `Box<dyn Db>` without moving out of the `ccx.ecx.db`
