### ISSUE TITLE
Anvil does not return the correct blob after notify new transaction

### ISSUE THREAD

**Issue by ferranbt** [foundry-rs/foundry#8701]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### Operating System

None

### Describe the bug

This is a repro of the [issue](https://github.com/ferranbt/anvil_blob_repro).

The system:
- Start `Anvil` process.
- Sends blob transactions.
- Subscribes for new transaction updates.
- Queries the blob.

The problem is that when I query the blob, some of the returned transactions contain the blob but some others not.

**Comment by mattsse** [comment]
this is expected, as soon as 4844 txs are mined, the sidecar can be discarded and is usually unavailable on eth_getraw, see docs on https://github.com/alloy-rs/alloy/pull/1168

there's an argument for not deleting them in anvil, if this is useful?
if so, we can just keep the sidecar around

**Comment by ferranbt** [comment]
> the sidecar can be discarded and is usually unavailable on eth_getraw

Is this the expected behaviour in all the EL nodes?

**Comment by mattsse** [comment]
ELs should keep the sidecar around until the tx (or its block rather) is finalized in case it gets reorged. but then it can safely be deleted because it is no longer required.

But ELs usually don't search for the sidecar if the transaction is mined (not pooled).

https://github.com/ethereum/go-ethereum/blob/142c94d62842c7801e8f4d71f080ae156ecd1f2b/internal/ethapi/api.go#L2088-L2088

https://github.com/paradigmxyz/reth/blob/1f5fb90bc83dd48d38e2f376790125d68ba92f3e/crates/rpc/rpc-eth-api/src/helpers/transaction.rs#L116-L119

so even if the tx is mined but unfinalized, it is usually returned without the sidecar
