### ISSUE TITLE
Feat: Forge Exec Arbitrary bytecode

### ISSUE THREAD

**Issue by refcell** [foundry-rs/foundry#899]
### Component

Forge

### Overview

Creates a new `forge` subcommand that executes arbitrary bytecode.

Example: `forge exec <bytecode>`

A very useful feature built into this would be a `--debug` flag that executes the bytecode in a debugging context like #356

**Comment by tynes** [comment]
This command is similar to `hevm exec` - is the idea to basically have it be the same command?

**Comment by onbjerg** [comment]
Any reason we would not roll this into `forge run`? Currently `cast` does not have any idea how to use the EVM at all (IIRC) and if we change that `cast` will probably grow a lot in size

**Comment by abigger87** [comment]
> Any reason we would not roll this into `forge run`? Currently `cast` does not have any idea how to use the EVM at all (IIRC) and if we change that `cast` will probably grow a lot in size

Agreed. In favor, changing.

**Comment by abigger87** [comment]
Cool if I take this issue on?

**Comment by onbjerg** [comment]
If you feel like this is not going to be a huge change and you can solve it before midday Monday CET then go for it. I will have to port it over when I get to debugging/`forge run`, which I think I'll get to at that time :smile:

**Comment by flyq** [comment]
So what is the current progress of this feature?
This function, combined with the forge fork, can analyze the smart contract bytecode on the chain very beautifully, especially when there seems to be no other tools that can analyze the stack/memory/storage's changes caused by composability calls with multiple unverified-source-code smart contracts
