### ISSUE TITLE
bug: verification in forge create with custom explorer when passing `--verifier etherscan` with `--etherscan-api-key` doesn't work 

### ISSUE THREAD

**Issue by antoinedc** [foundry-rs/foundry#9220]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a428ba6 2024-10-29T00:21:52.576754000Z)

### What command(s) is the bug in?

forge create

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running:
```
forge create \
  --rpc-url http://localhost:8545 \
  --private-key 0x1234 \
  contracts/UniswapV2Factory.sol:UniswapV2Factory \
  --constructor-args 0xF4E864F40476ac400a5AD55f8eA06c6CCd08597d --legacy \
  --verify \
  --verifier etherscan \
  --verifier-url http://localhost:8888/api \
  --etherscan-api-key anvil-23
```

I get this ouput:
```
[⠊] Compiling...
[⠆] Compiling 11 files with Solc 0.5.16
[⠰] Solc 0.5.16 finished in 250.35ms
Compiler run successful!
Error: ETHERSCAN_API_KEY must be set
```

Setting ETHERSCAN_API_KEY env variable does the same
http://localhost:8888/api is an Etherscan compatible API (https://tryethernal.com)

`forge verify-contract` works as expected though

**Comment by grandizzy** [comment]
@antoinedc pls check book on how to add unknown chains in config https://book.getfoundry.sh/reference/config/etherscan#etherscan

**Comment by antoinedc** [comment]
Thanks @grandizzy for the reply. I had actually seen that page before, but I'm looking at being able to do the verification without having to create or edit an extra file, directly in the forge create command.

Are there any technical reasons why this can't be supported?

This really does make a difference on my end. Contract verification is obviously very important for any explorer, and so is compatibility with user tooling/workflow. Not being able to be a drop-in replacement to Blockscout or Etherscan hurts adoption. And "gatekeeping" this feature to those two explorers seems a bit too opinionated.

As an example, Hardhat verification system works perfectly with any endpoint (based on Etherscan API-), and users can switch explorers by just changing a value, without having to change anything in their workflow.

**Comment by grandizzy** [comment]
I see, IMO is easier and cleaner to put an alias in config file (that could be easily reused in other projects) opposed to change command but I can understand your point. @zerosnacks could you please share your thoughts? thanks!

**Comment by zerosnacks** [comment]
Hi @antoinedc

I think this issue arises because you are passing the `verifier` as `etherscan` forcing a check for `ETHERSCAN_API_KEY must be set`

In lieu of a more generalized solution I would be open to accept a PR that adds your custom explorer as a `EtherscanVerificationProvider` to here:

https://github.com/foundry-rs/foundry/blob/a428ba6ad8856611339a6319290aade3347d25d9/crates/verify/src/provider.rs#L152-L176

**Comment by zerosnacks** [comment]
Hi @antoinedc, unfortunately this is due to the incorrect use of the `--verifier etherscan`. When this is passed a number of assumptions are made in regards to the resolving of the Etherscan configuration using `alloy-chains`. Due to `anvil-hardhat` not having a valid Etherscan API URL we fail to resolve this `api_url`.

cc @grandizzy, this incorrectly casts to `None` resulting in the `ETHERSCAN_API_KEY must be set` error

https://github.com/foundry-rs/foundry/blob/48930a68c583e8c56abd09e8b5af1cdb85367348/crates/config/src/lib.rs#L1296

https://github.com/foundry-rs/foundry/blob/48930a68c583e8c56abd09e8b5af1cdb85367348/crates/config/src/etherscan.rs#L263

I think the simplest solution here is to ask alternative explorers to add themselves to the `VerificationProviderType` and declare that they are compatible with an API rather than us inferring it. It is explicit and standardized.

We should also disallow the `--etherscan-api-key` flag to be passed if a verifier other than `--verifier etherscan` is set.

Re-opening as there are some action items

**Comment by antoinedc** [comment]
>  When this is passed a number of assumptions are made in regards to the resolving of the Etherscan configuration using alloy-chains. Due to anvil-hardhat not having a valid Etherscan API URL we fail to resolve this api_url.

Aah got it, I see. Thanks for the explanation! From what I've seen in other verifiers, the "method" (ie etherscan, sourcify, etc...), is more about knowing what api format to expect (and then allowing any endpoint) rather than something that will "force" the usage of a specific platform.
