### ISSUE TITLE
error code -32602: duplicate field `data` at line 1 column 194

### ISSUE THREAD

**Issue by HowHsu** [foundry-rs/foundry#9327]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (36cbce7 2024-11-15T00:21:52.319667269Z)

### What command(s) is the bug in?

cast call

### Operating System

Linux

### Describe the bug

`cast call {contract_address} {function_sig} {args} --rpc-url ...`

Call a view contract function =, but got this error retuns:
`Error: server returned an error response: error code -32602: duplicate field `data` at line 1 column 194`

**Comment by yash-atreya** [comment]
Can you provide the full command with the contract address and func sig?

**Comment by yash-atreya** [comment]
Can you provide the full command with the contract address and func sig?

**Comment by HowHsu** [comment]
> Can you provide the full command with the contract address and func sig?

It's a private blockchain, the func is "owner()" (the owner() of Ownable)

**Comment by HowHsu** [comment]
cast call 0xECaE5ba39d697753D1936D76a3852FeB08c11d82 "owner()"  --rpc-url

**Comment by grandizzy** [comment]
It looks like an issue with the chain as it cannot be reproduced on local anvil nor or mainnet / optimism etc. We'll probably need more details for the ticket @HowHsu

**Comment by HowHsu** [comment]
> It looks like an issue with the chain as it cannot be reproduced on local anvil nor or mainnet / optimism etc. We'll probably need more details for the ticket @HowHsu

More info: I alternatively use foundry solidity script, it works

**Comment by HowHsu** [comment]
I guess the root-cause is maybe that:
1. the chain is not a standard evm chain
2. difference between cast and foundry script

The chain is called Deep Brain Chain, which is a variant of Substrate

**Comment by HowHsu** [comment]
> Yeah, but non standard could be incompatible in some aspects like this (here's another ticket / sample with chain that doesn't follow standard [#7640 (comment)](https://github.com/foundry-rs/foundry/issues/7640#issuecomment-2429278005)). Do you use the same evm_version for both script and cast? (if not specified it is using paris)

How can I set the evm version for script and cast? I assume the evm_version in foundry.toml is for script?

**Comment by grandizzy** [comment]
that's right, for cast you can pass it as `--evm-version paris`

**Comment by HowHsu** [comment]
> that's right, for cast you can pass it as `--evm-version paris`

This parameter doesn't exist

**Comment by grandizzy** [comment]
> > that's right, for cast you can pass it as `--evm-version paris`
> 
> This parameter doesn't exist

```
cast run --help | grep -A3 evm
      --evm-version <EVM_VERSION>
          The EVM version to use.
          
          Overrides the version specified in the config.
```

**Comment by HowHsu** [comment]
> > > that's right, for cast you can pass it as `--evm-version paris`
> > 
> > 
> > This parameter doesn't exist
> 
> ```
> cast run --help | grep -A3 evm
>       --evm-version <EVM_VERSION>
>           The EVM version to use.
>           
>           Overrides the version specified in the config.
> ```
"Runs a published transaction in a local environment and prints the trace"  ------------From the `cast run --help`
While what I want is `cast send`

**Comment by chuwt** [comment]
Hi there, I also got the same error when I was trying to send native token via command:
`cast send 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 --value 100ether --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80`

The error was:
`server returned an error response: error code -32602: duplicate field `data` at line 1 column 214, data: {"message":"duplicate field `data` at line 1 column 214","data":{"method":"eth_estimateGas","params":[{"from":"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266","to":"0x70997970C51812dc3A010C7d01b50e0d17dc79C8","gasPrice":"0x3e05f1fd","value":"0x56bc75e2d63100000","input":"0x","data":"0x","nonce":"0x1","chainId":"0x7a69"},"pending"]}}`

The reason was the code set both `data` and `input` here:
https://github.com/foundry-rs/foundry/blob/00efa0d5965269149f374ba142fb1c3c7edd6c94/crates/cast/bin/tx.rs#L312-L315

I guess somewhere like hardhat refuse the request, need more investigation.

**Comment by rpedroni** [comment]
Getting the same issue for any of my local hardhat nodes. Adding `--trace` "fixes" it
![image](https://github.com/user-attachments/assets/87293e7e-4d1c-4d76-84e7-70b4a29cbd82)
