### ISSUE TITLE
Report from beginner in Solidity and Foundry 

### ISSUE THREAD

**Issue by nikkolasg** [foundry-rs/foundry#934]
### Component

Forge

### Describe the feature you would like

Hi,

I've recently embarked on the path of developing on Solidity and I started directly with Foundry (no real previous experience with Truffle etc). I am on Foundry because my application code needs to be in Rust so I thought I would do the whole thing in Rust, which seems like a good idea :) 
I've been pretty far in where I wanted to go and I've noted several items that I think could really benefit from some care as to help the development experience on Foundry/Forge. 

1. Bindings should provide way to deploy contract natively easily. Currently need to read the JSON file etc it's cumbersome, while a `MyContract::deploy()` should be in reach I believe.
2. Using Ganache should just work ideally - I had to specify the chain id and the "legacy()" each time. Maybe for the former we can detect the chain id or take by default the 1337 from Ganache.
3. More examples on how to use the low levels -> passing from U256 to uint? I had to go really deep in the stack passing from ether-rs to ethabi to ethereum-types to find how to bring it back to primitive rust value.
4. More documentation about send() vs call() and maybe restrctions or warnings: call() currently doesn't set the from: address also
5. Compatibilities with versions of forge. My bindings were not the same on CI and local while both versions were 0.1.0 only the commit changed.

Thanks a lot for the work here, except these glitches, I'm really loving it so far, it's a great platform ! Well done !

**Comment by onbjerg** [comment]
Great report, thank you for that 😄 WRT your fifth point, Foundry is still moving really fast so the artifacts are changing as well and there will be incompatibilities until we cut a stable release

**Comment by yohanelly95** [comment]
Hey, so adding `--legacy` tag with my deployment command, and there is no response. Usually I see something like this `No files changed, compilation skipped
Deployer: 0x645efC03Af16a2D8D9F67587be502830E80627A2
Deployed to: 0xcd0db8884A9EAcC5A5DAd1E4537DC8197EB5794C
Transaction hash: 0xf514a9601ac7fc54336fae740a96ed1f25231d7380de789fc087b7588a4b5c68
`. But with legacy there is nothing, no response although the deployment is successful. I would need the response since I run a post deployment script, so I'll need the contract addresses that were deployed. Is there a way better way to deploy multiple contracts and get their addresses ?

**Comment by onbjerg** [comment]
Thank you for this feedback again! :smile: I will close this issue, addressing some of your points, but I would highly encourage you to post feedback for issues you feel haven't been addressed since you opened this one so we can take a look at them individually.

Some of your feedback also seems like it is more for ethers-rs - I would highly encourage you to post the feedback there as well if relevant :smile: 

>Bindings should provide way to deploy contract natively easily. Currently need to read the JSON file etc it's cumbersome, while a MyContract::deploy() should be in reach I believe.

This is now supported - see https://github.com/gakonst/ethers-rs/issues/1013

>Using Ganache should just work ideally - I had to specify the chain id and the "legacy()" each time. Maybe for the former we can detect the chain id or take by default the 1337 from Ganache.

This seems like ethers-rs feedback? In any case, we also have Anvil now which supports EIP1559

>Compatibilities with versions of forge. My bindings were not the same on CI and local while both versions were 0.1.0 only the commit changed.

1.0 soon:tm: although we might never have perfect 1:1 lock-step with ethers-rs so stuff might be out of sync from time to time. The version numbers now are more like milestones - we release a new version nightly.
