### ISSUE TITLE
`vm.expectEmit` to support partial matching on event fields

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [foundry-rs/foundry#9385]
### Component

Forge

### `vm.expectEmit` to support partial matching on event fields

Currently all event fields have to be specified in advance before calling the emitting function. At this point some event fields may still be unknown e.g. an ID of an entity created by the emitting function. Possible solutions
- Match only on the type of event e.g. match only on `CrowdFunding.EvLaunch` type (see the example below)
- Indicate event fields to be ignored e.g. ignore the `campaignID` field

### Additional context

Given a function to launch a crowd funding campaign
```solidity
  function launch(uint goal) external returns (uint) {
    uint campaignID = uint(keccak256(abi.encode(block.timestamp)));
    address owner = msg.sender;
    emit EvLaunch(campaignID, owner, goal);
    return campaignID;
  }
```

The test does not pass because the `campaignID` is not yet known
```solidity
  function testLaunch() public {
    uint goal = 10 ether;
    vm.expectEmit(true, true, false, true);
    emit CrowdFunding.EvLaunch(<campaignID should be ignored>, owner, goal);
    vm.prank(owner);
    uint campaignID = fund.launch(goal);
  }
```

**Comment by grandizzy** [comment]
@volodymyrprokopyuk that's already supported, check book https://book.getfoundry.sh/forge/cheatcodes?highlight=expectEmit#cheatcodes

In your code `vm.expectEmit(true, true, false, true);` has last arg `true` which means to check for exact data match, hence fails. Setting that to false will make your test pass. However, if `campaignID` is indexed (hence a topic) then you will have to change expect emit as  `vm.expectEmit(false, true, false, false);` otherwise test will fail since `campaignID` topics doesn't match.

Hope this makes sense. Thanks!
