### ISSUE TITLE
`cast run` doesn't output much info

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#9416]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ce66e14 2024-10-21T00:26:14.754145000Z)

### What command(s) is the bug in?

cast run

### Operating System

macOS (Intel)

### Describe the bug

I'm trying to debug [this](https://sepolia.etherscan.io/tx/0x3aec73a664f755e96eba2fa02126976dbd99d7ae22b1a790aed2a8ff98cfe66e) transaction with `cast run`, but it doesn't output much helpful info:

<img width="1036" alt="image" src="https://github.com/user-attachments/assets/a1a0442d-d089-4f09-8da3-26d6f717691d">

**Comment by grandizzy** [comment]
@zhiqiangxu I am not sure what other details could be displayed since the tx fails with out of gas so not much executed, if you clone contract locally by
```
forge clone 0x27504265a9bc4330e3fe82061a60cd8b6369b4dc  -c 11155111 --etherscan-api-key $API_KEY
```
and execute a tx that passed like 0x7d709c93be5963d0ea7a0b36bfe2e87f1dd2d096cafeb814cf930886c7581d21 with local artifacts
```
cast run --la --decode-internal 0x7d709c93be5963d0ea7a0b36bfe2e87f1dd2d096cafeb814cf930886c7581d21 --rpc-url $RPC_URL --etherscan-api-key $ETHERSCAN_KE
```
you can see all traces even for internal calls are displayed.

![image](https://github.com/user-attachments/assets/98d48545-f6a5-46a9-9313-78db1e9c762d)

The tx you sent is with a much lower limit than the other txes so I suspect that's the reason, yours

![image](https://github.com/user-attachments/assets/74ee23d7-45ba-4bd0-9117-473225baf57b)

vs

![image](https://github.com/user-attachments/assets/60fe0818-a2d8-4775-a2a2-0c99c84b3ca1)

**Comment by grandizzy** [comment]
@zhiqiangxu hope this makes sense, please reopen if it doesn't. thank you!

**Comment by grandizzy** [comment]
> @grandizzy Thanks for the answer! But what's the `forge clone` command used for? I don't see the result being used anywhere above .

it downloads sources locally so you could use `cast --la` to use local artifacts or export signatures with `forge selectors cache`. This is useful when you have multiple contracts so you can obtain all sources / signatures and decode all traces/
