### ISSUE TITLE
[POC repo included] default foundry.toml "src" remappings dont work correctly

### ISSUE THREAD

**Issue by DrakeEvans** [foundry-rs/foundry#9454]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

I use `src/contracts` to store all my smart contracts, this means my `foundry.toml` contains the line 
`src = "src/contracts"`
I like to use `contracts/` as an import alias, such that I don't need to use relative imports everywhere, this means I have a `remapping.txt` with the line:
`contracts/=src/contracts/`

This causes foundry build to crash.  When I switch the line:
`src = "src/contracts"` => `src = "src"` in `foundry.toml` the compilation works

reproduction repo: https://github.com/DrakeEvans/foundry-remapping-bug

Recreate: run `forge build -w`
Fix: comment out line 3 and uncomment line 2

Fwiw, this is definitely a regression as I have been using this configuration 6 months ago fine

**Comment by grandizzy** [comment]
hey @DrakeEvans thanks for your report! Indeed, this was changed in PR https://github.com/foundry-rs/foundry/pull/9258 in order to solve https://github.com/foundry-rs/foundry/issues/3440 (that is to avoid any `src` remapping in deps to be applied for the root project). As you mentioned, changing `src = "src/contracts"` to `src = "src"`  would be the proper fix (as `contracts/=src/contracts/` remapping will be properly resolved), lmk if this doesn't make sense.

**Comment by DrakeEvans** [comment]
The issue with that fix is that it is now compiling a bunch of extra contracts potentially.  I want to limit compiling to just whats in src/contracts.  Im not clear on the value of what you are describing

**Comment by DrakeEvans** [comment]
@grandizzy I can confirm that #9466 fixes the issue
