### ISSUE TITLE
Deleting a mapping entry in Chisel, doesn't work

### ISSUE THREAD

**Issue by hahmadipoor** [foundry-rs/foundry#9600]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.3.0 (3ba3d5f 2024-12-25T00:20:45.124735866Z)

### Operating System

Linux

### Describe the bug

I created a mapping using chisel,  but when I delete an entry it doesn't get deleted. 
```
   mapping(address =>address) public tokenToOwner;
   tokenToOwner[address(1)]=address(11)
   tokenToOwner[address(2)]=address(22)
   delete tokenToOwner[address(1)]
   tokenToOwner[address(1)]
```
The last line of the above commands should return 0, but it still returns the previous value. There seems to be a problem with Chisel.

**Comment by grandizzy** [comment]
@hahmadipoor yeah, that's an known issue tracked here https://github.com/foundry-rs/foundry/issues/7193#issuecomment-2438113201 so you need to end the delete line with semicolon in order to be accounted (`delete tokenToOwner[address(1)];`) To see exactly the code that gets executed you can use `!source`, without ending in ; shows
```Solidity
    /// @notice REPL contract entry point
    function run() public {
        tokenToOwner[address(1)] = address(11);
        tokenToOwner[address(2)] = address(22);
    }
```

with ; line gets added
```Solidity
    /// @notice REPL contract entry point
    function run() public {
        tokenToOwner[address(1)] = address(11);
        tokenToOwner[address(2)] = address(22);
        delete tokenToOwner[address(1)];
    }
```

Going to close as a dupe, will be fixed with #7193 thank you
